// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8bb2cf947e486dda2e680665792a6bb805dd879866ff4dcddb7bbdaea4e8a9cf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package xberg

/*
#cgo CFLAGS: -I${SRCDIR}/include
#include "xberg.h"
#include <stdlib.h>
#include <string.h>

extern int32_t goOcrBackendProcessImage(void* user_data, uint8_t* image_bytes, size_t image_bytes_len, char* config, char** out_result, char** out_error);
extern int32_t goOcrBackendProcessImageFile(void* user_data, char* path, char* config, char** out_result, char** out_error);
extern int32_t goOcrBackendSupportsLanguage(void* user_data, char* lang, char** out_error);
extern int32_t goOcrBackendBackendType(void* user_data, char** out_result, char** out_error);
extern int32_t goOcrBackendSupportedLanguages(void* user_data, char** out_result, char** out_error);
extern int32_t goOcrBackendSupportsTableDetection(void* user_data, char** out_error);
extern int32_t goOcrBackendSupportsDocumentProcessing(void* user_data, char** out_error);
extern int32_t goOcrBackendEmitsStructuredMarkdown(void* user_data, char** out_error);
extern int32_t goOcrBackendProcessDocument(void* user_data, char* _path, char* _config, char** out_result, char** out_error);
extern int32_t goOcrBackendName(void*, char**, char**);
extern int32_t goOcrBackendVersion(void*, char**, char**);
extern int32_t goOcrBackendInitialize(void*, char**);
extern int32_t goOcrBackendShutdown(void*, char**);
extern void goOcrBackendFreeUserData(void*);
extern void goOcrBackendFreeString(char*);
extern int32_t goPostProcessorProcess(void* user_data, char* result, char* config, char** out_error);
extern int32_t goPostProcessorProcessingStage(void* user_data, char** out_result, char** out_error);
extern int32_t goPostProcessorShouldProcess(void* user_data, char* _result, char* _config, char** out_error);
extern uint64_t goPostProcessorEstimatedDurationMs(void* user_data, char* _result, char** out_error);
extern int32_t goPostProcessorPriority(void* user_data, char** out_error);
extern int32_t goPostProcessorName(void*, char**, char**);
extern int32_t goPostProcessorVersion(void*, char**, char**);
extern int32_t goPostProcessorInitialize(void*, char**);
extern int32_t goPostProcessorShutdown(void*, char**);
extern void goPostProcessorFreeUserData(void*);
extern void goPostProcessorFreeString(char*);
extern int32_t goValidatorValidate(void* user_data, char* result, char* config, char** out_error);
extern int32_t goValidatorShouldValidate(void* user_data, char* _result, char* _config, char** out_error);
extern int32_t goValidatorPriority(void* user_data, char** out_error);
extern int32_t goValidatorName(void*, char**, char**);
extern int32_t goValidatorVersion(void*, char**, char**);
extern int32_t goValidatorInitialize(void*, char**);
extern int32_t goValidatorShutdown(void*, char**);
extern void goValidatorFreeUserData(void*);
extern void goValidatorFreeString(char*);
extern int32_t goDocumentExtractorExtract(void* user_data, char* input, char* config, char** out_result, char** out_error);
extern int32_t goDocumentExtractorSupportedMimeTypes(void* user_data, char** out_result, char** out_error);
extern int32_t goDocumentExtractorPriority(void* user_data, char** out_error);
extern int32_t goDocumentExtractorCanHandle(void* user_data, char* _path, char* _mime_type, char** out_error);
extern int32_t goDocumentExtractorName(void*, char**, char**);
extern int32_t goDocumentExtractorVersion(void*, char**, char**);
extern int32_t goDocumentExtractorInitialize(void*, char**);
extern int32_t goDocumentExtractorShutdown(void*, char**);
extern void goDocumentExtractorFreeUserData(void*);
extern void goDocumentExtractorFreeString(char*);
extern size_t goEmbeddingBackendDimensions(void* user_data, char** out_error);
extern int32_t goEmbeddingBackendEmbed(void* user_data, char* texts, char** out_result, char** out_error);
extern int32_t goEmbeddingBackendName(void*, char**, char**);
extern int32_t goEmbeddingBackendVersion(void*, char**, char**);
extern int32_t goEmbeddingBackendInitialize(void*, char**);
extern int32_t goEmbeddingBackendShutdown(void*, char**);
extern void goEmbeddingBackendFreeUserData(void*);
extern void goEmbeddingBackendFreeString(char*);
extern int32_t goRendererRenderResult(void* user_data, char* result, char** out_result, char** out_error);
extern int32_t goRendererName(void*, char**, char**);
extern int32_t goRendererVersion(void*, char**, char**);
extern int32_t goRendererInitialize(void*, char**);
extern int32_t goRendererShutdown(void*, char**);
extern void goRendererFreeUserData(void*);
extern void goRendererFreeString(char*);
extern int32_t goRerankerBackendRerank(void* user_data, char* query, char* documents, char** out_result, char** out_error);
extern int32_t goRerankerBackendName(void*, char**, char**);
extern int32_t goRerankerBackendVersion(void*, char**, char**);
extern int32_t goRerankerBackendInitialize(void*, char**);
extern int32_t goRerankerBackendShutdown(void*, char**);
extern void goRerankerBackendFreeUserData(void*);
extern void goRerankerBackendFreeString(char*);
extern size_t goTokenizerBackendCountTokens(void* user_data, char* text, char** out_error);
extern int32_t goTokenizerBackendName(void*, char**, char**);
extern int32_t goTokenizerBackendVersion(void*, char**, char**);
extern int32_t goTokenizerBackendInitialize(void*, char**);
extern int32_t goTokenizerBackendShutdown(void*, char**);
extern void goTokenizerBackendFreeUserData(void*);
extern void goTokenizerBackendFreeString(char*);
// Note: suppress incompatible-pointer-types warnings because cgo exports may have
// signatures that C strictly typechecks. The function pointers are ABI-compatible.
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wincompatible-function-pointer-types"
#else
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#endif
// C inline function to construct the XBERGXbergOcrBackendVTable vtable.
// This allows direct assignment of function pointers with proper casting.
static inline XBERGXbergOcrBackendVTable* xberg_ocr_backend_vtable_new(void) {
	// Note: All function pointers are assigned with generic casts to suppress warnings.
	// The actual function addresses are ABI-compatible despite signature differences.
	XBERGXbergOcrBackendVTable* vtable = (XBERGXbergOcrBackendVTable*)malloc(sizeof(XBERGXbergOcrBackendVTable));
	if (!vtable) return NULL;
	memset(vtable, 0, sizeof(XBERGXbergOcrBackendVTable));	vtable->process_image = (void(*)(void))goOcrBackendProcessImage;	vtable->process_image_file = (void(*)(void))goOcrBackendProcessImageFile;	vtable->supports_language = (void(*)(void))goOcrBackendSupportsLanguage;	vtable->backend_type = (void(*)(void))goOcrBackendBackendType;	vtable->supported_languages = (void(*)(void))goOcrBackendSupportedLanguages;	vtable->supports_table_detection = (void(*)(void))goOcrBackendSupportsTableDetection;	vtable->supports_document_processing = (void(*)(void))goOcrBackendSupportsDocumentProcessing;	vtable->emits_structured_markdown = (void(*)(void))goOcrBackendEmitsStructuredMarkdown;	vtable->process_document = (void(*)(void))goOcrBackendProcessDocument;	vtable->free_string = (void(*)(void))goOcrBackendFreeString;
	vtable->free_user_data = (void(*)(void))goOcrBackendFreeUserData;
	vtable->name_fn = (void(*)(void))goOcrBackendName;
	vtable->version_fn = (void(*)(void))goOcrBackendVersion;
	vtable->initialize_fn = (void(*)(void))goOcrBackendInitialize;
	vtable->shutdown_fn = (void(*)(void))goOcrBackendShutdown;

	return vtable;
}
#pragma GCC diagnostic pop
// Note: suppress incompatible-pointer-types warnings because cgo exports may have
// signatures that C strictly typechecks. The function pointers are ABI-compatible.
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wincompatible-function-pointer-types"
#else
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#endif
// C inline function to construct the XBERGXbergPostProcessorVTable vtable.
// This allows direct assignment of function pointers with proper casting.
static inline XBERGXbergPostProcessorVTable* xberg_post_processor_vtable_new(void) {
	// Note: All function pointers are assigned with generic casts to suppress warnings.
	// The actual function addresses are ABI-compatible despite signature differences.
	XBERGXbergPostProcessorVTable* vtable = (XBERGXbergPostProcessorVTable*)malloc(sizeof(XBERGXbergPostProcessorVTable));
	if (!vtable) return NULL;
	memset(vtable, 0, sizeof(XBERGXbergPostProcessorVTable));	vtable->process = (void(*)(void))goPostProcessorProcess;	vtable->processing_stage = (void(*)(void))goPostProcessorProcessingStage;	vtable->should_process = (void(*)(void))goPostProcessorShouldProcess;	vtable->estimated_duration_ms = (void(*)(void))goPostProcessorEstimatedDurationMs;	vtable->priority = (void(*)(void))goPostProcessorPriority;	vtable->free_string = (void(*)(void))goPostProcessorFreeString;
	vtable->free_user_data = (void(*)(void))goPostProcessorFreeUserData;
	vtable->name_fn = (void(*)(void))goPostProcessorName;
	vtable->version_fn = (void(*)(void))goPostProcessorVersion;
	vtable->initialize_fn = (void(*)(void))goPostProcessorInitialize;
	vtable->shutdown_fn = (void(*)(void))goPostProcessorShutdown;

	return vtable;
}
#pragma GCC diagnostic pop
// Note: suppress incompatible-pointer-types warnings because cgo exports may have
// signatures that C strictly typechecks. The function pointers are ABI-compatible.
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wincompatible-function-pointer-types"
#else
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#endif
// C inline function to construct the XBERGXbergValidatorVTable vtable.
// This allows direct assignment of function pointers with proper casting.
static inline XBERGXbergValidatorVTable* xberg_validator_vtable_new(void) {
	// Note: All function pointers are assigned with generic casts to suppress warnings.
	// The actual function addresses are ABI-compatible despite signature differences.
	XBERGXbergValidatorVTable* vtable = (XBERGXbergValidatorVTable*)malloc(sizeof(XBERGXbergValidatorVTable));
	if (!vtable) return NULL;
	memset(vtable, 0, sizeof(XBERGXbergValidatorVTable));	vtable->validate = (void(*)(void))goValidatorValidate;	vtable->should_validate = (void(*)(void))goValidatorShouldValidate;	vtable->priority = (void(*)(void))goValidatorPriority;	vtable->free_string = (void(*)(void))goValidatorFreeString;
	vtable->free_user_data = (void(*)(void))goValidatorFreeUserData;
	vtable->name_fn = (void(*)(void))goValidatorName;
	vtable->version_fn = (void(*)(void))goValidatorVersion;
	vtable->initialize_fn = (void(*)(void))goValidatorInitialize;
	vtable->shutdown_fn = (void(*)(void))goValidatorShutdown;

	return vtable;
}
#pragma GCC diagnostic pop
// Note: suppress incompatible-pointer-types warnings because cgo exports may have
// signatures that C strictly typechecks. The function pointers are ABI-compatible.
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wincompatible-function-pointer-types"
#else
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#endif
// C inline function to construct the XBERGXbergDocumentExtractorVTable vtable.
// This allows direct assignment of function pointers with proper casting.
static inline XBERGXbergDocumentExtractorVTable* xberg_document_extractor_vtable_new(void) {
	// Note: All function pointers are assigned with generic casts to suppress warnings.
	// The actual function addresses are ABI-compatible despite signature differences.
	XBERGXbergDocumentExtractorVTable* vtable = (XBERGXbergDocumentExtractorVTable*)malloc(sizeof(XBERGXbergDocumentExtractorVTable));
	if (!vtable) return NULL;
	memset(vtable, 0, sizeof(XBERGXbergDocumentExtractorVTable));	vtable->extract = (void(*)(void))goDocumentExtractorExtract;	vtable->supported_mime_types = (void(*)(void))goDocumentExtractorSupportedMimeTypes;	vtable->priority = (void(*)(void))goDocumentExtractorPriority;	vtable->can_handle = (void(*)(void))goDocumentExtractorCanHandle;	vtable->free_string = (void(*)(void))goDocumentExtractorFreeString;
	vtable->free_user_data = (void(*)(void))goDocumentExtractorFreeUserData;
	vtable->name_fn = (void(*)(void))goDocumentExtractorName;
	vtable->version_fn = (void(*)(void))goDocumentExtractorVersion;
	vtable->initialize_fn = (void(*)(void))goDocumentExtractorInitialize;
	vtable->shutdown_fn = (void(*)(void))goDocumentExtractorShutdown;

	return vtable;
}
#pragma GCC diagnostic pop
// Note: suppress incompatible-pointer-types warnings because cgo exports may have
// signatures that C strictly typechecks. The function pointers are ABI-compatible.
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wincompatible-function-pointer-types"
#else
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#endif
// C inline function to construct the XBERGXbergEmbeddingBackendVTable vtable.
// This allows direct assignment of function pointers with proper casting.
static inline XBERGXbergEmbeddingBackendVTable* xberg_embedding_backend_vtable_new(void) {
	// Note: All function pointers are assigned with generic casts to suppress warnings.
	// The actual function addresses are ABI-compatible despite signature differences.
	XBERGXbergEmbeddingBackendVTable* vtable = (XBERGXbergEmbeddingBackendVTable*)malloc(sizeof(XBERGXbergEmbeddingBackendVTable));
	if (!vtable) return NULL;
	memset(vtable, 0, sizeof(XBERGXbergEmbeddingBackendVTable));	vtable->dimensions = (void(*)(void))goEmbeddingBackendDimensions;	vtable->embed = (void(*)(void))goEmbeddingBackendEmbed;	vtable->free_string = (void(*)(void))goEmbeddingBackendFreeString;
	vtable->free_user_data = (void(*)(void))goEmbeddingBackendFreeUserData;
	vtable->name_fn = (void(*)(void))goEmbeddingBackendName;
	vtable->version_fn = (void(*)(void))goEmbeddingBackendVersion;
	vtable->initialize_fn = (void(*)(void))goEmbeddingBackendInitialize;
	vtable->shutdown_fn = (void(*)(void))goEmbeddingBackendShutdown;

	return vtable;
}
#pragma GCC diagnostic pop
// Note: suppress incompatible-pointer-types warnings because cgo exports may have
// signatures that C strictly typechecks. The function pointers are ABI-compatible.
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wincompatible-function-pointer-types"
#else
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#endif
// C inline function to construct the XBERGXbergRendererVTable vtable.
// This allows direct assignment of function pointers with proper casting.
static inline XBERGXbergRendererVTable* xberg_renderer_vtable_new(void) {
	// Note: All function pointers are assigned with generic casts to suppress warnings.
	// The actual function addresses are ABI-compatible despite signature differences.
	XBERGXbergRendererVTable* vtable = (XBERGXbergRendererVTable*)malloc(sizeof(XBERGXbergRendererVTable));
	if (!vtable) return NULL;
	memset(vtable, 0, sizeof(XBERGXbergRendererVTable));	vtable->render_result = (void(*)(void))goRendererRenderResult;	vtable->free_string = (void(*)(void))goRendererFreeString;
	vtable->free_user_data = (void(*)(void))goRendererFreeUserData;
	vtable->name_fn = (void(*)(void))goRendererName;
	vtable->version_fn = (void(*)(void))goRendererVersion;
	vtable->initialize_fn = (void(*)(void))goRendererInitialize;
	vtable->shutdown_fn = (void(*)(void))goRendererShutdown;

	return vtable;
}
#pragma GCC diagnostic pop
// Note: suppress incompatible-pointer-types warnings because cgo exports may have
// signatures that C strictly typechecks. The function pointers are ABI-compatible.
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wincompatible-function-pointer-types"
#else
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#endif
// C inline function to construct the XBERGXbergRerankerBackendVTable vtable.
// This allows direct assignment of function pointers with proper casting.
static inline XBERGXbergRerankerBackendVTable* xberg_reranker_backend_vtable_new(void) {
	// Note: All function pointers are assigned with generic casts to suppress warnings.
	// The actual function addresses are ABI-compatible despite signature differences.
	XBERGXbergRerankerBackendVTable* vtable = (XBERGXbergRerankerBackendVTable*)malloc(sizeof(XBERGXbergRerankerBackendVTable));
	if (!vtable) return NULL;
	memset(vtable, 0, sizeof(XBERGXbergRerankerBackendVTable));	vtable->rerank = (void(*)(void))goRerankerBackendRerank;	vtable->free_string = (void(*)(void))goRerankerBackendFreeString;
	vtable->free_user_data = (void(*)(void))goRerankerBackendFreeUserData;
	vtable->name_fn = (void(*)(void))goRerankerBackendName;
	vtable->version_fn = (void(*)(void))goRerankerBackendVersion;
	vtable->initialize_fn = (void(*)(void))goRerankerBackendInitialize;
	vtable->shutdown_fn = (void(*)(void))goRerankerBackendShutdown;

	return vtable;
}
#pragma GCC diagnostic pop
// Note: suppress incompatible-pointer-types warnings because cgo exports may have
// signatures that C strictly typechecks. The function pointers are ABI-compatible.
#pragma GCC diagnostic push
#if defined(__clang__)
#pragma GCC diagnostic ignored "-Wincompatible-function-pointer-types"
#else
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#endif
// C inline function to construct the XBERGXbergTokenizerBackendVTable vtable.
// This allows direct assignment of function pointers with proper casting.
static inline XBERGXbergTokenizerBackendVTable* xberg_tokenizer_backend_vtable_new(void) {
	// Note: All function pointers are assigned with generic casts to suppress warnings.
	// The actual function addresses are ABI-compatible despite signature differences.
	XBERGXbergTokenizerBackendVTable* vtable = (XBERGXbergTokenizerBackendVTable*)malloc(sizeof(XBERGXbergTokenizerBackendVTable));
	if (!vtable) return NULL;
	memset(vtable, 0, sizeof(XBERGXbergTokenizerBackendVTable));	vtable->count_tokens = (void(*)(void))goTokenizerBackendCountTokens;	vtable->free_string = (void(*)(void))goTokenizerBackendFreeString;
	vtable->free_user_data = (void(*)(void))goTokenizerBackendFreeUserData;
	vtable->name_fn = (void(*)(void))goTokenizerBackendName;
	vtable->version_fn = (void(*)(void))goTokenizerBackendVersion;
	vtable->initialize_fn = (void(*)(void))goTokenizerBackendInitialize;
	vtable->shutdown_fn = (void(*)(void))goTokenizerBackendShutdown;

	return vtable;
}
#pragma GCC diagnostic pop
*/
import "C"

import (
	"encoding/json"
	"fmt"
	"os"
	"runtime/cgo"
	"sync"
	"unsafe"
)

// handleRegistry tracks cgo.Handles by name to ensure proper cleanup on unregister.
// Without this, unregistered plugins can cause use-after-free crashes when Rust
// still holds vtable pointers and tries to invoke callbacks on deleted handles.
type handleRegistry struct {
	mu      sync.Mutex
	handles map[string]cgo.Handle
}

var (
	ocr_backendRegistry        = &handleRegistry{handles: make(map[string]cgo.Handle)}
	post_processorRegistry     = &handleRegistry{handles: make(map[string]cgo.Handle)}
	validatorRegistry          = &handleRegistry{handles: make(map[string]cgo.Handle)}
	document_extractorRegistry = &handleRegistry{handles: make(map[string]cgo.Handle)}
	embedding_backendRegistry  = &handleRegistry{handles: make(map[string]cgo.Handle)}
	rendererRegistry           = &handleRegistry{handles: make(map[string]cgo.Handle)}
	reranker_backendRegistry   = &handleRegistry{handles: make(map[string]cgo.Handle)}
	tokenizer_backendRegistry  = &handleRegistry{handles: make(map[string]cgo.Handle)}
)

// store adds a handle to the registry, keyed by name.
func (reg *handleRegistry) store(name string, handle cgo.Handle) {
	reg.mu.Lock()
	defer reg.mu.Unlock()
	if old, ok := reg.handles[name]; ok {
		old.Delete()
	}
	reg.handles[name] = handle
}

// delete removes and deletes a handle from the registry by name.
func (reg *handleRegistry) delete(name string) {
	reg.mu.Lock()
	defer reg.mu.Unlock()
	if handle, ok := reg.handles[name]; ok {
		delete(reg.handles, name)
		handle.Delete()
	}
}

// clear removes and deletes all handles from the registry.
func (reg *handleRegistry) clear() {
	reg.mu.Lock()
	defer reg.mu.Unlock()
	for _, handle := range reg.handles {
		handle.Delete()
	}
	reg.handles = make(map[string]cgo.Handle)
}

// OcrBackend defines the Go interface for the OcrBackend trait.
type OcrBackend interface {
	// Name returns the plugin name.
	Name() string
	// Version returns the plugin version.
	Version() string
	// Initialize is called when the plugin is loaded.
	Initialize() error
	// Shutdown is called when the plugin is unloaded.
	Shutdown() error
	// process_image
	ProcessImage(image_bytes []byte, config OcrConfig) (ExtractedDocument, error)

	// process_image_file
	ProcessImageFile(path string, config OcrConfig) (ExtractedDocument, error)

	// supports_language
	SupportsLanguage(lang string) bool

	// backend_type
	BackendType() OcrBackendType

	// supported_languages
	SupportedLanguages() []string

	// supports_table_detection
	SupportsTableDetection() bool

	// supports_document_processing
	SupportsDocumentProcessing() bool

	// emits_structured_markdown
	EmitsStructuredMarkdown() bool

	// process_document
	ProcessDocument(_path string, _config OcrConfig) (ExtractedDocument, error)
}

// OcrBackendBridge wraps a OcrBackend implementation and exposes it to the C plugin system.
type OcrBackendBridge struct {
	impl OcrBackend
}

// NewOcrBackendBridge creates a new Bridge wrapping the given implementation.
func NewOcrBackendBridge(impl OcrBackend) *OcrBackendBridge {
	return &OcrBackendBridge{impl: impl}
}

func (b *OcrBackendBridge) Name() string {
	return b.impl.Name()
}

func (b *OcrBackendBridge) Version() string {
	return b.impl.Version()
}

func (b *OcrBackendBridge) Initialize() error {
	return b.impl.Initialize()
}

func (b *OcrBackendBridge) Shutdown() error {
	return b.impl.Shutdown()
}

func (b *OcrBackendBridge) ProcessImage(image_bytes []byte, config OcrConfig) (ExtractedDocument, error) {
	return b.impl.ProcessImage(image_bytes, config)
}

func (b *OcrBackendBridge) ProcessImageFile(path string, config OcrConfig) (ExtractedDocument, error) {
	return b.impl.ProcessImageFile(path, config)
}

func (b *OcrBackendBridge) SupportsLanguage(lang string) bool {
	return b.impl.SupportsLanguage(lang)
}

func (b *OcrBackendBridge) BackendType() OcrBackendType {
	return b.impl.BackendType()
}

func (b *OcrBackendBridge) SupportedLanguages() []string {
	return b.impl.SupportedLanguages()
}

func (b *OcrBackendBridge) SupportsTableDetection() bool {
	return b.impl.SupportsTableDetection()
}

func (b *OcrBackendBridge) SupportsDocumentProcessing() bool {
	return b.impl.SupportsDocumentProcessing()
}

func (b *OcrBackendBridge) EmitsStructuredMarkdown() bool {
	return b.impl.EmitsStructuredMarkdown()
}

func (b *OcrBackendBridge) ProcessDocument(_path string, _config OcrConfig) (ExtractedDocument, error) {
	return b.impl.ProcessDocument(_path, _config)
}

//export goOcrBackendProcessImage
func goOcrBackendProcessImage(
	userData unsafe.Pointer,
	image_bytes *C.uint8_t,
	image_bytesLen C.size_t,
	config *C.char,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'ProcessImage' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'ProcessImage' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	var goImage_bytes []byte
	if image_bytes != nil {
		goImage_bytes = unsafe.Slice((*byte)(unsafe.Pointer(image_bytes)), int(image_bytesLen))
	}
	var goConfig OcrConfig
	if config != nil {
		json.Unmarshal([]byte(C.GoString(config)), &goConfig)

	}

	// Call the method
	callbackResult, err := impl.ProcessImage(goImage_bytes, goConfig)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goOcrBackendProcessImageFile
func goOcrBackendProcessImageFile(
	userData unsafe.Pointer,
	path *C.char,
	config *C.char,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'ProcessImageFile' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'ProcessImageFile' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	goPath := C.GoString(path)

	var goConfig OcrConfig
	if config != nil {
		json.Unmarshal([]byte(C.GoString(config)), &goConfig)

	}

	// Call the method
	callbackResult, err := impl.ProcessImageFile(goPath, goConfig)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goOcrBackendSupportsLanguage
func goOcrBackendSupportsLanguage(
	userData unsafe.Pointer,
	lang *C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'SupportsLanguage' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'SupportsLanguage' called with an invalid handle; returning default")
		return 0
	}

	goLang := C.GoString(lang)

	// Call the method
	callbackResult := impl.SupportsLanguage(goLang)

	if callbackResult {
		return 1
	}
	return 0
}

//export goOcrBackendBackendType
func goOcrBackendBackendType(
	userData unsafe.Pointer,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'BackendType' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'BackendType' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.BackendType()

	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goOcrBackendSupportedLanguages
func goOcrBackendSupportedLanguages(
	userData unsafe.Pointer,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'SupportedLanguages' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'SupportedLanguages' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.SupportedLanguages()

	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goOcrBackendSupportsTableDetection
func goOcrBackendSupportsTableDetection(
	userData unsafe.Pointer,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'SupportsTableDetection' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'SupportsTableDetection' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.SupportsTableDetection()

	if callbackResult {
		return 1
	}
	return 0
}

//export goOcrBackendSupportsDocumentProcessing
func goOcrBackendSupportsDocumentProcessing(
	userData unsafe.Pointer,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'SupportsDocumentProcessing' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'SupportsDocumentProcessing' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.SupportsDocumentProcessing()

	if callbackResult {
		return 1
	}
	return 0
}

//export goOcrBackendEmitsStructuredMarkdown
func goOcrBackendEmitsStructuredMarkdown(
	userData unsafe.Pointer,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'EmitsStructuredMarkdown' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'EmitsStructuredMarkdown' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.EmitsStructuredMarkdown()

	if callbackResult {
		return 1
	}
	return 0
}

//export goOcrBackendProcessDocument
func goOcrBackendProcessDocument(
	userData unsafe.Pointer,
	_path *C.char,
	_config *C.char,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'ProcessDocument' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'ProcessDocument' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	go_path := C.GoString(_path)

	var go_config OcrConfig
	if _config != nil {
		json.Unmarshal([]byte(C.GoString(_config)), &go_config)

	}

	// Call the method
	callbackResult, err := impl.ProcessDocument(go_path, go_config)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goOcrBackendName
func goOcrBackendName(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'Name' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'Name' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goOcrBackendVersion
func goOcrBackendVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'Version' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'Version' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goOcrBackendInitialize
func goOcrBackendInitialize(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'Initialize' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'Initialize' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goOcrBackendShutdown
func goOcrBackendShutdown(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'Shutdown' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(OcrBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[OcrBackendBridge] host 'Shutdown' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goOcrBackendFreeUserData
func goOcrBackendFreeUserData(userData unsafe.Pointer) {

	// No-op to avoid cleanup-queue panics. Handles cleaned in Unregister().
}

//export goOcrBackendFreeString
func goOcrBackendFreeString(ptr *C.char) {
	if ptr != nil {
		C.free(unsafe.Pointer(ptr))
	}
}

// RegisterOcrBackend registers a OcrBackend implementation with the C runtime.
func RegisterOcrBackend(impl OcrBackend) error {
	bridge := NewOcrBackendBridge(impl)
	handle := cgo.NewHandle(bridge)
	// Build the C vtable by calling the C helper function.
	// This ensures function pointers are correctly populated in C, fixing ARM64 macOS issues.
	vtable := C.xberg_ocr_backend_vtable_new()
	if vtable == nil {
		return fmt.Errorf("failed to allocate %s vtable", impl.Name())
	}
	defer C.free(unsafe.Pointer(vtable))
	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.xberg_register_ocr_backend(
		cName,
		vtable,
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register OcrBackend"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	// Store handle by name for later cleanup on unregister
	ocr_backendRegistry.store(impl.Name(), handle)
	return nil
}

// UnregisterOcrBackend unregisters a OcrBackend implementation.
func UnregisterOcrBackend(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	var cErr *C.char
	rc := C.xberg_unregister_ocr_backend(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister OcrBackend"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete the handle now that Rust has unregistered the plugin
	ocr_backendRegistry.delete(name)
	return nil
}

// ClearOcrBackends removes all registered OcrBackend implementations.
func ClearOcrBackends() error {
	var cErr *C.char
	rc := C.xberg_clear_ocr_backend(&cErr)

	if rc != 0 {
		msg := "failed to clear OcrBackend plugins"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete all handles now that Rust has cleared all plugins
	ocr_backendRegistry.clear()
	return nil
}

// PostProcessor defines the Go interface for the PostProcessor trait.
type PostProcessor interface {
	// Name returns the plugin name.
	Name() string
	// Version returns the plugin version.
	Version() string
	// Initialize is called when the plugin is loaded.
	Initialize() error
	// Shutdown is called when the plugin is unloaded.
	Shutdown() error
	// process
	Process(result ExtractedDocument, config ExtractionConfig) error

	// processing_stage
	ProcessingStage() ProcessingStage

	// should_process
	ShouldProcess(_result ExtractedDocument, _config ExtractionConfig) bool

	// estimated_duration_ms
	EstimatedDurationMs(_result ExtractedDocument) uint64

	// priority
	Priority() int32
}

// PostProcessorBridge wraps a PostProcessor implementation and exposes it to the C plugin system.
type PostProcessorBridge struct {
	impl PostProcessor
}

// NewPostProcessorBridge creates a new Bridge wrapping the given implementation.
func NewPostProcessorBridge(impl PostProcessor) *PostProcessorBridge {
	return &PostProcessorBridge{impl: impl}
}

func (b *PostProcessorBridge) Name() string {
	return b.impl.Name()
}

func (b *PostProcessorBridge) Version() string {
	return b.impl.Version()
}

func (b *PostProcessorBridge) Initialize() error {
	return b.impl.Initialize()
}

func (b *PostProcessorBridge) Shutdown() error {
	return b.impl.Shutdown()
}

func (b *PostProcessorBridge) Process(result ExtractedDocument, config ExtractionConfig) error {
	return b.impl.Process(result, config)
}

func (b *PostProcessorBridge) ProcessingStage() ProcessingStage {
	return b.impl.ProcessingStage()
}

func (b *PostProcessorBridge) ShouldProcess(_result ExtractedDocument, _config ExtractionConfig) bool {
	return b.impl.ShouldProcess(_result, _config)
}

func (b *PostProcessorBridge) EstimatedDurationMs(_result ExtractedDocument) uint64 {
	return b.impl.EstimatedDurationMs(_result)
}

func (b *PostProcessorBridge) Priority() int32 {
	return b.impl.Priority()
}

//export goPostProcessorProcess
func goPostProcessorProcess(
	userData unsafe.Pointer,
	result *C.char,
	config *C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Process' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Process' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	var goResult ExtractedDocument
	if result != nil {
		json.Unmarshal([]byte(C.GoString(result)), &goResult)

	}

	var goConfig ExtractionConfig
	if config != nil {
		json.Unmarshal([]byte(C.GoString(config)), &goConfig)

	}

	// Call the method
	err := impl.Process(goResult, goConfig)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0 // success
}

//export goPostProcessorProcessingStage
func goPostProcessorProcessingStage(
	userData unsafe.Pointer,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'ProcessingStage' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'ProcessingStage' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.ProcessingStage()

	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goPostProcessorShouldProcess
func goPostProcessorShouldProcess(
	userData unsafe.Pointer,
	_result *C.char,
	_config *C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'ShouldProcess' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'ShouldProcess' called with an invalid handle; returning default")
		return 0
	}

	var go_result ExtractedDocument
	if _result != nil {
		json.Unmarshal([]byte(C.GoString(_result)), &go_result)

	}

	var go_config ExtractionConfig
	if _config != nil {
		json.Unmarshal([]byte(C.GoString(_config)), &go_config)

	}

	// Call the method
	callbackResult := impl.ShouldProcess(go_result, go_config)

	if callbackResult {
		return 1
	}
	return 0
}

//export goPostProcessorEstimatedDurationMs
func goPostProcessorEstimatedDurationMs(
	userData unsafe.Pointer,
	_result *C.char,
	outError **C.char,
) (ret C.uint64_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'EstimatedDurationMs' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'EstimatedDurationMs' called with an invalid handle; returning default")
		return 0
	}

	var go_result ExtractedDocument
	if _result != nil {
		json.Unmarshal([]byte(C.GoString(_result)), &go_result)

	}

	// Call the method
	callbackResult := impl.EstimatedDurationMs(go_result)

	return C.uint64_t(callbackResult)
}

//export goPostProcessorPriority
func goPostProcessorPriority(
	userData unsafe.Pointer,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Priority' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Priority' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.Priority()

	return C.int32_t(callbackResult)
}

//export goPostProcessorName
func goPostProcessorName(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Name' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Name' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goPostProcessorVersion
func goPostProcessorVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Version' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Version' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goPostProcessorInitialize
func goPostProcessorInitialize(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Initialize' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Initialize' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goPostProcessorShutdown
func goPostProcessorShutdown(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Shutdown' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(PostProcessor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[PostProcessorBridge] host 'Shutdown' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goPostProcessorFreeUserData
func goPostProcessorFreeUserData(userData unsafe.Pointer) {

	// No-op to avoid cleanup-queue panics. Handles cleaned in Unregister().
}

//export goPostProcessorFreeString
func goPostProcessorFreeString(ptr *C.char) {
	if ptr != nil {
		C.free(unsafe.Pointer(ptr))
	}
}

// RegisterPostProcessor registers a PostProcessor implementation with the C runtime.
func RegisterPostProcessor(impl PostProcessor) error {
	bridge := NewPostProcessorBridge(impl)
	handle := cgo.NewHandle(bridge)
	// Build the C vtable by calling the C helper function.
	// This ensures function pointers are correctly populated in C, fixing ARM64 macOS issues.
	vtable := C.xberg_post_processor_vtable_new()
	if vtable == nil {
		return fmt.Errorf("failed to allocate %s vtable", impl.Name())
	}
	defer C.free(unsafe.Pointer(vtable))
	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.xberg_register_post_processor(
		cName,
		vtable,
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register PostProcessor"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	// Store handle by name for later cleanup on unregister
	post_processorRegistry.store(impl.Name(), handle)
	return nil
}

// UnregisterPostProcessor unregisters a PostProcessor implementation.
func UnregisterPostProcessor(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	var cErr *C.char
	rc := C.xberg_unregister_post_processor(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister PostProcessor"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete the handle now that Rust has unregistered the plugin
	post_processorRegistry.delete(name)
	return nil
}

// ClearPostProcessors removes all registered PostProcessor implementations.
func ClearPostProcessors() error {
	var cErr *C.char
	rc := C.xberg_clear_post_processor(&cErr)

	if rc != 0 {
		msg := "failed to clear PostProcessor plugins"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete all handles now that Rust has cleared all plugins
	post_processorRegistry.clear()
	return nil
}

// Validator defines the Go interface for the Validator trait.
type Validator interface {
	// Name returns the plugin name.
	Name() string
	// Version returns the plugin version.
	Version() string
	// Initialize is called when the plugin is loaded.
	Initialize() error
	// Shutdown is called when the plugin is unloaded.
	Shutdown() error
	// validate
	Validate(result ExtractedDocument, config ExtractionConfig) error

	// should_validate
	ShouldValidate(_result ExtractedDocument, _config ExtractionConfig) bool

	// priority
	Priority() int32
}

// ValidatorBridge wraps a Validator implementation and exposes it to the C plugin system.
type ValidatorBridge struct {
	impl Validator
}

// NewValidatorBridge creates a new Bridge wrapping the given implementation.
func NewValidatorBridge(impl Validator) *ValidatorBridge {
	return &ValidatorBridge{impl: impl}
}

func (b *ValidatorBridge) Name() string {
	return b.impl.Name()
}

func (b *ValidatorBridge) Version() string {
	return b.impl.Version()
}

func (b *ValidatorBridge) Initialize() error {
	return b.impl.Initialize()
}

func (b *ValidatorBridge) Shutdown() error {
	return b.impl.Shutdown()
}

func (b *ValidatorBridge) Validate(result ExtractedDocument, config ExtractionConfig) error {
	return b.impl.Validate(result, config)
}

func (b *ValidatorBridge) ShouldValidate(_result ExtractedDocument, _config ExtractionConfig) bool {
	return b.impl.ShouldValidate(_result, _config)
}

func (b *ValidatorBridge) Priority() int32 {
	return b.impl.Priority()
}

//export goValidatorValidate
func goValidatorValidate(
	userData unsafe.Pointer,
	result *C.char,
	config *C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Validate' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Validator)

	if !ok {
		fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Validate' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	var goResult ExtractedDocument
	if result != nil {
		json.Unmarshal([]byte(C.GoString(result)), &goResult)

	}

	var goConfig ExtractionConfig
	if config != nil {
		json.Unmarshal([]byte(C.GoString(config)), &goConfig)

	}

	// Call the method
	err := impl.Validate(goResult, goConfig)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0 // success
}

//export goValidatorShouldValidate
func goValidatorShouldValidate(
	userData unsafe.Pointer,
	_result *C.char,
	_config *C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'ShouldValidate' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Validator)

	if !ok {
		fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'ShouldValidate' called with an invalid handle; returning default")
		return 0
	}

	var go_result ExtractedDocument
	if _result != nil {
		json.Unmarshal([]byte(C.GoString(_result)), &go_result)

	}

	var go_config ExtractionConfig
	if _config != nil {
		json.Unmarshal([]byte(C.GoString(_config)), &go_config)

	}

	// Call the method
	callbackResult := impl.ShouldValidate(go_result, go_config)

	if callbackResult {
		return 1
	}
	return 0
}

//export goValidatorPriority
func goValidatorPriority(
	userData unsafe.Pointer,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Priority' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Validator)

	if !ok {
		fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Priority' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.Priority()

	return C.int32_t(callbackResult)
}

//export goValidatorName
func goValidatorName(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Name' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Validator)

	if !ok {
		fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Name' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goValidatorVersion
func goValidatorVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Version' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Validator)

	if !ok {
		fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Version' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goValidatorInitialize
func goValidatorInitialize(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Initialize' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Validator)

	if !ok {
		fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Initialize' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goValidatorShutdown
func goValidatorShutdown(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Shutdown' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Validator)

	if !ok {
		fmt.Fprintln(os.Stderr, "[ValidatorBridge] host 'Shutdown' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goValidatorFreeUserData
func goValidatorFreeUserData(userData unsafe.Pointer) {

	// No-op to avoid cleanup-queue panics. Handles cleaned in Unregister().
}

//export goValidatorFreeString
func goValidatorFreeString(ptr *C.char) {
	if ptr != nil {
		C.free(unsafe.Pointer(ptr))
	}
}

// RegisterValidator registers a Validator implementation with the C runtime.
func RegisterValidator(impl Validator) error {
	bridge := NewValidatorBridge(impl)
	handle := cgo.NewHandle(bridge)
	// Build the C vtable by calling the C helper function.
	// This ensures function pointers are correctly populated in C, fixing ARM64 macOS issues.
	vtable := C.xberg_validator_vtable_new()
	if vtable == nil {
		return fmt.Errorf("failed to allocate %s vtable", impl.Name())
	}
	defer C.free(unsafe.Pointer(vtable))
	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.xberg_register_validator(
		cName,
		vtable,
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register Validator"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	// Store handle by name for later cleanup on unregister
	validatorRegistry.store(impl.Name(), handle)
	return nil
}

// UnregisterValidator unregisters a Validator implementation.
func UnregisterValidator(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	var cErr *C.char
	rc := C.xberg_unregister_validator(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister Validator"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete the handle now that Rust has unregistered the plugin
	validatorRegistry.delete(name)
	return nil
}

// ClearValidators removes all registered Validator implementations.
func ClearValidators() error {
	var cErr *C.char
	rc := C.xberg_clear_validator(&cErr)

	if rc != 0 {
		msg := "failed to clear Validator plugins"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete all handles now that Rust has cleared all plugins
	validatorRegistry.clear()
	return nil
}

// DocumentExtractor defines the Go interface for the DocumentExtractor trait.
type DocumentExtractor interface {
	// Name returns the plugin name.
	Name() string
	// Version returns the plugin version.
	Version() string
	// Initialize is called when the plugin is loaded.
	Initialize() error
	// Shutdown is called when the plugin is unloaded.
	Shutdown() error
	// extract
	Extract(input ExtractInput, config ExtractionConfig) (ExtractedDocument, error)

	// supported_mime_types
	SupportedMimeTypes() []string

	// priority
	Priority() int32

	// can_handle
	CanHandle(_path string, _mime_type string) bool
}

// DocumentExtractorBridge wraps a DocumentExtractor implementation and exposes it to the C plugin system.
type DocumentExtractorBridge struct {
	impl DocumentExtractor
}

// NewDocumentExtractorBridge creates a new Bridge wrapping the given implementation.
func NewDocumentExtractorBridge(impl DocumentExtractor) *DocumentExtractorBridge {
	return &DocumentExtractorBridge{impl: impl}
}

func (b *DocumentExtractorBridge) Name() string {
	return b.impl.Name()
}

func (b *DocumentExtractorBridge) Version() string {
	return b.impl.Version()
}

func (b *DocumentExtractorBridge) Initialize() error {
	return b.impl.Initialize()
}

func (b *DocumentExtractorBridge) Shutdown() error {
	return b.impl.Shutdown()
}

func (b *DocumentExtractorBridge) Extract(input ExtractInput, config ExtractionConfig) (ExtractedDocument, error) {
	return b.impl.Extract(input, config)
}

func (b *DocumentExtractorBridge) SupportedMimeTypes() []string {
	return b.impl.SupportedMimeTypes()
}

func (b *DocumentExtractorBridge) Priority() int32 {
	return b.impl.Priority()
}

func (b *DocumentExtractorBridge) CanHandle(_path string, _mime_type string) bool {
	return b.impl.CanHandle(_path, _mime_type)
}

//export goDocumentExtractorExtract
func goDocumentExtractorExtract(
	userData unsafe.Pointer,
	input *C.char,
	config *C.char,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Extract' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(DocumentExtractor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Extract' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	var goInput ExtractInput
	if input != nil {
		json.Unmarshal([]byte(C.GoString(input)), &goInput)

	}

	var goConfig ExtractionConfig
	if config != nil {
		json.Unmarshal([]byte(C.GoString(config)), &goConfig)

	}

	// Call the method
	callbackResult, err := impl.Extract(goInput, goConfig)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goDocumentExtractorSupportedMimeTypes
func goDocumentExtractorSupportedMimeTypes(
	userData unsafe.Pointer,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'SupportedMimeTypes' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(DocumentExtractor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'SupportedMimeTypes' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.SupportedMimeTypes()

	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goDocumentExtractorPriority
func goDocumentExtractorPriority(
	userData unsafe.Pointer,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Priority' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(DocumentExtractor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Priority' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.Priority()

	return C.int32_t(callbackResult)
}

//export goDocumentExtractorCanHandle
func goDocumentExtractorCanHandle(
	userData unsafe.Pointer,
	_path *C.char,
	_mime_type *C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'CanHandle' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(DocumentExtractor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'CanHandle' called with an invalid handle; returning default")
		return 0
	}

	go_path := C.GoString(_path)

	go_mime_type := C.GoString(_mime_type)

	// Call the method
	callbackResult := impl.CanHandle(go_path, go_mime_type)

	if callbackResult {
		return 1
	}
	return 0
}

//export goDocumentExtractorName
func goDocumentExtractorName(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Name' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(DocumentExtractor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Name' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goDocumentExtractorVersion
func goDocumentExtractorVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Version' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(DocumentExtractor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Version' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goDocumentExtractorInitialize
func goDocumentExtractorInitialize(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Initialize' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(DocumentExtractor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Initialize' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goDocumentExtractorShutdown
func goDocumentExtractorShutdown(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Shutdown' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(DocumentExtractor)

	if !ok {
		fmt.Fprintln(os.Stderr, "[DocumentExtractorBridge] host 'Shutdown' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goDocumentExtractorFreeUserData
func goDocumentExtractorFreeUserData(userData unsafe.Pointer) {

	// No-op to avoid cleanup-queue panics. Handles cleaned in Unregister().
}

//export goDocumentExtractorFreeString
func goDocumentExtractorFreeString(ptr *C.char) {
	if ptr != nil {
		C.free(unsafe.Pointer(ptr))
	}
}

// RegisterDocumentExtractor registers a DocumentExtractor implementation with the C runtime.
func RegisterDocumentExtractor(impl DocumentExtractor) error {
	bridge := NewDocumentExtractorBridge(impl)
	handle := cgo.NewHandle(bridge)
	// Build the C vtable by calling the C helper function.
	// This ensures function pointers are correctly populated in C, fixing ARM64 macOS issues.
	vtable := C.xberg_document_extractor_vtable_new()
	if vtable == nil {
		return fmt.Errorf("failed to allocate %s vtable", impl.Name())
	}
	defer C.free(unsafe.Pointer(vtable))
	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.xberg_register_document_extractor(
		cName,
		vtable,
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register DocumentExtractor"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	// Store handle by name for later cleanup on unregister
	document_extractorRegistry.store(impl.Name(), handle)
	return nil
}

// UnregisterDocumentExtractor unregisters a DocumentExtractor implementation.
func UnregisterDocumentExtractor(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	var cErr *C.char
	rc := C.xberg_unregister_document_extractor(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister DocumentExtractor"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete the handle now that Rust has unregistered the plugin
	document_extractorRegistry.delete(name)
	return nil
}

// ClearDocumentExtractors removes all registered DocumentExtractor implementations.
func ClearDocumentExtractors() error {
	var cErr *C.char
	rc := C.xberg_clear_document_extractor(&cErr)

	if rc != 0 {
		msg := "failed to clear DocumentExtractor plugins"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete all handles now that Rust has cleared all plugins
	document_extractorRegistry.clear()
	return nil
}

// EmbeddingBackend defines the Go interface for the EmbeddingBackend trait.
type EmbeddingBackend interface {
	// Name returns the plugin name.
	Name() string
	// Version returns the plugin version.
	Version() string
	// Initialize is called when the plugin is loaded.
	Initialize() error
	// Shutdown is called when the plugin is unloaded.
	Shutdown() error
	// dimensions
	Dimensions() uint

	// embed
	Embed(texts []string) ([][]float32, error)
}

// EmbeddingBackendBridge wraps a EmbeddingBackend implementation and exposes it to the C plugin system.
type EmbeddingBackendBridge struct {
	impl EmbeddingBackend
}

// NewEmbeddingBackendBridge creates a new Bridge wrapping the given implementation.
func NewEmbeddingBackendBridge(impl EmbeddingBackend) *EmbeddingBackendBridge {
	return &EmbeddingBackendBridge{impl: impl}
}

func (b *EmbeddingBackendBridge) Name() string {
	return b.impl.Name()
}

func (b *EmbeddingBackendBridge) Version() string {
	return b.impl.Version()
}

func (b *EmbeddingBackendBridge) Initialize() error {
	return b.impl.Initialize()
}

func (b *EmbeddingBackendBridge) Shutdown() error {
	return b.impl.Shutdown()
}

func (b *EmbeddingBackendBridge) Dimensions() uint {
	return b.impl.Dimensions()
}

func (b *EmbeddingBackendBridge) Embed(texts []string) ([][]float32, error) {
	return b.impl.Embed(texts)
}

//export goEmbeddingBackendDimensions
func goEmbeddingBackendDimensions(
	userData unsafe.Pointer,
	outError **C.char,
) (ret C.uintptr_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Dimensions' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(EmbeddingBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Dimensions' called with an invalid handle; returning default")
		return 0
	}

	// Call the method
	callbackResult := impl.Dimensions()

	return C.uintptr_t(callbackResult)
}

//export goEmbeddingBackendEmbed
func goEmbeddingBackendEmbed(
	userData unsafe.Pointer,
	texts *C.char,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Embed' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(EmbeddingBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Embed' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	var goTexts []string
	if texts != nil {
		json.Unmarshal([]byte(C.GoString(texts)), &goTexts)

	}

	// Call the method
	callbackResult, err := impl.Embed(goTexts)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goEmbeddingBackendName
func goEmbeddingBackendName(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Name' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(EmbeddingBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Name' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goEmbeddingBackendVersion
func goEmbeddingBackendVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Version' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(EmbeddingBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Version' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goEmbeddingBackendInitialize
func goEmbeddingBackendInitialize(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Initialize' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(EmbeddingBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Initialize' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goEmbeddingBackendShutdown
func goEmbeddingBackendShutdown(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Shutdown' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(EmbeddingBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[EmbeddingBackendBridge] host 'Shutdown' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goEmbeddingBackendFreeUserData
func goEmbeddingBackendFreeUserData(userData unsafe.Pointer) {

	// No-op to avoid cleanup-queue panics. Handles cleaned in Unregister().
}

//export goEmbeddingBackendFreeString
func goEmbeddingBackendFreeString(ptr *C.char) {
	if ptr != nil {
		C.free(unsafe.Pointer(ptr))
	}
}

// RegisterEmbeddingBackend registers a EmbeddingBackend implementation with the C runtime.
func RegisterEmbeddingBackend(impl EmbeddingBackend) error {
	bridge := NewEmbeddingBackendBridge(impl)
	handle := cgo.NewHandle(bridge)
	// Build the C vtable by calling the C helper function.
	// This ensures function pointers are correctly populated in C, fixing ARM64 macOS issues.
	vtable := C.xberg_embedding_backend_vtable_new()
	if vtable == nil {
		return fmt.Errorf("failed to allocate %s vtable", impl.Name())
	}
	defer C.free(unsafe.Pointer(vtable))
	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.xberg_register_embedding_backend(
		cName,
		vtable,
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register EmbeddingBackend"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	// Store handle by name for later cleanup on unregister
	embedding_backendRegistry.store(impl.Name(), handle)
	return nil
}

// UnregisterEmbeddingBackend unregisters a EmbeddingBackend implementation.
func UnregisterEmbeddingBackend(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	var cErr *C.char
	rc := C.xberg_unregister_embedding_backend(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister EmbeddingBackend"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete the handle now that Rust has unregistered the plugin
	embedding_backendRegistry.delete(name)
	return nil
}

// ClearEmbeddingBackends removes all registered EmbeddingBackend implementations.
func ClearEmbeddingBackends() error {
	var cErr *C.char
	rc := C.xberg_clear_embedding_backend(&cErr)

	if rc != 0 {
		msg := "failed to clear EmbeddingBackend plugins"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete all handles now that Rust has cleared all plugins
	embedding_backendRegistry.clear()
	return nil
}

// Renderer defines the Go interface for the Renderer trait.
type Renderer interface {
	// Name returns the plugin name.
	Name() string
	// Version returns the plugin version.
	Version() string
	// Initialize is called when the plugin is loaded.
	Initialize() error
	// Shutdown is called when the plugin is unloaded.
	Shutdown() error
	// render_result
	RenderResult(result ExtractedDocument) (string, error)
}

// RendererBridge wraps a Renderer implementation and exposes it to the C plugin system.
type RendererBridge struct {
	impl Renderer
}

// NewRendererBridge creates a new Bridge wrapping the given implementation.
func NewRendererBridge(impl Renderer) *RendererBridge {
	return &RendererBridge{impl: impl}
}

func (b *RendererBridge) Name() string {
	return b.impl.Name()
}

func (b *RendererBridge) Version() string {
	return b.impl.Version()
}

func (b *RendererBridge) Initialize() error {
	return b.impl.Initialize()
}

func (b *RendererBridge) Shutdown() error {
	return b.impl.Shutdown()
}

func (b *RendererBridge) RenderResult(result ExtractedDocument) (string, error) {
	return b.impl.RenderResult(result)
}

//export goRendererRenderResult
func goRendererRenderResult(
	userData unsafe.Pointer,
	result *C.char,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RendererBridge] host 'RenderResult' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Renderer)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RendererBridge] host 'RenderResult' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	var goResult ExtractedDocument
	if result != nil {
		json.Unmarshal([]byte(C.GoString(result)), &goResult)

	}

	// Call the method
	callbackResult, err := impl.RenderResult(goResult)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	cResult := C.CString(callbackResult)
	*outResult = cResult
	return 0 // success
}

//export goRendererName
func goRendererName(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RendererBridge] host 'Name' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Renderer)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RendererBridge] host 'Name' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goRendererVersion
func goRendererVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RendererBridge] host 'Version' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Renderer)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RendererBridge] host 'Version' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goRendererInitialize
func goRendererInitialize(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RendererBridge] host 'Initialize' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Renderer)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RendererBridge] host 'Initialize' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goRendererShutdown
func goRendererShutdown(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RendererBridge] host 'Shutdown' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(Renderer)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RendererBridge] host 'Shutdown' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goRendererFreeUserData
func goRendererFreeUserData(userData unsafe.Pointer) {

	// No-op to avoid cleanup-queue panics. Handles cleaned in Unregister().
}

//export goRendererFreeString
func goRendererFreeString(ptr *C.char) {
	if ptr != nil {
		C.free(unsafe.Pointer(ptr))
	}
}

// RegisterRenderer registers a Renderer implementation with the C runtime.
func RegisterRenderer(impl Renderer) error {
	bridge := NewRendererBridge(impl)
	handle := cgo.NewHandle(bridge)
	// Build the C vtable by calling the C helper function.
	// This ensures function pointers are correctly populated in C, fixing ARM64 macOS issues.
	vtable := C.xberg_renderer_vtable_new()
	if vtable == nil {
		return fmt.Errorf("failed to allocate %s vtable", impl.Name())
	}
	defer C.free(unsafe.Pointer(vtable))
	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.xberg_register_renderer(
		cName,
		vtable,
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register Renderer"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	// Store handle by name for later cleanup on unregister
	rendererRegistry.store(impl.Name(), handle)
	return nil
}

// UnregisterRenderer unregisters a Renderer implementation.
func UnregisterRenderer(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	var cErr *C.char
	rc := C.xberg_unregister_renderer(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister Renderer"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete the handle now that Rust has unregistered the plugin
	rendererRegistry.delete(name)
	return nil
}

// ClearRenderers removes all registered Renderer implementations.
func ClearRenderers() error {
	var cErr *C.char
	rc := C.xberg_clear_renderer(&cErr)

	if rc != 0 {
		msg := "failed to clear Renderer plugins"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete all handles now that Rust has cleared all plugins
	rendererRegistry.clear()
	return nil
}

// RerankerBackend defines the Go interface for the RerankerBackend trait.
type RerankerBackend interface {
	// Name returns the plugin name.
	Name() string
	// Version returns the plugin version.
	Version() string
	// Initialize is called when the plugin is loaded.
	Initialize() error
	// Shutdown is called when the plugin is unloaded.
	Shutdown() error
	// rerank
	Rerank(query string, documents []string) ([]float32, error)
}

// RerankerBackendBridge wraps a RerankerBackend implementation and exposes it to the C plugin system.
type RerankerBackendBridge struct {
	impl RerankerBackend
}

// NewRerankerBackendBridge creates a new Bridge wrapping the given implementation.
func NewRerankerBackendBridge(impl RerankerBackend) *RerankerBackendBridge {
	return &RerankerBackendBridge{impl: impl}
}

func (b *RerankerBackendBridge) Name() string {
	return b.impl.Name()
}

func (b *RerankerBackendBridge) Version() string {
	return b.impl.Version()
}

func (b *RerankerBackendBridge) Initialize() error {
	return b.impl.Initialize()
}

func (b *RerankerBackendBridge) Shutdown() error {
	return b.impl.Shutdown()
}

func (b *RerankerBackendBridge) Rerank(query string, documents []string) ([]float32, error) {
	return b.impl.Rerank(query, documents)
}

//export goRerankerBackendRerank
func goRerankerBackendRerank(
	userData unsafe.Pointer,
	query *C.char,
	documents *C.char,
	outResult **C.char,
	outError **C.char,
) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Rerank' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(RerankerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Rerank' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}

	goQuery := C.GoString(query)

	var goDocuments []string
	if documents != nil {
		json.Unmarshal([]byte(C.GoString(documents)), &goDocuments)

	}

	// Call the method
	callbackResult, err := impl.Rerank(goQuery, goDocuments)

	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	jsonBytes, _ := json.Marshal(callbackResult)
	cResult := C.CString(string(jsonBytes))
	*outResult = cResult
	return 0 // success
}

//export goRerankerBackendName
func goRerankerBackendName(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Name' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(RerankerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Name' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goRerankerBackendVersion
func goRerankerBackendVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Version' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(RerankerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Version' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goRerankerBackendInitialize
func goRerankerBackendInitialize(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Initialize' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(RerankerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Initialize' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goRerankerBackendShutdown
func goRerankerBackendShutdown(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Shutdown' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(RerankerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[RerankerBackendBridge] host 'Shutdown' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goRerankerBackendFreeUserData
func goRerankerBackendFreeUserData(userData unsafe.Pointer) {

	// No-op to avoid cleanup-queue panics. Handles cleaned in Unregister().
}

//export goRerankerBackendFreeString
func goRerankerBackendFreeString(ptr *C.char) {
	if ptr != nil {
		C.free(unsafe.Pointer(ptr))
	}
}

// RegisterRerankerBackend registers a RerankerBackend implementation with the C runtime.
func RegisterRerankerBackend(impl RerankerBackend) error {
	bridge := NewRerankerBackendBridge(impl)
	handle := cgo.NewHandle(bridge)
	// Build the C vtable by calling the C helper function.
	// This ensures function pointers are correctly populated in C, fixing ARM64 macOS issues.
	vtable := C.xberg_reranker_backend_vtable_new()
	if vtable == nil {
		return fmt.Errorf("failed to allocate %s vtable", impl.Name())
	}
	defer C.free(unsafe.Pointer(vtable))
	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.xberg_register_reranker_backend(
		cName,
		vtable,
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register RerankerBackend"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	// Store handle by name for later cleanup on unregister
	reranker_backendRegistry.store(impl.Name(), handle)
	return nil
}

// UnregisterRerankerBackend unregisters a RerankerBackend implementation.
func UnregisterRerankerBackend(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	var cErr *C.char
	rc := C.xberg_unregister_reranker_backend(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister RerankerBackend"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete the handle now that Rust has unregistered the plugin
	reranker_backendRegistry.delete(name)
	return nil
}

// ClearRerankerBackends removes all registered RerankerBackend implementations.
func ClearRerankerBackends() error {
	var cErr *C.char
	rc := C.xberg_clear_reranker_backend(&cErr)

	if rc != 0 {
		msg := "failed to clear RerankerBackend plugins"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete all handles now that Rust has cleared all plugins
	reranker_backendRegistry.clear()
	return nil
}

// TokenizerBackend defines the Go interface for the TokenizerBackend trait.
type TokenizerBackend interface {
	// Name returns the plugin name.
	Name() string
	// Version returns the plugin version.
	Version() string
	// Initialize is called when the plugin is loaded.
	Initialize() error
	// Shutdown is called when the plugin is unloaded.
	Shutdown() error
	// count_tokens
	CountTokens(text string) uint
}

// TokenizerBackendBridge wraps a TokenizerBackend implementation and exposes it to the C plugin system.
type TokenizerBackendBridge struct {
	impl TokenizerBackend
}

// NewTokenizerBackendBridge creates a new Bridge wrapping the given implementation.
func NewTokenizerBackendBridge(impl TokenizerBackend) *TokenizerBackendBridge {
	return &TokenizerBackendBridge{impl: impl}
}

func (b *TokenizerBackendBridge) Name() string {
	return b.impl.Name()
}

func (b *TokenizerBackendBridge) Version() string {
	return b.impl.Version()
}

func (b *TokenizerBackendBridge) Initialize() error {
	return b.impl.Initialize()
}

func (b *TokenizerBackendBridge) Shutdown() error {
	return b.impl.Shutdown()
}

func (b *TokenizerBackendBridge) CountTokens(text string) uint {
	return b.impl.CountTokens(text)
}

//export goTokenizerBackendCountTokens
func goTokenizerBackendCountTokens(
	userData unsafe.Pointer,
	text *C.char,
	outError **C.char,
) (ret C.uintptr_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'CountTokens' panicked; returning default:", r)
			ret = 0
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(TokenizerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'CountTokens' called with an invalid handle; returning default")
		return 0
	}

	goText := C.GoString(text)

	// Call the method
	callbackResult := impl.CountTokens(goText)

	return C.uintptr_t(callbackResult)
}

//export goTokenizerBackendName
func goTokenizerBackendName(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'Name' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(TokenizerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'Name' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	name := impl.Name()
	cName := C.CString(name)
	*outResult = cName
	return 0
}

//export goTokenizerBackendVersion
func goTokenizerBackendVersion(userData unsafe.Pointer, outResult **C.char, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'Version' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(TokenizerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'Version' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	version := impl.Version()
	cVersion := C.CString(version)
	*outResult = cVersion
	return 0
}

//export goTokenizerBackendInitialize
func goTokenizerBackendInitialize(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'Initialize' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(TokenizerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'Initialize' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Initialize()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goTokenizerBackendShutdown
func goTokenizerBackendShutdown(userData unsafe.Pointer, outError **C.char) (ret C.int32_t) {

	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'Shutdown' panicked:", r)
			*outError = C.CString(fmt.Sprint(r))
			ret = 1
		}
	}()

	handle := cgo.Handle(uintptr(unsafe.Pointer(userData)))
	impl, ok := handle.Value().(TokenizerBackend)

	if !ok {
		fmt.Fprintln(os.Stderr, "[TokenizerBackendBridge] host 'Shutdown' called with an invalid handle")
		*outError = C.CString("invalid handle")
		return 1
	}
	err := impl.Shutdown()
	if err != nil {
		cErr := C.CString(err.Error())
		*outError = cErr
		return 1
	}
	return 0
}

//export goTokenizerBackendFreeUserData
func goTokenizerBackendFreeUserData(userData unsafe.Pointer) {

	// No-op to avoid cleanup-queue panics. Handles cleaned in Unregister().
}

//export goTokenizerBackendFreeString
func goTokenizerBackendFreeString(ptr *C.char) {
	if ptr != nil {
		C.free(unsafe.Pointer(ptr))
	}
}

// RegisterTokenizerBackend registers a TokenizerBackend implementation with the C runtime.
func RegisterTokenizerBackend(impl TokenizerBackend) error {
	bridge := NewTokenizerBackendBridge(impl)
	handle := cgo.NewHandle(bridge)
	// Build the C vtable by calling the C helper function.
	// This ensures function pointers are correctly populated in C, fixing ARM64 macOS issues.
	vtable := C.xberg_tokenizer_backend_vtable_new()
	if vtable == nil {
		return fmt.Errorf("failed to allocate %s vtable", impl.Name())
	}
	defer C.free(unsafe.Pointer(vtable))
	// Call C registration
	cName := C.CString(impl.Name())
	defer C.free(unsafe.Pointer(cName))

	var cErr *C.char
	rc := C.xberg_register_tokenizer_backend(
		cName,
		vtable,
		unsafe.Pointer(uintptr(handle)),
		&cErr,
	)

	if rc != 0 {
		msg := "failed to register TokenizerBackend"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		handle.Delete()
		return fmt.Errorf("%s", msg)
	}

	// Store handle by name for later cleanup on unregister
	tokenizer_backendRegistry.store(impl.Name(), handle)
	return nil
}

// UnregisterTokenizerBackend unregisters a TokenizerBackend implementation.
func UnregisterTokenizerBackend(name string) error {
	cName := C.CString(name)
	defer C.free(unsafe.Pointer(cName))
	var cErr *C.char
	rc := C.xberg_unregister_tokenizer_backend(cName, &cErr)

	if rc != 0 {
		msg := "failed to unregister TokenizerBackend"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.xberg_free_string(cErr)
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete the handle now that Rust has unregistered the plugin
	tokenizer_backendRegistry.delete(name)
	return nil
}

// ClearTokenizerBackends removes all registered TokenizerBackend implementations.
func ClearTokenizerBackends() error {
	var cErr *C.char
	rc := C.xberg_clear_tokenizer_backend(&cErr)

	if rc != 0 {
		msg := "failed to clear TokenizerBackend plugins"
		if cErr != nil {
			msg = C.GoString(cErr)
			C.free(unsafe.Pointer(cErr))
		}
		return fmt.Errorf("%s", msg)
	}

	// Delete all handles now that Rust has cleared all plugins
	tokenizer_backendRegistry.clear()
	return nil
}
