// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:446748155774867df28fecd60b1f51d93e20d7476cf9f2aad1cd588a1cf0950e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
