// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:209a244862e56919f9675a72596b4bcd9283654720164e27cad36e49934090ab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
