# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:69c80abf4f614dd71dc3083f935efafc2bedc2382b4fdd350f3f86b38738cad0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: table
defmodule E2e.TableTest do
  use ExUnit.Case, async: false

  describe "table_csv_extraction" do
    @tag :skip
    test "CSV file extraction produces content" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_html_extraction" do
    @tag :skip
    test "HTML table extraction produces markdown format" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_xlsx_markdown" do
    @tag :skip
    test "XLSX extraction produces markdown table format" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
