# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:79767c34939bd7e728fe740f134bd9b63081f8b415726e27ae20fbf8cbeb336f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: tokenizer_backend_management
defmodule E2e.TokenizerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "tokenizer_backends_clear" do
    test "tokenizer_backends_clear" do
      result = Xberg.clear_tokenizer_backends()
    end
  end

  describe "tokenizer_backends_list" do
    test "tokenizer_backends_list" do
      result = Xberg.list_tokenizer_backends()
    end
  end
end
