# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:04dd93e71ba97bcf1658d70be8adfe5e756f1c851ce0a4b6993928f46f46e797
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: tokenizer_backend_management
defmodule E2e.TokenizerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "tokenizer_backends_clear" do
    test "tokenizer_backends_clear" do
      result = Xberg.clear_tokenizer_backends()
    end
  end

  describe "tokenizer_backends_list" do
    test "tokenizer_backends_list" do
      result = Xberg.list_tokenizer_backends()
    end
  end
end
