// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:70f002808d2ae79f0f5135f47c0c282e1162631902e4b57c6829abfd62ec4fb5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;

/** E2e tests for category: validator_management. */
public class ValidatorManagementTest {

    @Test
    void testValidatorsClear() throws Exception {
        // Clear all validators and verify list is empty
        Xberg.clearValidators();


    }


    @Test
    void testValidatorsList() throws Exception {
        // List all registered validators
        var result = Xberg.listValidators();


    }

}
