# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65f62ba6b9d66f5494fa566b7aedd9a323351f32be6da2885f83cf5dc49e1be9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy."""


class KreuzbergError(Exception):
    """Main error type for all Kreuzberg operations."""


class IoError(KreuzbergError):
    """A file system or I/O operation failed. These errors always bubble up unchanged."""


class ParsingError(KreuzbergError):
    """Document parsing failed (e.g. corrupt file, unsupported format feature)."""


class OcrError(KreuzbergError):
    """An OCR engine returned an error or produced unusable output."""


class ValidationError(KreuzbergError):
    """Invalid configuration or input parameters were supplied."""


class CacheError(KreuzbergError):
    """A cache read or write operation failed."""


class ImageProcessingError(KreuzbergError):
    """An image manipulation operation (resize, decode, DPI conversion) failed."""


class SerializationError(KreuzbergError):
    """JSON or MessagePack serialization/deserialization failed."""


class MissingDependencyError(KreuzbergError):
    """A required optional system dependency (e.g. `tesseract`) was not found."""


class PluginError(KreuzbergError):
    """A registered plugin returned an error during extraction."""


class LockPoisonedError(KreuzbergError):
    """An internal `Mutex` or `RwLock` was found in a poisoned state."""


class UnsupportedFormatError(KreuzbergError):
    """The document's MIME type is not supported by any registered extractor."""


class EmbeddingError(KreuzbergError):
    """The embedding model or embedding pipeline returned an error."""


class RerankingError(KreuzbergError):
    """The reranker model or reranking pipeline returned an error."""


class TranscriptionError(KreuzbergError):
    """Audio/video transcription failed."""


class KreuzbergTimeoutError(KreuzbergError):
    """The extraction operation exceeded the configured time limit."""


class CancelledError(KreuzbergError):
    """The extraction was cancelled via a `CancellationToken`."""


class SecurityError(KreuzbergError):
    """A security policy was violated (e.g. zip bomb, oversized archive)."""


class OtherError(KreuzbergError):
    """A catch-all for uncommon errors that do not fit another variant."""
