// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1a5fd2c01e339b0cb1af6f2a612b9c3c4822cad9f397bf89982894f874eb33c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: registry

use kreuzberg::{list_document_extractors, list_ocr_backends, list_post_processors, list_validators};

#[test]
fn test_list_document_extractors() {
    // List document extractors
    let _ = list_document_extractors();
}

#[test]
fn test_list_ocr_backends() {
    // List OCR backends
    let _ = list_ocr_backends();
}

#[test]
fn test_list_post_processors() {
    // List post-processors
    let _ = list_post_processors();
}

#[test]
fn test_list_validators() {
    // List validators
    let _ = list_validators();
}
