// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2385f036e5dd4733b8d37146e4bceab02d9b1ffcc6ed038870a91a566d35aa17
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: summarization

use kreuzberg::extract_file_sync;

#[test]
fn test_summarization_extractive_smoke() {
    // TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required.
    let path: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/",
        "text/book_war_and_peace_1p.txt"
    );
    let mime_type: Option<String> = None;
    let config_json: serde_json::Value =
        serde_json::from_str(r#"{"summarization":{"max_tokens":80,"strategy":"extractive"}}"#).unwrap();
    let config = serde_json::from_value(config_json).unwrap();
    let result = extract_file_sync(path, mime_type.as_deref(), &config).expect("should succeed");
    assert_eq!(
        result.mime_type.to_string().as_str().trim(),
        r#"text/plain"#,
        "equals assertion failed"
    );
    assert!(
        !result.summary.as_ref().unwrap().text.is_empty(),
        "expected non-empty value"
    );
    assert_eq!(
        result.summary.as_ref().unwrap().strategy.to_string().as_str().trim(),
        r#"extractive"#,
        "equals assertion failed"
    );
}
