# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CitedField do
  @moduledoc "A single field with its citation envelope."

  @typedoc "A single field with its citation envelope."
  @type t :: %__MODULE__{
          value: String.t() | nil,
          page: non_neg_integer() | nil,
          confidence: float() | nil,
          source: String.t() | nil
        }

  defstruct value: nil,
            page: nil,
            confidence: nil,
            source: :llm
end
