# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2cb66c78f7aec60e31fcc9ad98498dfde4422c5c0abbbe0bf53a080f554b12cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
