# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:04dd93e71ba97bcf1658d70be8adfe5e756f1c851ce0a4b6993928f46f46e797
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
