# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c4ed597c7beb11c21c08eb657d38a2f336825dd3932ffba8461108cca62f969
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  field_type: String.t() | nil
  }

  defstruct name: nil,
  field_type: nil
end
