# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ae7a57a5f67a4483a2401ee09ff79ccb526ac6f43dd72cf53bbc71ff93758b67
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentRevision do
  @moduledoc """
  A single tracked change embedded in a document.

  Populated by per-format extractors that understand change-tracking metadata
  (DOCX `w:ins`/`w:del`/`w:rPrChange`, ODT `text:change-*`, …). Every
  extractor defaults to `ExtractedDocument.revisions = None` until a
  format-specific implementation is added.
  """

  @typedoc "A single tracked change embedded in a document."
  @type t :: %__MODULE__{
  revision_id: String.t() | nil,
  author: String.t() | nil,
  timestamp: String.t() | nil,
  kind: String.t() | nil,
  anchor: String.t() | nil | nil,
  delta: Xberg.RevisionDelta.t()
  }

  defstruct revision_id: nil,
  author: nil,
  timestamp: nil,
  kind: :insertion,
  anchor: nil,
  delta: nil
end
