# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a1926de7910b3789b64da14061dd23c1defcae86f0082fd54b028972453e2fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  data: binary(),
  compressed_size: non_neg_integer(),
  mime_type: String.t() | nil
  }

  defstruct name: nil,
  data: <<>>,
  compressed_size: 0,
  mime_type: nil
end
