# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9b6c82fdc18c3106bdec2c926b44f0262b7dcc51189a52c181c04410d16a2fd9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Entity do
  @moduledoc "A single named entity detected in the extracted text."

  @typedoc "A single named entity detected in the extracted text."
  @type t :: %__MODULE__{
          category: String.t() | nil,
          text: String.t() | nil,
          start: non_neg_integer(),
          end: non_neg_integer(),
          confidence: float() | nil
        }

  defstruct category: :person,
            text: nil,
            start: 0,
            end: 0,
            confidence: nil
end
