# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9b6c82fdc18c3106bdec2c926b44f0262b7dcc51189a52c181c04410d16a2fd9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: String.t() | nil
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
