# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:446748155774867df28fecd60b1f51d93e20d7476cf9f2aad1cd588a1cf0950e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  @typedoc "Header/heading element metadata."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil,
          id: String.t() | nil,
          depth: non_neg_integer(),
          html_offset: non_neg_integer()
        }

  defstruct level: 0,
            text: nil,
            id: nil,
            depth: 0,
            html_offset: 0

  @doc "Validate that the header level is within valid range (1-6)."
  @spec valid?(t()) :: boolean()
  def valid?(%__MODULE__{level: level}) do
    level >= 1 and level <= 6
  end
end
