# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a1926de7910b3789b64da14061dd23c1defcae86f0082fd54b028972453e2fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
  page_count: non_neg_integer(),
  pages: [Xberg.PageSignals.t()]
  }

  defstruct page_count: 0,
  pages: []
end
