# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:28933e85bc9dc440d3d48a0fa997a78b13df863b6249812908ba7914441b9232
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrTable do
  @moduledoc """
  Table detected via OCR.

  Represents a table structure recognized during OCR processing.
  """

  @typedoc "Table detected via OCR."
  @type t :: %__MODULE__{
  cells: [[String.t()]],
  markdown: String.t() | nil,
  page_number: non_neg_integer(),
  bounding_box: Xberg.OcrTableBoundingBox.t() | nil
  }

  defstruct cells: [],
  markdown: nil,
  page_number: 0,
  bounding_box: nil
end
