# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3ad1b68b0be4fdc6ebc01463167045ca5149b37b32b369d4f228dafdb6cc5cc
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OcrPageFailure do
  @moduledoc """
  A page whose OCR failed while extraction of the document continued.

  The warning in `ExtractedDocument::processing_warnings` stays available. One warning
  can cover several pages: when an automatic OCR run of selected pages fails as a whole,
  it adds one warning and one record for each selected page. A failure of the OCR fallback
  for the whole document adds a warning and no record. Repeated failures on one page make
  one record.
  """

  @typedoc "A page whose OCR failed while extraction of the document continued."
  @type t :: %__MODULE__{
          page: non_neg_integer(),
          error: String.t() | nil,
          recovered: boolean()
        }

  defstruct page: 0,
            error: nil,
            recovered: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
