# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ba7524a2759609dc6f17c04fa9ae89940b7a540ae2e9a3708ac3fca410f8701
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  @typedoc "Bounding box for an OCR-detected table in pixel coordinates."
  @type t :: %__MODULE__{
  left: non_neg_integer(),
  top: non_neg_integer(),
  right: non_neg_integer(),
  bottom: non_neg_integer()
  }

  defstruct left: 0,
  top: 0,
  right: 0,
  bottom: 0
end
