# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8bb2cf947e486dda2e680665792a6bb805dd879866ff4dcddb7bbdaea4e8a9cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrBoundingBox do
  @moduledoc "Pixel-space bounding box of a QR code inside its source image."

  @typedoc "Pixel-space bounding box of a QR code inside its source image."
  @type t :: %__MODULE__{
  x: non_neg_integer(),
  y: non_neg_integer(),
  width: non_neg_integer(),
  height: non_neg_integer()
  }

  defstruct x: 0,
  y: 0,
  width: 0,
  height: 0
end
