# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0f3e348cc193e0cfa8fdcc36fd3ebb5e08e4360d10b525744b736383abddeae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RecognizedTable do
  @moduledoc """
  Pre-computed table markdown for a table detection region.

  Produced by the TATR-based table structure recognizer and surfaced as part of
  layout-aware OCR results.  The struct lives here (under `layout-types`, pure-Rust)
  so that consumers who do not enable `layout-detection` (ORT) can still reference
  the type in their own code.
  """

  @typedoc "Pre-computed table markdown for a table detection region."
  @type t :: %__MODULE__{
          detection_bbox: Xberg.BBox.t(),
          cells: [[String.t()]],
          markdown: String.t() | nil
        }

  defstruct detection_bbox: nil,
            cells: [],
            markdown: nil
end
