# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:04dd93e71ba97bcf1658d70be8adfe5e756f1c851ce0a4b6993928f46f46e797
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RevisionDelta do
  @moduledoc """
  The content changes that make up a single revision.

  For insertions and deletions the `content` field carries the added/removed
  lines as `DiffLine::Added` / `DiffLine::Removed` entries. For format
  changes, `content` is empty — the property diff is left as a TODO for a
  later enrichment pass.
  """

  @typedoc "The content changes that make up a single revision."
  @type t :: %__MODULE__{
          content: [String.t() | nil],
          table_changes: [Xberg.CellChange.t()]
        }

  defstruct content: [],
            table_changes: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
