# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f4455c2b07242204473e94b1bab0fb0abca6b063de1f94569a77af55f6a3cb08
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.TesseractConfig do
  @moduledoc """
  Tesseract OCR configuration.

  Provides fine-grained control over Tesseract OCR engine parameters.
  Most users can use the defaults, but these settings allow optimization
  for specific document types (invoices, handwriting, etc.).

  **This is the public-facing counterpart of `ocr::types::TesseractConfig`
  (the internal, engine-facing representation with `u8`/`String` fields instead of
  `i32`/`Vec<String>`).** They are two independent struct definitions bridged only by
  an explicit `From<&TesseractConfig> for crate::ocr::types::TesseractConfig` impl in
  `ocr/types.rs` — that conversion carries field *values* across, but each struct keeps
  its own `Default` impl, and the conversion does nothing to keep those two defaults in
  sync. Several production call sites (`extractors::image::apply_default_tesseract_psm`,
  `configured_region_ocr`, `sparse_image_ocr_fallback_config`) construct *this* struct's
  default and convert it, bypassing the internal struct's `Default` entirely — so if the
  two defaults disagree, standalone image OCR silently uses this struct's value while
  PDF-embedded OCR (which can reach the internal `Default` directly when no
  `tesseract_config` is set) uses the other. When changing a default here, also update
  `ocr::types::TesseractConfig::default`, and vice versa.
  """

  @typedoc "Tesseract OCR configuration."
  @type t :: %__MODULE__{
          language: [String.t()],
          psm: integer() | nil,
          output_format: String.t() | nil,
          oem: integer(),
          min_confidence: float(),
          preprocessing: Xberg.ImagePreprocessingConfig.t() | nil,
          enable_table_detection: boolean(),
          table_min_confidence: float(),
          table_column_threshold: integer(),
          table_row_threshold_ratio: float(),
          use_cache: boolean(),
          classify_use_pre_adapted_templates: boolean(),
          language_model_ngram_on: boolean(),
          tessedit_dont_blkrej_good_wds: boolean(),
          tessedit_dont_rowrej_good_wds: boolean(),
          tessedit_enable_dict_correction: boolean(),
          tessedit_char_whitelist: String.t() | nil,
          tessedit_char_blacklist: String.t() | nil,
          tessedit_use_primary_params_model: boolean(),
          textord_space_size_is_variable: boolean(),
          thresholding_method: String.t() | nil
        }

  defstruct language: ["eng"],
            psm: nil,
            output_format: "markdown",
            oem: 3,
            min_confidence: 0,
            preprocessing: nil,
            enable_table_detection: true,
            table_min_confidence: 0,
            table_column_threshold: 50,
            table_row_threshold_ratio: 0.5,
            use_cache: true,
            classify_use_pre_adapted_templates: true,
            language_model_ngram_on: true,
            tessedit_dont_blkrej_good_wds: true,
            tessedit_dont_rowrej_good_wds: true,
            tessedit_enable_dict_correction: true,
            tessedit_char_whitelist: "",
            tessedit_char_blacklist: "",
            tessedit_use_primary_params_model: true,
            textord_space_size_is_variable: true,
            thresholding_method: "otsu"

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
