<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8bb2cf947e486dda2e680665792a6bb805dd879866ff4dcddb7bbdaea4e8a9cf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractInput;
use Xberg\ExtractionConfig;

/** E2e tests for category: batch. */
final class BatchTest extends TestCase
{

    /** extract_batch: happy path with mixed inputs */
    public function test_extract_batch_bytes_happy(): void
    {
        $result = Xberg::extractBatch([ExtractInput::from_json('{"bytes":[72,101,108,108,111,44,32,119,111,114,108,100,33],"kind":"bytes","mime_type":"text/plain"}'), ExtractInput::from_json('{"bytes":[60,104,116,109,108,62,60,98,111,100,121,62,84,101,115,116,60,47,98,111,100,121,62,60,47,104,116,109,108,62],"kind":"bytes","mime_type":"text/html"}')], \Xberg\ExtractionConfig::from_json('{}'));
        $results = $result->getResults();

            $this->assertGreaterThanOrEqual(1, count($results));


    }


    /** extract_batch with invalid bytes MIME type */
    public function test_extract_batch_bytes_invalid_mime(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::extractBatch([ExtractInput::from_json('{"bytes":[72,101,108,108,111],"kind":"bytes","mime_type":"application/x-nonexistent"}')], \Xberg\ExtractionConfig::from_json('{}'));


    }


    /** extract_batch: handles unsupported MIME gracefully */
    public function test_extract_batch_bytes_mixed_format(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::extractBatch([ExtractInput::from_json('{"bytes":[80,68,70,32,112,108,97,99,101,104,111,108,100,101,114],"kind":"bytes","mime_type":"application/x-unknown"}')], \Xberg\ExtractionConfig::from_json('{}'));


    }


    /** extract_batch with unsupported bytes MIME type */
    public function test_extract_batch_bytes_unsupported_mime(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::extractBatch([ExtractInput::from_json('{"bytes":[100,97,116,97],"kind":"bytes","mime_type":"application/x-unknown"}')], \Xberg\ExtractionConfig::from_json('{}'));


    }


    /** extract_batch: empty batch */
    public function test_extract_batch_empty_inputs(): void
    {
        $result = Xberg::extractBatch([], \Xberg\ExtractionConfig::from_json('{}'));
        $results = $result->getResults();

            $this->assertCount(0, $results);


    }


    /** extract_batch with missing URI inputs */
    public function test_extract_batch_uri_all_missing(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::extractBatch([ExtractInput::from_json('{"kind":"uri","uri":"/nonexistent/a.pdf"}'), ExtractInput::from_json('{"kind":"uri","uri":"/nonexistent/b.txt"}')], \Xberg\ExtractionConfig::from_json('{}'));


    }


    /** extract_batch over URI inputs */
    public function test_extract_batch_uri_basic(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::extractBatch([ExtractInput::from_json('{"kind":"uri","uri":"pdf/fake_memo.pdf"}'), ExtractInput::from_json('{"kind":"uri","uri":"text/fake_text.txt"}')], \Xberg\ExtractionConfig::from_json('{}'));


    }


    /** extract_batch with missing URI input */
    public function test_extract_batch_uri_not_found(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::extractBatch([ExtractInput::from_json('{"kind":"uri","uri":"/nonexistent/a.pdf"}')], \Xberg\ExtractionConfig::from_json('{}'));


    }


    /** extract_batch with mixed valid and missing URI inputs */
    public function test_extract_batch_uri_partial_failure(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::extractBatch([ExtractInput::from_json('{"kind":"uri","uri":"text/plain.txt"}'), ExtractInput::from_json('{"kind":"uri","uri":"/nonexistent/missing.pdf"}')], \Xberg\ExtractionConfig::from_json('{}'));


    }

}
