<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0faa091a47b256ebba1e8379b247a65f35e0fc46e65b004a4271f18fa009dbee
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: code. */
final class CodeTest extends TestCase
{

    /** Test language detection from shebang line via bytes input */
    public function test_code_shebang_detection(): void
    {
        $result = Kreuzberg::extractFileSync("code/script.sh", "text/x-source-code", \Kreuzberg\ExtractionConfig::from_json('{}'));

            $this->assertEquals("text/x-source-code", trim($result->mimeType));
            $this->assertGreaterThanOrEqual(10, strlen($result->content));
            $this->assertStringContainsString("build", $result->content);
    $this->assertStringContainsString("clean", $result->content);

    }

}
