// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:be0ca5196793cdf505ad71c96bf36e353ba155a1a4a17c4a70ab0b15f7ac0e7b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg

/// E2e tests for category: contract.
final class ContractTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testApiBatchBytesAsync() async throws {
        // Tests async batch bytes extraction API (batch_extract_bytes)
        let configObj = try extractionConfigFromJson("{}")
        let result = try await Kreuzberg.extractFile(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertTrue(result.content.contains("May 5, 2023") || result.content.contains("Mallori"), "expected to contain at least one of the specified values")
    }

    func testApiBatchBytesWithConfigsAsync() async throws {
        // Tests async batch bytes extraction with per-file configs (batch_extract_bytes with file_configs parameter)
        let configObj = try extractionConfigFromJson("{\"output_format\":\"markdown\"}")
        let result = try await Kreuzberg.extractFile(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertEqual((result.metadata.outputFormat ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "markdown")
    }

    func testApiBatchFileAsync() async throws {
        // Tests async batch file extraction API (batch_extract_file)
        let configObj = try extractionConfigFromJson("{}")
        let result = try await Kreuzberg.extractFile(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertTrue(result.content.contains("May 5, 2023") || result.content.contains("Mallori"), "expected to contain at least one of the specified values")
    }

    func testApiBatchFileWithConfigsAsync() async throws {
        // Tests async batch file extraction with per-file configs (batch_extract_files with file_configs parameter)
        let configObj = try extractionConfigFromJson("{\"output_format\":\"markdown\"}")
        let result = try await Kreuzberg.extractFile(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertEqual((result.metadata.outputFormat ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "markdown")
    }

    func testApiExtractBytesAsync() async throws {
        // Tests async bytes extraction API (extract_bytes)
        let configObj = try extractionConfigFromJson("{}")
        let result = try await Kreuzberg.extractFile(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertTrue(result.content.contains("May 5, 2023") || result.content.contains("Mallori"), "expected to contain at least one of the specified values")
    }

    func testApiExtractFileAsync() async throws {
        // Tests async file extraction API (extract_file)
        let configObj = try extractionConfigFromJson("{}")
        let result = try await Kreuzberg.extractFile(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertTrue(result.content.contains("May 5, 2023") || result.content.contains("Mallori"), "expected to contain at least one of the specified values")
    }

    func testConfigChunkingPrependHeadingContext() throws {
        // Tests markdown chunker prepends heading hierarchy to chunk content
        let configObj = try extractionConfigFromJson("{\"chunking\":{\"chunker_type\":\"markdown\",\"max_chars\":300,\"max_overlap\":50,\"prepend_heading_context\":true}}")
        let result = try Kreuzberg.extractFileSync(path: "markdown/extraction_test.md", mimeType: nil, config: configObj)
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertGreaterThanOrEqual((result.chunks()?.count ?? 0), 2)
        XCTAssertTrue(result.chunksHaveContent)
        XCTAssertTrue(result.chunksHaveHeadingContext)
        XCTAssertTrue(result.firstChunkStartsWithHeading)
    }

    func testConfigDocumentStructureWithHeadings() throws {
        // Tests document structure with DOCX heading-driven nesting
        let configObj = try extractionConfigFromJson("{\"include_document_structure\":true}")
        let result = try Kreuzberg.extractFileSync(path: "docx/fake.docx", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
        XCTAssertNotNil(result.document, "expected non-nil value")
        XCTAssertGreaterThanOrEqual(result.document()?.nodes().count ?? 0, 1)
    }

    func testConfigElementTypes() throws {
        // Tests element-based result format with element type assertions on DOCX
        let configObj = try extractionConfigFromJson("{\"result_format\":\"element_based\"}")
        let result = try Kreuzberg.extractFileSync(path: "docx/unit_test_headers.docx", mimeType: nil, config: configObj)
        XCTAssertTrue(result.mimeType.contains("application/vnd.openxmlformats-officedocument.wordprocessingml.document"), "expected to contain at least one of the specified values")
        XCTAssertGreaterThanOrEqual((result.elements()?.count ?? 0), 1)
    }

    func testConfigExtractionTimeout() throws {
        // Tests that extraction_timeout_secs config field is accepted and does not affect fast extractions
        let configObj = try extractionConfigFromJson("{\"extraction_timeout_secs\":300}")
        let result = try Kreuzberg.extractFileSync(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
    }

    func testConfigKeywords() throws {
        // Tests keyword extraction via YAKE algorithm
        let configObj = try extractionConfigFromJson("{\"keywords\":{\"algorithm\":\"yake\",\"max_keywords\":10}}")
        let result = try Kreuzberg.extractFileSync(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertGreaterThan(result.keywords.count, 0, "expected non-empty value")
        XCTAssertGreaterThanOrEqual(result.keywords().count, 1)
    }

    func testConfigPages() throws {
        // Tests page extraction and page marker configuration
        let configObj = try extractionConfigFromJson("{\"pages\":{\"extract_pages\":true,\"insert_page_markers\":true}}")
        let result = try Kreuzberg.extractFileSync(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertTrue(result.content.contains("PAGE"), "expected to contain at least one of the specified values")
    }

    func testConfigQualityEnabled() throws {
        // Tests quality scoring produces a score value in [0.0, 1.0]
        let configObj = try extractionConfigFromJson("{\"enable_quality_processing\":true}")
        let result = try Kreuzberg.extractFileSync(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertNotNil(result.qualityScore, "expected non-nil value")
        XCTAssertGreaterThanOrEqual((result.qualityScore ?? 0), 0.0)
        XCTAssertLessThanOrEqual((result.qualityScore ?? 0), 1.0)
    }

    func testConfigSecurityLimits() throws {
        // Tests archive extraction with custom security limits
        let configObj = try extractionConfigFromJson("{\"security_limits\":{\"max_archive_size\":104857600,\"max_compression_ratio\":50,\"max_files_in_archive\":100}}")
        let result = try Kreuzberg.extractFileSync(path: "archives/documents.zip", mimeType: nil, config: configObj)
        XCTAssertTrue(result.mimeType.contains("application/zip") || result.mimeType.contains("application/x-zip-compressed"), "expected to contain at least one of the specified values")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
    }

    func testConfigTreeSitter() throws {
        // Tests tree-sitter configuration round-trip
        let configObj = try extractionConfigFromJson("{\"tree_sitter\":{\"groups\":[\"web\"],\"languages\":[\"python\",\"rust\"],\"process\":{\"comments\":false,\"diagnostics\":false,\"docstrings\":false,\"exports\":true,\"imports\":true,\"structure\":true,\"symbols\":false}}}")
        let result = try Kreuzberg.extractFileSync(path: "code/hello.py", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "text/x-source-code")
        XCTAssertGreaterThanOrEqual(result.content.count, 5)
    }

    func testOutputFormatBytesMarkdown() throws {
        // Tests markdown output format via bytes extraction API
        let contentData = try Data(contentsOf: URL(fileURLWithPath: "pdf/fake_memo.pdf"))
        let contentVec = RustBridge.RustVec<UInt8>()
        for _byte in contentData { contentVec.push(value: _byte) }
        let configObj = try extractionConfigFromJson("{\"output_format\":\"markdown\"}")
        let result = try Kreuzberg.extractBytesSync(content: contentVec, mimeType: "application/pdf", config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertEqual((result.metadata.outputFormat ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "markdown")
    }

    func testOutputFormatMarkdown() throws {
        // Tests Markdown output format
        let configObj = try extractionConfigFromJson("{\"output_format\":\"markdown\"}")
        let result = try Kreuzberg.extractFileSync(path: "pdf/fake_memo.pdf", mimeType: nil, config: configObj)
        XCTAssertEqual(result.mimeType.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content.count, 10)
        XCTAssertEqual((result.metadata.outputFormat ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "markdown")
    }

}
