// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4e31e2de5abb6a698abb398126f66a7c3b8da270359a8966814d52fe645b03bd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: embedding_backend_management.
final class EmbeddingBackendManagementTests: XCTestCase {
    func testEmbeddingBackendsClear() throws {
        // Clear all embedding backends and verify list is empty
        let result = try Kreuzberg.clearEmbeddingBackends()
    }

    func testEmbeddingBackendsList() throws {
        // List all registered embedding backends
        let result = try Kreuzberg.listEmbeddingBackends()
    }

}
