// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:decbacb38ca392b0d8e278b7044150d6b3cb3a645f79702094e10190b73e260b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: registry.
final class RegistryTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testListDocumentExtractors() throws {
        // List document extractors
        let result = try Kreuzberg.listDocumentExtractors()
    }

    func testListEmbeddingBackends() throws {
        // List embedding backends
        let result = try Kreuzberg.listEmbeddingBackends()
    }

    func testListOcrBackends() throws {
        // List OCR backends
        let result = try Kreuzberg.listOcrBackends()
    }

    func testListPostProcessors() throws {
        // List post-processors
        let result = try Kreuzberg.listPostProcessors()
    }

    func testListRenderers() throws {
        // List renderers
        let result = try Kreuzberg.listRenderers()
    }

    func testListValidators() throws {
        // List validators
        let result = try Kreuzberg.listValidators()
    }

}
