// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:37046f5e2146c7b3937652361ef11ca94d1ec9802ee7356a330af1192cab920e
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
