// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4001a48eb806f6f50b125457fd75ded87092b78bc1bfe88dfaa34c0d66cb1682
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// dBASE field information.
/// </summary>
public sealed class DbfFieldInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("field_type")]
    public string FieldType { get; set; } = "";

}
