// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c14f485d75e266f6cf80a07a2e1174872fc96f33e97a2cae26e0b65d0163a8f7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// EPUB metadata (Dublin Core extensions).
/// </summary>
public sealed class EpubMetadata
{
    [JsonPropertyName("coverage")]
    public string? Coverage { get; set; } = null;

    [JsonPropertyName("dc_format")]
    public string? DcFormat { get; set; } = null;

    [JsonPropertyName("relation")]
    public string? Relation { get; set; } = null;

    [JsonPropertyName("source")]
    public string? Source { get; set; } = null;

    [JsonPropertyName("dc_type")]
    public string? DcType { get; set; } = null;

    [JsonPropertyName("cover_image")]
    public string? CoverImage { get; set; } = null;


    /// <summary>
    /// Parse a <see cref="EpubMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static EpubMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<EpubMetadata>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse EpubMetadata from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse EpubMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
