// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d715a94173c0396b2dfcbe0a068a59d1534f3a61380d193393d8da2565aeeffc
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The preset's declared `id` does not match its file-system location.
/// </summary>
public class IdMismatchException : LoadErrorException
{
    public IdMismatchException(string message) : base(message) { }

    public IdMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
