// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d86aadd48600a27da227c2faa64439824e1e9b105a64f8f5b6f71201ee591e39
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// OCR backend types./// </summary>
public enum OcrBackendType
{/// <summary>    /// Tesseract OCR (native Rust binding)    /// </summary>
    [JsonPropertyName("tesseract")]
    Tesseract,/// <summary>    /// EasyOCR (Python-based, via FFI)    /// </summary>
    [JsonPropertyName("easyocr")]
    EasyOcr,/// <summary>    /// PaddleOCR (Python-based, via FFI)    /// </summary>
    [JsonPropertyName("paddleocr")]
    PaddleOcr,/// <summary>    /// Custom/third-party OCR backend    /// </summary>
    [JsonPropertyName("custom")]
    Custom,
}
