// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e5ed2b14a30c61dc3e9f97bc9a6dd74f6f180c314268436f3f3757365869c362
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
