// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:650c0672496dd63a5d3f6454b5003e3c1d2319de243bbc54444e5503dc79249d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ReductionLevel
{    [JsonPropertyName("off")]
    Off,    [JsonPropertyName("light")]
    Light,    [JsonPropertyName("moderate")]
    Moderate,    [JsonPropertyName("aggressive")]
    Aggressive,    [JsonPropertyName("maximum")]
    Maximum,}
