// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e8f7fc071d9d6cc8b9860edf80e586eaf81beff15ec144b16178e746bcaccf7c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class StructuredDataResult
{
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    [JsonPropertyName("format")]
    public string Format { get; set; } = "";

    [JsonPropertyName("metadata")]
    public Dictionary<string, string> Metadata { get; set; } = default!;

    [JsonPropertyName("text_fields")]
    public List<string> TextFields { get; set; } = [];

}
