// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9b6c82fdc18c3106bdec2c926b44f0262b7dcc51189a52c181c04410d16a2fd9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: renderer_management.
final class RendererManagementTests: XCTestCase {
  override class func setUp() {
    super.setUp()
    _ = "true".withCString { val in
      "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
        setenv(key, val, 0)
      }
    }
    let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
  }

  func testRenderersClear() throws {
    // Clear all renderers and verify list is empty
    let result = try Xberg.clearRenderers()
  }

  func testRenderersList() throws {
    // List all registered renderers
    let result = try Xberg.listRenderers()
  }

}
