# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:446748155774867df28fecd60b1f51d93e20d7476cf9f2aad1cd588a1cf0950e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Public API for conversion."""

import json
from typing import Any, TypeVar, cast, overload

import xberg._xberg as _rust

from ._xberg import ChunkingDecision, ChunkingResult, Citation, ClassificationLabel, ConfidenceSignals, DocumentBoundary, DocumentMetadata, EmbeddingBackend, EmbeddingPreset, ExtractionConfidence, ExtractionDiff, ExtractionResult, FootnoteAnchor, FootnoteDefinition, Keyword, MultidocInput, OcrBackend, PageClassificationConfig, PageRange, PatternMatch, PiiCategory, PostProcessor, Preset, QrCode, RegionKind, Renderer, RerankedDocument, RerankerBackend, RerankerPreset, ResolvedPreset, StructuredCallMode, StructuredInput, SupportedFormat, TranslationConfig, Validator
from .options import AccelerationConfig, BoundingBox, ChunkPlan, ChunkingConfig, ConfidenceWeights, ContentFilterConfig, DiffOptions, DocumentStructure, EmailConfig, EmbeddingConfig, ExtractInput, ExtractedImage, ExtractionConfig, ExtractionOutput, FileExtractionConfig, HeuristicsConfig, HierarchyConfig, HtmlOutputConfig, ImageExtractionConfig, ImagePreprocessingConfig, KeywordConfig, LanguageDetectionConfig, LayoutDetectionConfig, LlmConfig, LlmUsage, Metadata, MultidocThresholds, NerConfig, OcrConfidence, OcrConfig, OcrElement, OcrElementConfig, OcrQualityThresholds, PageConfig, PdfConfig, PostProcessorConfig, RakeParams, RedactionConfig, RerankerConfig, SecurityLimits, StructuredThresholds, SummarizationConfig, SvgOptions, Table, TesseractConfig, TokenReductionOptions, TranscriptionConfig, TreeSitterConfig, TreeSitterProcessConfig, UrlExtractionConfig, YakeParams

_E = TypeVar("_E")

def _pascal_to_snake(value: str) -> str:
    """Convert PascalCase/camelCase to snake_case (AtxClosed -> atx_closed)."""
    out_chars: list[str] = []
    for index, ch in enumerate(value):
        if ch.isupper() and index > 0 and (value[index - 1].islower() or (index + 1 < len(value) and value[index + 1].islower())):
            out_chars.append("_")
        out_chars.append(ch.lower())
    return "".join(out_chars)


def _coerce_enum(enum_cls: type[_E], value: object) -> _E:
    """Coerce a string/alias value into the matching pyclass enum instance."""
    if isinstance(value, enum_cls):
        return value
    if value is None:
        msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
        raise ValueError(msg)
    s = str(value).replace("-", "_").replace(" ", "_")
    snake = _pascal_to_snake(s)
    candidates = (
        s,
        s.upper(),
        s.lower(),
        snake,
        snake.upper(),
        "".join(part.capitalize() for part in s.split("_")),
        "".join(part.capitalize() for part in snake.split("_")),
    )
    for candidate in candidates:
        attr = getattr(enum_cls, candidate, None)
        if isinstance(attr, enum_cls):
            return attr
    msg = f"unknown {getattr(enum_cls, '__name__', enum_cls)!s} value: {value!r}"
    raise ValueError(msg)


@overload
def _to_rust_image_preprocessing_config(value: None) -> None: ...


@overload
def _to_rust_image_preprocessing_config(value: ImagePreprocessingConfig | dict[str, Any] | str) -> _rust.ImagePreprocessingConfig: ...
def _to_rust_image_preprocessing_config(
    value: ImagePreprocessingConfig | dict[str, Any] | str | None,
) -> _rust.ImagePreprocessingConfig | None:
    """Convert Python ImagePreprocessingConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = ImagePreprocessingConfig(**value)
    if value is None:
        return None
    value = cast(ImagePreprocessingConfig, value)
    return _rust.ImagePreprocessingConfig(
        target_dpi=value.target_dpi,
        auto_rotate=value.auto_rotate,
        deskew=value.deskew,
        denoise=value.denoise,
        contrast_enhance=value.contrast_enhance,
        binarization_method=value.binarization_method,
        invert_colors=value.invert_colors,
    )


@overload
def _to_rust_tesseract_config(value: None) -> None: ...


@overload
def _to_rust_tesseract_config(value: TesseractConfig | dict[str, Any] | str) -> _rust.TesseractConfig: ...
def _to_rust_tesseract_config(value: TesseractConfig | dict[str, Any] | str | None) -> _rust.TesseractConfig | None:
    """Convert Python TesseractConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "preprocessing" in value and value["preprocessing"] is not None:
            value["preprocessing"] = _to_rust_image_preprocessing_config(value["preprocessing"])
        value = TesseractConfig(**value)
    if value is None:
        return None
    value = cast(TesseractConfig, value)
    return _rust.TesseractConfig(
        language=value.language,
        psm=value.psm,
        output_format=value.output_format,
        oem=value.oem,
        min_confidence=value.min_confidence,
        preprocessing=_to_rust_image_preprocessing_config(value.preprocessing),
        enable_table_detection=value.enable_table_detection,
        table_min_confidence=value.table_min_confidence,
        table_column_threshold=value.table_column_threshold,
        table_row_threshold_ratio=value.table_row_threshold_ratio,
        use_cache=value.use_cache,
        classify_use_pre_adapted_templates=value.classify_use_pre_adapted_templates,
        language_model_ngram_on=value.language_model_ngram_on,
        tessedit_dont_blkrej_good_wds=value.tessedit_dont_blkrej_good_wds,
        tessedit_dont_rowrej_good_wds=value.tessedit_dont_rowrej_good_wds,
        tessedit_enable_dict_correction=value.tessedit_enable_dict_correction,
        tessedit_char_whitelist=value.tessedit_char_whitelist,
        tessedit_char_blacklist=value.tessedit_char_blacklist,
        tessedit_use_primary_params_model=value.tessedit_use_primary_params_model,
        textord_space_size_is_variable=value.textord_space_size_is_variable,
        thresholding_method=value.thresholding_method,
    )


@overload
def _to_rust_ocr_element_config(value: None) -> None: ...


@overload
def _to_rust_ocr_element_config(value: OcrElementConfig | dict[str, Any] | str) -> _rust.OcrElementConfig: ...
def _to_rust_ocr_element_config(value: OcrElementConfig | dict[str, Any] | str | None) -> _rust.OcrElementConfig | None:
    """Convert Python OcrElementConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "min_level" in value and value["min_level"] is not None:
            value["min_level"] = _coerce_enum(_rust.OcrElementLevel, value["min_level"])
        value = OcrElementConfig(**value)
    if value is None:
        return None
    value = cast(OcrElementConfig, value)
    return _rust.OcrElementConfig(
        include_elements=value.include_elements,
        **({"min_level": _coerce_enum(_rust.OcrElementLevel, value.min_level)} if value.min_level is not None else {}),
        min_confidence=value.min_confidence,
        build_hierarchy=value.build_hierarchy,
    )


@overload
def _to_rust_ocr_quality_thresholds(value: None) -> None: ...


@overload
def _to_rust_ocr_quality_thresholds(value: OcrQualityThresholds | dict[str, Any] | str) -> _rust.OcrQualityThresholds: ...
def _to_rust_ocr_quality_thresholds(
    value: OcrQualityThresholds | dict[str, Any] | str | None,
) -> _rust.OcrQualityThresholds | None:
    """Convert Python OcrQualityThresholds to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = OcrQualityThresholds(**value)
    if value is None:
        return None
    value = cast(OcrQualityThresholds, value)
    return _rust.OcrQualityThresholds(
        min_total_non_whitespace=value.min_total_non_whitespace,
        min_non_whitespace_per_page=value.min_non_whitespace_per_page,
        min_meaningful_word_len=value.min_meaningful_word_len,
        min_meaningful_words=value.min_meaningful_words,
        min_alnum_ratio=value.min_alnum_ratio,
        min_garbage_chars=value.min_garbage_chars,
        max_fragmented_word_ratio=value.max_fragmented_word_ratio,
        critical_fragmented_word_ratio=value.critical_fragmented_word_ratio,
        min_avg_word_length=value.min_avg_word_length,
        min_words_for_avg_length_check=value.min_words_for_avg_length_check,
        min_consecutive_repeat_ratio=value.min_consecutive_repeat_ratio,
        min_words_for_repeat_check=value.min_words_for_repeat_check,
        substantive_min_chars=value.substantive_min_chars,
        non_text_min_chars=value.non_text_min_chars,
        alnum_ws_ratio_threshold=value.alnum_ws_ratio_threshold,
        pipeline_min_quality=value.pipeline_min_quality,
    )


@overload
def _to_rust_llm_config(value: None) -> None: ...


@overload
def _to_rust_llm_config(value: LlmConfig | dict[str, Any] | str) -> _rust.LlmConfig: ...
def _to_rust_llm_config(value: LlmConfig | dict[str, Any] | str | None) -> _rust.LlmConfig | None:
    """Convert Python LlmConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = LlmConfig(**value)
    if value is None:
        return None
    value = cast(LlmConfig, value)
    return _rust.LlmConfig(
        model=value.model,
        api_key=value.api_key,
        base_url=value.base_url,
        timeout_secs=value.timeout_secs,
        max_retries=value.max_retries,
        temperature=value.temperature,
        max_tokens=value.max_tokens,
    )


@overload
def _to_rust_acceleration_config(value: None) -> None: ...


@overload
def _to_rust_acceleration_config(value: AccelerationConfig | dict[str, Any] | str) -> _rust.AccelerationConfig: ...
def _to_rust_acceleration_config(
    value: AccelerationConfig | dict[str, Any] | str | None,
) -> _rust.AccelerationConfig | None:
    """Convert Python AccelerationConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "provider" in value and value["provider"] is not None:
            value["provider"] = _coerce_enum(_rust.ExecutionProviderType, value["provider"])
        value = AccelerationConfig(**value)
    if value is None:
        return None
    value = cast(AccelerationConfig, value)
    return _rust.AccelerationConfig(
        **({"provider": _coerce_enum(_rust.ExecutionProviderType, value.provider)} if value.provider is not None else {}),
        device_id=value.device_id,
    )


def _coerce_dict_ocr_config(value: dict[str, Any]) -> OcrConfig:
    """Coerce a dict into OcrConfig, converting nested types in-place."""
    _struct_coercions = {
        "tesseract_config": _to_rust_tesseract_config,
        "element_config": _to_rust_ocr_element_config,
        "quality_thresholds": _to_rust_ocr_quality_thresholds,
        "vlm_config": _to_rust_llm_config,
        "acceleration": _to_rust_acceleration_config,
    }
    for _k, _fn in _struct_coercions.items():
        if _k in value and value[_k] is not None:
            value[_k] = _fn(value[_k])
    _data_enum_coercions = {
        "output_format": _rust.OutputFormat,
        "vlm_fallback": _rust.VlmFallbackPolicy,
    }
    for _k, _cls in _data_enum_coercions.items():
        if _k in value and value[_k] is not None and not isinstance(value[_k], _cls):
            value[_k] = _cls(value[_k])
    return OcrConfig(**value)
@overload
def _to_rust_ocr_config(value: None) -> None: ...


@overload
def _to_rust_ocr_config(value: OcrConfig | dict[str, Any] | str) -> _rust.OcrConfig: ...
def _to_rust_ocr_config(value: OcrConfig | dict[str, Any] | str | None) -> _rust.OcrConfig | None:
    """Convert Python OcrConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = _coerce_dict_ocr_config(value)
    if value is None:
        return None
    value = cast(OcrConfig, value)
    return _rust.OcrConfig(
        enabled=value.enabled,
        backend=value.backend,
        language=value.language,
        tesseract_config=_to_rust_tesseract_config(value.tesseract_config),
        output_format=(value.output_format if isinstance(value.output_format, _rust.OutputFormat) else _rust.OutputFormat(value.output_format)) if value.output_format is not None else None,
        paddle_ocr_config=value.paddle_ocr_config,
        backend_options=value.backend_options,
        element_config=_to_rust_ocr_element_config(value.element_config),
        quality_thresholds=_to_rust_ocr_quality_thresholds(value.quality_thresholds),
        pipeline=value.pipeline,
        auto_rotate=value.auto_rotate,
**({"vlm_fallback": value.vlm_fallback if isinstance(value.vlm_fallback, _rust.VlmFallbackPolicy) else _rust.VlmFallbackPolicy(value.vlm_fallback)} if value.vlm_fallback is not None else {}),
        vlm_config=_to_rust_llm_config(value.vlm_config),
        vlm_prompt=value.vlm_prompt,
        acceleration=_to_rust_acceleration_config(value.acceleration),
        tessdata_bytes=value.tessdata_bytes,
        tessdata_path=value.tessdata_path,
    )


@overload
def _to_rust_embedding_config(value: None) -> None: ...


@overload
def _to_rust_embedding_config(value: EmbeddingConfig | dict[str, Any] | str) -> _rust.EmbeddingConfig: ...
def _to_rust_embedding_config(value: EmbeddingConfig | dict[str, Any] | str | None) -> _rust.EmbeddingConfig | None:
    """Convert Python EmbeddingConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "acceleration" in value and value["acceleration"] is not None:
            value["acceleration"] = _to_rust_acceleration_config(value["acceleration"])
        if "model" in value and value["model"] is not None and not isinstance(value["model"], _rust.EmbeddingModelType):
            value["model"] = _rust.EmbeddingModelType(value["model"])
        value = EmbeddingConfig(**value)
    if value is None:
        return None
    value = cast(EmbeddingConfig, value)
    return _rust.EmbeddingConfig(
        model=value.model if isinstance(value.model, _rust.EmbeddingModelType) else _rust.EmbeddingModelType(value.model),
        normalize=value.normalize,
        batch_size=value.batch_size,
        show_download_progress=value.show_download_progress,
        cache_dir=value.cache_dir,
        acceleration=_to_rust_acceleration_config(value.acceleration),
        max_embed_duration_secs=value.max_embed_duration_secs,
    )


@overload
def _to_rust_chunking_config(value: None) -> None: ...


@overload
def _to_rust_chunking_config(value: ChunkingConfig | dict[str, Any] | str) -> _rust.ChunkingConfig: ...
def _to_rust_chunking_config(value: ChunkingConfig | dict[str, Any] | str | None) -> _rust.ChunkingConfig | None:
    """Convert Python ChunkingConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        # Alias serde-renamed keys back to Rust field names
        if "max_chars" in value and "max_characters" not in value:
            value["max_characters"] = value.pop("max_chars")
        if "max_overlap" in value and "overlap" not in value:
            value["overlap"] = value.pop("max_overlap")
        if "chunker_type" in value and value["chunker_type"] is not None:
            value["chunker_type"] = _coerce_enum(_rust.ChunkerType, value["chunker_type"])
        if "table_chunking" in value and value["table_chunking"] is not None:
            value["table_chunking"] = _coerce_enum(_rust.TableChunkingMode, value["table_chunking"])
        if "embedding" in value and value["embedding"] is not None:
            value["embedding"] = _to_rust_embedding_config(value["embedding"])
        if "sizing" in value and value["sizing"] is not None and not isinstance(value["sizing"], _rust.ChunkSizing):
            value["sizing"] = _rust.ChunkSizing(value["sizing"])
        value = ChunkingConfig(**value)
    if value is None:
        return None
    value = cast(ChunkingConfig, value)
    return _rust.ChunkingConfig(
        max_chars=value.max_characters,
        max_overlap=value.overlap,
        trim=value.trim,
        chunker_type=_coerce_enum(_rust.ChunkerType, value.chunker_type),
        embedding=_to_rust_embedding_config(value.embedding),
        preset=value.preset,
**({"sizing": value.sizing if isinstance(value.sizing, _rust.ChunkSizing) else _rust.ChunkSizing(value.sizing)} if value.sizing is not None else {}),
        prepend_heading_context=value.prepend_heading_context,
        topic_threshold=value.topic_threshold,
        **({"table_chunking": _coerce_enum(_rust.TableChunkingMode, value.table_chunking)} if value.table_chunking is not None else {}),
    )


@overload
def _to_rust_content_filter_config(value: None) -> None: ...


@overload
def _to_rust_content_filter_config(value: ContentFilterConfig | dict[str, Any] | str) -> _rust.ContentFilterConfig: ...
def _to_rust_content_filter_config(
    value: ContentFilterConfig | dict[str, Any] | str | None,
) -> _rust.ContentFilterConfig | None:
    """Convert Python ContentFilterConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = ContentFilterConfig(**value)
    if value is None:
        return None
    value = cast(ContentFilterConfig, value)
    return _rust.ContentFilterConfig(
        include_headers=value.include_headers,
        include_footers=value.include_footers,
        strip_repeating_text=value.strip_repeating_text,
        include_watermarks=value.include_watermarks,
    )


@overload
def _to_rust_svg_options(value: None) -> None: ...


@overload
def _to_rust_svg_options(value: SvgOptions | dict[str, Any] | str) -> _rust.SvgOptions: ...
def _to_rust_svg_options(value: SvgOptions | dict[str, Any] | str | None) -> _rust.SvgOptions | None:
    """Convert Python SvgOptions to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = SvgOptions(**value)
    if value is None:
        return None
    value = cast(SvgOptions, value)
    return _rust.SvgOptions(
        sanitize=value.sanitize,
        render_dpi=value.render_dpi,
    )


@overload
def _to_rust_image_extraction_config(value: None) -> None: ...


@overload
def _to_rust_image_extraction_config(value: ImageExtractionConfig | dict[str, Any] | str) -> _rust.ImageExtractionConfig: ...
def _to_rust_image_extraction_config(
    value: ImageExtractionConfig | dict[str, Any] | str | None,
) -> _rust.ImageExtractionConfig | None:
    """Convert Python ImageExtractionConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "svg" in value and value["svg"] is not None:
            value["svg"] = _to_rust_svg_options(value["svg"])
        if "output_format" in value and value["output_format"] is not None and not isinstance(value["output_format"], _rust.ImageOutputFormat):
            value["output_format"] = _rust.ImageOutputFormat(value["output_format"])
        value = ImageExtractionConfig(**value)
    if value is None:
        return None
    value = cast(ImageExtractionConfig, value)
    return _rust.ImageExtractionConfig(
        extract_images=value.extract_images,
        target_dpi=value.target_dpi,
        max_image_dimension=value.max_image_dimension,
        inject_placeholders=value.inject_placeholders,
        auto_adjust_dpi=value.auto_adjust_dpi,
        min_dpi=value.min_dpi,
        max_dpi=value.max_dpi,
        max_images_per_page=value.max_images_per_page,
        classify=value.classify,
        include_page_rasters=value.include_page_rasters,
        run_ocr_on_images=value.run_ocr_on_images,
        ocr_text_only=value.ocr_text_only,
        append_ocr_text=value.append_ocr_text,
**({"output_format": value.output_format if isinstance(value.output_format, _rust.ImageOutputFormat) else _rust.ImageOutputFormat(value.output_format)} if value.output_format is not None else {}),
        svg=_to_rust_svg_options(value.svg),
        include_data_base64=value.include_data_base64,
    )


@overload
def _to_rust_hierarchy_config(value: None) -> None: ...


@overload
def _to_rust_hierarchy_config(value: HierarchyConfig | dict[str, Any] | str) -> _rust.HierarchyConfig: ...
def _to_rust_hierarchy_config(value: HierarchyConfig | dict[str, Any] | str | None) -> _rust.HierarchyConfig | None:
    """Convert Python HierarchyConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = HierarchyConfig(**value)
    if value is None:
        return None
    value = cast(HierarchyConfig, value)
    return _rust.HierarchyConfig(
        enabled=value.enabled,
        k_clusters=value.k_clusters,
        include_bbox=value.include_bbox,
        ocr_coverage_threshold=value.ocr_coverage_threshold,
    )


@overload
def _to_rust_pdf_config(value: None) -> None: ...


@overload
def _to_rust_pdf_config(value: PdfConfig | dict[str, Any] | str) -> _rust.PdfConfig: ...
def _to_rust_pdf_config(value: PdfConfig | dict[str, Any] | str | None) -> _rust.PdfConfig | None:
    """Convert Python PdfConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "hierarchy" in value and value["hierarchy"] is not None:
            value["hierarchy"] = _to_rust_hierarchy_config(value["hierarchy"])
        value = PdfConfig(**value)
    if value is None:
        return None
    value = cast(PdfConfig, value)
    return _rust.PdfConfig(
        extract_images=value.extract_images,
        extract_tables=value.extract_tables,
        passwords=value.passwords,
        extract_metadata=value.extract_metadata,
        hierarchy=_to_rust_hierarchy_config(value.hierarchy),
        extract_annotations=value.extract_annotations,
        top_margin_fraction=value.top_margin_fraction,
        bottom_margin_fraction=value.bottom_margin_fraction,
        allow_single_column_tables=value.allow_single_column_tables,
        ocr_inline_images=value.ocr_inline_images,
        extract_form_fields=value.extract_form_fields,
        reading_order=value.reading_order,
    )


@overload
def _to_rust_token_reduction_options(value: None) -> None: ...


@overload
def _to_rust_token_reduction_options(value: TokenReductionOptions | dict[str, Any] | str) -> _rust.TokenReductionOptions: ...
def _to_rust_token_reduction_options(
    value: TokenReductionOptions | dict[str, Any] | str | None,
) -> _rust.TokenReductionOptions | None:
    """Convert Python TokenReductionOptions to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = TokenReductionOptions(**value)
    if value is None:
        return None
    value = cast(TokenReductionOptions, value)
    return _rust.TokenReductionOptions(
        mode=value.mode,
        preserve_important_words=value.preserve_important_words,
    )


@overload
def _to_rust_language_detection_config(value: None) -> None: ...


@overload
def _to_rust_language_detection_config(value: LanguageDetectionConfig | dict[str, Any] | str) -> _rust.LanguageDetectionConfig: ...
def _to_rust_language_detection_config(
    value: LanguageDetectionConfig | dict[str, Any] | str | None,
) -> _rust.LanguageDetectionConfig | None:
    """Convert Python LanguageDetectionConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = LanguageDetectionConfig(**value)
    if value is None:
        return None
    value = cast(LanguageDetectionConfig, value)
    return _rust.LanguageDetectionConfig(
        enabled=value.enabled,
        min_confidence=value.min_confidence,
        detect_multiple=value.detect_multiple,
    )


@overload
def _to_rust_page_config(value: None) -> None: ...


@overload
def _to_rust_page_config(value: PageConfig | dict[str, Any] | str) -> _rust.PageConfig: ...
def _to_rust_page_config(value: PageConfig | dict[str, Any] | str | None) -> _rust.PageConfig | None:
    """Convert Python PageConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = PageConfig(**value)
    if value is None:
        return None
    value = cast(PageConfig, value)
    return _rust.PageConfig(
        extract_pages=value.extract_pages,
        insert_page_markers=value.insert_page_markers,
        marker_format=value.marker_format,
    )


@overload
def _to_rust_yake_params(value: None) -> None: ...


@overload
def _to_rust_yake_params(value: YakeParams | dict[str, Any] | str) -> _rust.YakeParams: ...
def _to_rust_yake_params(value: YakeParams | dict[str, Any] | str | None) -> _rust.YakeParams | None:
    """Convert Python YakeParams to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = YakeParams(**value)
    if value is None:
        return None
    value = cast(YakeParams, value)
    return _rust.YakeParams(
        window_size=value.window_size,
    )


@overload
def _to_rust_rake_params(value: None) -> None: ...


@overload
def _to_rust_rake_params(value: RakeParams | dict[str, Any] | str) -> _rust.RakeParams: ...
def _to_rust_rake_params(value: RakeParams | dict[str, Any] | str | None) -> _rust.RakeParams | None:
    """Convert Python RakeParams to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = RakeParams(**value)
    if value is None:
        return None
    value = cast(RakeParams, value)
    return _rust.RakeParams(
        min_word_length=value.min_word_length,
        max_words_per_phrase=value.max_words_per_phrase,
    )


@overload
def _to_rust_keyword_config(value: None) -> None: ...


@overload
def _to_rust_keyword_config(value: KeywordConfig | dict[str, Any] | str) -> _rust.KeywordConfig: ...
def _to_rust_keyword_config(value: KeywordConfig | dict[str, Any] | str | None) -> _rust.KeywordConfig | None:
    """Convert Python KeywordConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "algorithm" in value and value["algorithm"] is not None:
            value["algorithm"] = _coerce_enum(_rust.KeywordAlgorithm, value["algorithm"])
        if "yake_params" in value and value["yake_params"] is not None:
            value["yake_params"] = _to_rust_yake_params(value["yake_params"])
        if "rake_params" in value and value["rake_params"] is not None:
            value["rake_params"] = _to_rust_rake_params(value["rake_params"])
        value = KeywordConfig(**value)
    if value is None:
        return None
    value = cast(KeywordConfig, value)
    return _rust.KeywordConfig(
        **({"algorithm": _coerce_enum(_rust.KeywordAlgorithm, value.algorithm)} if value.algorithm is not None else {}),
        max_keywords=value.max_keywords,
        min_score=value.min_score,
        language=value.language,
        yake_params=_to_rust_yake_params(value.yake_params),
        rake_params=_to_rust_rake_params(value.rake_params),
    )


@overload
def _to_rust_post_processor_config(value: None) -> None: ...


@overload
def _to_rust_post_processor_config(value: PostProcessorConfig | dict[str, Any] | str) -> _rust.PostProcessorConfig: ...
def _to_rust_post_processor_config(
    value: PostProcessorConfig | dict[str, Any] | str | None,
) -> _rust.PostProcessorConfig | None:
    """Convert Python PostProcessorConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = PostProcessorConfig(**value)
    if value is None:
        return None
    value = cast(PostProcessorConfig, value)
    return _rust.PostProcessorConfig(
        enabled=value.enabled,
        enabled_processors=value.enabled_processors,
        disabled_processors=value.disabled_processors,
        enabled_set=value.enabled_set,
        disabled_set=value.disabled_set,
    )


@overload
def _to_rust_layout_detection_config(value: None) -> None: ...


@overload
def _to_rust_layout_detection_config(value: LayoutDetectionConfig | dict[str, Any] | str) -> _rust.LayoutDetectionConfig: ...
def _to_rust_layout_detection_config(
    value: LayoutDetectionConfig | dict[str, Any] | str | None,
) -> _rust.LayoutDetectionConfig | None:
    """Convert Python LayoutDetectionConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "table_model" in value and value["table_model"] is not None:
            value["table_model"] = _coerce_enum(_rust.TableModel, value["table_model"])
        if "acceleration" in value and value["acceleration"] is not None:
            value["acceleration"] = _to_rust_acceleration_config(value["acceleration"])
        value = LayoutDetectionConfig(**value)
    if value is None:
        return None
    value = cast(LayoutDetectionConfig, value)
    return _rust.LayoutDetectionConfig(
        confidence_threshold=value.confidence_threshold,
        apply_heuristics=value.apply_heuristics,
        **({"table_model": _coerce_enum(_rust.TableModel, value.table_model)} if value.table_model is not None else {}),
        acceleration=_to_rust_acceleration_config(value.acceleration),
        enable_chart_understanding=value.enable_chart_understanding,
    )


@overload
def _to_rust_transcription_config(value: None) -> None: ...


@overload
def _to_rust_transcription_config(value: TranscriptionConfig | dict[str, Any] | str) -> _rust.TranscriptionConfig: ...
def _to_rust_transcription_config(
    value: TranscriptionConfig | dict[str, Any] | str | None,
) -> _rust.TranscriptionConfig | None:
    """Convert Python TranscriptionConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "model" in value and value["model"] is not None:
            value["model"] = _coerce_enum(_rust.WhisperModel, value["model"])
        value = TranscriptionConfig(**value)
    if value is None:
        return None
    value = cast(TranscriptionConfig, value)
    return _rust.TranscriptionConfig(
        enabled=value.enabled,
        **({"model": _coerce_enum(_rust.WhisperModel, value.model)} if value.model is not None else {}),
        language=value.language,
        timestamps=value.timestamps,
        max_duration_ms=value.max_duration_ms,
        max_bytes=value.max_bytes,
        timeout_ms=value.timeout_ms,
        model_cache_dir=value.model_cache_dir,
        allow_network=value.allow_network,
        verify_hash=value.verify_hash,
    )


@overload
def _to_rust_tree_sitter_process_config(value: None) -> None: ...


@overload
def _to_rust_tree_sitter_process_config(value: TreeSitterProcessConfig | dict[str, Any] | str) -> _rust.TreeSitterProcessConfig: ...
def _to_rust_tree_sitter_process_config(
    value: TreeSitterProcessConfig | dict[str, Any] | str | None,
) -> _rust.TreeSitterProcessConfig | None:
    """Convert Python TreeSitterProcessConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "content_mode" in value and value["content_mode"] is not None:
            value["content_mode"] = _coerce_enum(_rust.CodeContentMode, value["content_mode"])
        value = TreeSitterProcessConfig(**value)
    if value is None:
        return None
    value = cast(TreeSitterProcessConfig, value)
    return _rust.TreeSitterProcessConfig(
        structure=value.structure,
        imports=value.imports,
        exports=value.exports,
        comments=value.comments,
        docstrings=value.docstrings,
        symbols=value.symbols,
        diagnostics=value.diagnostics,
        chunk_max_size=value.chunk_max_size,
        **({"content_mode": _coerce_enum(_rust.CodeContentMode, value.content_mode)} if value.content_mode is not None else {}),
    )


@overload
def _to_rust_tree_sitter_config(value: None) -> None: ...


@overload
def _to_rust_tree_sitter_config(value: TreeSitterConfig | dict[str, Any] | str) -> _rust.TreeSitterConfig: ...
def _to_rust_tree_sitter_config(value: TreeSitterConfig | dict[str, Any] | str | None) -> _rust.TreeSitterConfig | None:
    """Convert Python TreeSitterConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "process" in value and value["process"] is not None:
            value["process"] = _to_rust_tree_sitter_process_config(value["process"])
        value = TreeSitterConfig(**value)
    if value is None:
        return None
    value = cast(TreeSitterConfig, value)
    return _rust.TreeSitterConfig(
        enabled=value.enabled,
        cache_dir=value.cache_dir,
        languages=value.languages,
        groups=value.groups,
        process=_to_rust_tree_sitter_process_config(value.process),
    )


def _coerce_dict_file_extraction_config(value: dict[str, Any]) -> FileExtractionConfig:
    """Coerce a dict into FileExtractionConfig, converting nested types in-place."""
    _struct_coercions = {
        "ocr": _to_rust_ocr_config,
        "chunking": _to_rust_chunking_config,
        "content_filter": _to_rust_content_filter_config,
        "images": _to_rust_image_extraction_config,
        "pdf_options": _to_rust_pdf_config,
        "token_reduction": _to_rust_token_reduction_options,
        "language_detection": _to_rust_language_detection_config,
        "pages": _to_rust_page_config,
        "keywords": _to_rust_keyword_config,
        "postprocessor": _to_rust_post_processor_config,
        "layout": _to_rust_layout_detection_config,
        "transcription": _to_rust_transcription_config,
        "tree_sitter": _to_rust_tree_sitter_config,
    }
    for _k, _fn in _struct_coercions.items():
        if _k in value and value[_k] is not None:
            value[_k] = _fn(value[_k])
    _enum_coercions = {
        "result_format": _rust.ResultFormat,
    }
    for _k, _cls in _enum_coercions.items():
        if _k in value and value[_k] is not None:
            value[_k] = _coerce_enum(_cls, value[_k])
    _data_enum_coercions = {
        "output_format": _rust.OutputFormat,
    }
    for _k, _cls in _data_enum_coercions.items():
        if _k in value and value[_k] is not None and not isinstance(value[_k], _cls):
            value[_k] = _cls(value[_k])
    return FileExtractionConfig(**value)
@overload
def _to_rust_file_extraction_config(value: None) -> None: ...


@overload
def _to_rust_file_extraction_config(value: FileExtractionConfig | dict[str, Any] | str) -> _rust.FileExtractionConfig: ...
def _to_rust_file_extraction_config(
    value: FileExtractionConfig | dict[str, Any] | str | None,
) -> _rust.FileExtractionConfig | None:
    """Convert Python FileExtractionConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = _coerce_dict_file_extraction_config(value)
    if value is None:
        return None
    value = cast(FileExtractionConfig, value)
    return _rust.FileExtractionConfig(
        enable_quality_processing=value.enable_quality_processing,
        ocr=_to_rust_ocr_config(value.ocr),
        force_ocr=value.force_ocr,
        force_ocr_pages=value.force_ocr_pages,
        disable_ocr=value.disable_ocr,
        chunking=_to_rust_chunking_config(value.chunking),
        content_filter=_to_rust_content_filter_config(value.content_filter),
        images=_to_rust_image_extraction_config(value.images),
        pdf_options=_to_rust_pdf_config(value.pdf_options),
        token_reduction=_to_rust_token_reduction_options(value.token_reduction),
        language_detection=_to_rust_language_detection_config(value.language_detection),
        pages=_to_rust_page_config(value.pages),
        keywords=_to_rust_keyword_config(value.keywords),
        postprocessor=_to_rust_post_processor_config(value.postprocessor),
        result_format=_coerce_enum(_rust.ResultFormat, value.result_format),
        output_format=(value.output_format if isinstance(value.output_format, _rust.OutputFormat) else _rust.OutputFormat(value.output_format)) if value.output_format is not None else None,
        include_document_structure=value.include_document_structure,
        layout=_to_rust_layout_detection_config(value.layout),
        transcription=_to_rust_transcription_config(value.transcription),
        timeout_secs=value.timeout_secs,
        tree_sitter=_to_rust_tree_sitter_config(value.tree_sitter),
        structured_extraction=value.structured_extraction,
    )


@overload
def _to_rust_extract_input(value: None) -> None: ...


@overload
def _to_rust_extract_input(value: ExtractInput | dict[str, Any] | str) -> _rust.ExtractInput: ...
def _to_rust_extract_input(value: ExtractInput | dict[str, Any] | str | None) -> _rust.ExtractInput | None:
    """Convert Python ExtractInput to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "kind" in value and value["kind"] is not None:
            value["kind"] = _coerce_enum(_rust.ExtractInputKind, value["kind"])
        if "config" in value and value["config"] is not None:
            value["config"] = _to_rust_file_extraction_config(value["config"])
        value = ExtractInput(**value)
    if value is None:
        return None
    value = cast(ExtractInput, value)
    return _rust.ExtractInput(
        kind=_coerce_enum(_rust.ExtractInputKind, value.kind),
        bytes=value.bytes,
        uri=value.uri,
        mime_type=value.mime_type,
        filename=value.filename,
        config=_to_rust_file_extraction_config(value.config),
    )


@overload
def _to_rust_html_output_config(value: None) -> None: ...


@overload
def _to_rust_html_output_config(value: HtmlOutputConfig | dict[str, Any] | str) -> _rust.HtmlOutputConfig: ...
def _to_rust_html_output_config(value: HtmlOutputConfig | dict[str, Any] | str | None) -> _rust.HtmlOutputConfig | None:
    """Convert Python HtmlOutputConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "theme" in value and value["theme"] is not None:
            value["theme"] = _coerce_enum(_rust.HtmlTheme, value["theme"])
        value = HtmlOutputConfig(**value)
    if value is None:
        return None
    value = cast(HtmlOutputConfig, value)
    return _rust.HtmlOutputConfig(
        css=value.css,
        css_file=value.css_file,
        **({"theme": _coerce_enum(_rust.HtmlTheme, value.theme)} if value.theme is not None else {}),
        class_prefix=value.class_prefix,
        embed_css=value.embed_css,
    )


@overload
def _to_rust_security_limits(value: None) -> None: ...


@overload
def _to_rust_security_limits(value: SecurityLimits | dict[str, Any] | str) -> _rust.SecurityLimits: ...
def _to_rust_security_limits(value: SecurityLimits | dict[str, Any] | str | None) -> _rust.SecurityLimits | None:
    """Convert Python SecurityLimits to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = SecurityLimits(**value)
    if value is None:
        return None
    value = cast(SecurityLimits, value)
    return _rust.SecurityLimits(
        max_archive_size=value.max_archive_size,
        max_compression_ratio=value.max_compression_ratio,
        max_files_in_archive=value.max_files_in_archive,
        max_nesting_depth=value.max_nesting_depth,
        max_entity_length=value.max_entity_length,
        max_content_size=value.max_content_size,
        max_iterations=value.max_iterations,
        max_xml_depth=value.max_xml_depth,
        max_table_cells=value.max_table_cells,
    )


@overload
def _to_rust_email_config(value: None) -> None: ...


@overload
def _to_rust_email_config(value: EmailConfig | dict[str, Any] | str) -> _rust.EmailConfig: ...
def _to_rust_email_config(value: EmailConfig | dict[str, Any] | str | None) -> _rust.EmailConfig | None:
    """Convert Python EmailConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = EmailConfig(**value)
    if value is None:
        return None
    value = cast(EmailConfig, value)
    return _rust.EmailConfig(
        msg_fallback_codepage=value.msg_fallback_codepage,
    )


@overload
def _to_rust_url_extraction_config(value: None) -> None: ...


@overload
def _to_rust_url_extraction_config(value: UrlExtractionConfig | dict[str, Any] | str) -> _rust.UrlExtractionConfig: ...
def _to_rust_url_extraction_config(
    value: UrlExtractionConfig | dict[str, Any] | str | None,
) -> _rust.UrlExtractionConfig | None:
    """Convert Python UrlExtractionConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "mode" in value and value["mode"] is not None:
            value["mode"] = _coerce_enum(_rust.UrlExtractionMode, value["mode"])
        value = UrlExtractionConfig(**value)
    if value is None:
        return None
    value = cast(UrlExtractionConfig, value)
    return _rust.UrlExtractionConfig(
        mode=_coerce_enum(_rust.UrlExtractionMode, value.mode),
        document_url_pattern=value.document_url_pattern,
        max_document_urls_per_result=value.max_document_urls_per_result,
        max_total_urls=value.max_total_urls,
        allow_local_file_inputs=value.allow_local_file_inputs,
        allow_file_uris=value.allow_file_uris,
    )


@overload
def _to_rust_ner_config(value: None) -> None: ...


@overload
def _to_rust_ner_config(value: NerConfig | dict[str, Any] | str) -> _rust.NerConfig: ...
def _to_rust_ner_config(value: NerConfig | dict[str, Any] | str | None) -> _rust.NerConfig | None:
    """Convert Python NerConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "backend" in value and value["backend"] is not None:
            value["backend"] = _coerce_enum(_rust.NerBackendKind, value["backend"])
        if "llm" in value and value["llm"] is not None:
            value["llm"] = _to_rust_llm_config(value["llm"])
        value = NerConfig(**value)
    if value is None:
        return None
    value = cast(NerConfig, value)
    return _rust.NerConfig(
        **({"backend": _coerce_enum(_rust.NerBackendKind, value.backend)} if value.backend is not None else {}),
        categories=[_rust.EntityCategory(v) for v in value.categories],
        model=value.model,
        llm=_to_rust_llm_config(value.llm),
        custom_labels=value.custom_labels,
    )


@overload
def _to_rust_redaction_config(value: None) -> None: ...


@overload
def _to_rust_redaction_config(value: RedactionConfig | dict[str, Any] | str) -> _rust.RedactionConfig: ...
def _to_rust_redaction_config(value: RedactionConfig | dict[str, Any] | str | None) -> _rust.RedactionConfig | None:
    """Convert Python RedactionConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "strategy" in value and value["strategy"] is not None:
            value["strategy"] = _coerce_enum(_rust.RedactionStrategy, value["strategy"])
        if "ner" in value and value["ner"] is not None:
            value["ner"] = _to_rust_ner_config(value["ner"])
        value = RedactionConfig(**value)
    if value is None:
        return None
    value = cast(RedactionConfig, value)
    return _rust.RedactionConfig(
        categories=[_rust.PiiCategory(v) for v in value.categories],
        **({"strategy": _coerce_enum(_rust.RedactionStrategy, value.strategy)} if value.strategy is not None else {}),
        ner=_to_rust_ner_config(value.ner),
        preserve_offsets=value.preserve_offsets,
        custom_terms=value.custom_terms,
        custom_patterns=value.custom_patterns,
    )


@overload
def _to_rust_summarization_config(value: None) -> None: ...


@overload
def _to_rust_summarization_config(value: SummarizationConfig | dict[str, Any] | str) -> _rust.SummarizationConfig: ...
def _to_rust_summarization_config(
    value: SummarizationConfig | dict[str, Any] | str | None,
) -> _rust.SummarizationConfig | None:
    """Convert Python SummarizationConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "strategy" in value and value["strategy"] is not None:
            value["strategy"] = _coerce_enum(_rust.SummaryStrategy, value["strategy"])
        if "llm" in value and value["llm"] is not None:
            value["llm"] = _to_rust_llm_config(value["llm"])
        value = SummarizationConfig(**value)
    if value is None:
        return None
    value = cast(SummarizationConfig, value)
    return _rust.SummarizationConfig(
        **({"strategy": _coerce_enum(_rust.SummaryStrategy, value.strategy)} if value.strategy is not None else {}),
        max_tokens=value.max_tokens,
        llm=_to_rust_llm_config(value.llm),
    )


def _coerce_dict_extraction_config(value: dict[str, Any]) -> ExtractionConfig:
    """Coerce a dict into ExtractionConfig, converting nested types in-place."""
    _struct_coercions = {
        "ocr": _to_rust_ocr_config,
        "chunking": _to_rust_chunking_config,
        "content_filter": _to_rust_content_filter_config,
        "images": _to_rust_image_extraction_config,
        "pdf_options": _to_rust_pdf_config,
        "token_reduction": _to_rust_token_reduction_options,
        "language_detection": _to_rust_language_detection_config,
        "pages": _to_rust_page_config,
        "keywords": _to_rust_keyword_config,
        "postprocessor": _to_rust_post_processor_config,
        "html_output": _to_rust_html_output_config,
        "security_limits": _to_rust_security_limits,
        "layout": _to_rust_layout_detection_config,
        "transcription": _to_rust_transcription_config,
        "acceleration": _to_rust_acceleration_config,
        "email": _to_rust_email_config,
        "url": _to_rust_url_extraction_config,
        "tree_sitter": _to_rust_tree_sitter_config,
        "ner": _to_rust_ner_config,
        "redaction": _to_rust_redaction_config,
        "summarization": _to_rust_summarization_config,
    }
    for _k, _fn in _struct_coercions.items():
        if _k in value and value[_k] is not None:
            value[_k] = _fn(value[_k])
    _enum_coercions = {
        "result_format": _rust.ResultFormat,
    }
    for _k, _cls in _enum_coercions.items():
        if _k in value and value[_k] is not None:
            value[_k] = _coerce_enum(_cls, value[_k])
    _data_enum_coercions = {
        "output_format": _rust.OutputFormat,
    }
    for _k, _cls in _data_enum_coercions.items():
        if _k in value and value[_k] is not None and not isinstance(value[_k], _cls):
            value[_k] = _cls(value[_k])
    return ExtractionConfig(**value)
@overload
def _to_rust_extraction_config(value: None) -> None: ...


@overload
def _to_rust_extraction_config(value: ExtractionConfig | dict[str, Any] | str) -> _rust.ExtractionConfig: ...
def _to_rust_extraction_config(value: ExtractionConfig | dict[str, Any] | str | None) -> _rust.ExtractionConfig | None:
    """Convert Python ExtractionConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = _coerce_dict_extraction_config(value)
    if value is None:
        return None
    value = cast(dict[str, Any], value)
    return _rust.ExtractionConfig(**value)


@overload
def _to_rust_metadata(value: None) -> None: ...


@overload
def _to_rust_metadata(value: Metadata | dict[str, Any] | str) -> _rust.Metadata: ...
def _to_rust_metadata(value: Metadata | dict[str, Any] | str | None) -> _rust.Metadata | None:
    """Convert Python Metadata to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "format" in value and value["format"] is not None and not isinstance(value["format"], _rust.FormatMetadata):
            value["format"] = _rust.FormatMetadata(value["format"])
        value = Metadata(**value)
    if value is None:
        return None
    value = cast(Metadata, value)
    return _rust.Metadata(
        title=value.title,
        subject=value.subject,
        authors=value.authors,
        keywords=value.keywords,
        language=value.language,
        created_at=value.created_at,
        modified_at=value.modified_at,
        created_by=value.created_by,
        modified_by=value.modified_by,
        pages=value.pages,
        format=(value.format if isinstance(value.format, _rust.FormatMetadata) else _rust.FormatMetadata(value.format)) if value.format is not None else None,
        image_preprocessing=value.image_preprocessing,
        json_schema=value.json_schema,
        error=value.error,
        extraction_duration_ms=value.extraction_duration_ms,
        category=value.category,
        tags=value.tags,
        document_version=value.document_version,
        abstract_text=value.abstract_text,
        output_format=value.output_format,
        ocr_used=value.ocr_used,
        additional=value.additional,
    )


@overload
def _to_rust_bounding_box(value: None) -> None: ...


@overload
def _to_rust_bounding_box(value: BoundingBox | dict[str, Any] | str) -> _rust.BoundingBox: ...
def _to_rust_bounding_box(value: BoundingBox | dict[str, Any] | str | None) -> _rust.BoundingBox | None:
    """Convert Python BoundingBox to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = BoundingBox(**value)
    if value is None:
        return None
    value = cast(BoundingBox, value)
    return _rust.BoundingBox(
        x0=value.x0,
        y0=value.y0,
        x1=value.x1,
        y1=value.y1,
    )


@overload
def _to_rust_table(value: None) -> None: ...


@overload
def _to_rust_table(value: Table | dict[str, Any] | str) -> _rust.Table: ...
def _to_rust_table(value: Table | dict[str, Any] | str | None) -> _rust.Table | None:
    """Convert Python Table to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "bounding_box" in value and value["bounding_box"] is not None:
            value["bounding_box"] = _to_rust_bounding_box(value["bounding_box"])
        value = Table(**value)
    if value is None:
        return None
    value = cast(Table, value)
    return _rust.Table(
        cells=value.cells,
        markdown=value.markdown,
        page_number=value.page_number,
        bounding_box=_to_rust_bounding_box(value.bounding_box),
    )


@overload
def _to_rust_extracted_image(value: None) -> None: ...


@overload
def _to_rust_extracted_image(value: ExtractedImage | dict[str, Any] | str) -> _rust.ExtractedImage: ...
def _to_rust_extracted_image(value: ExtractedImage | dict[str, Any] | str | None) -> _rust.ExtractedImage | None:
    """Convert Python ExtractedImage to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "image_kind" in value and value["image_kind"] is not None:
            value["image_kind"] = _coerce_enum(_rust.ImageKind, value["image_kind"])
        if "ocr_result" in value and value["ocr_result"] is not None:
            value["ocr_result"] = _to_rust_extraction_result(value["ocr_result"])
        if "bounding_box" in value and value["bounding_box"] is not None:
            value["bounding_box"] = _to_rust_bounding_box(value["bounding_box"])
        value = ExtractedImage(**value)
    if value is None:
        return None
    value = cast(ExtractedImage, value)
    return _rust.ExtractedImage(
        data=value.data,
        format=value.format,
        image_index=value.image_index,
        page_number=value.page_number,
        width=value.width,
        height=value.height,
        colorspace=value.colorspace,
        bits_per_component=value.bits_per_component,
        is_mask=value.is_mask,
        description=value.description,
        ocr_result=_to_rust_extraction_result(value.ocr_result),
        bounding_box=_to_rust_bounding_box(value.bounding_box),
        source_path=value.source_path,
        image_kind=_coerce_enum(_rust.ImageKind, value.image_kind),
        kind_confidence=value.kind_confidence,
        cluster_id=value.cluster_id,
        caption=value.caption,
        qr_codes=value.qr_codes,
        data_base64=value.data_base64,
    )


@overload
def _to_rust_ocr_confidence(value: None) -> None: ...


@overload
def _to_rust_ocr_confidence(value: OcrConfidence | dict[str, Any] | str) -> _rust.OcrConfidence: ...
def _to_rust_ocr_confidence(value: OcrConfidence | dict[str, Any] | str | None) -> _rust.OcrConfidence | None:
    """Convert Python OcrConfidence to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = OcrConfidence(**value)
    if value is None:
        return None
    value = cast(OcrConfidence, value)
    return _rust.OcrConfidence(
        detection=value.detection,
        recognition=value.recognition,
    )


@overload
def _to_rust_ocr_element(value: None) -> None: ...


@overload
def _to_rust_ocr_element(value: OcrElement | dict[str, Any] | str) -> _rust.OcrElement: ...
def _to_rust_ocr_element(value: OcrElement | dict[str, Any] | str | None) -> _rust.OcrElement | None:
    """Convert Python OcrElement to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "level" in value and value["level"] is not None:
            value["level"] = _coerce_enum(_rust.OcrElementLevel, value["level"])
        if "confidence" in value and value["confidence"] is not None:
            value["confidence"] = _to_rust_ocr_confidence(value["confidence"])
        if "geometry" in value and value["geometry"] is not None and not isinstance(value["geometry"], _rust.OcrBoundingGeometry):
            value["geometry"] = _rust.OcrBoundingGeometry(value["geometry"])
        value = OcrElement(**value)
    if value is None:
        return None
    value = cast(OcrElement, value)
    return _rust.OcrElement(
        text=value.text,
        geometry=value.geometry if isinstance(value.geometry, _rust.OcrBoundingGeometry) else _rust.OcrBoundingGeometry(value.geometry),
        confidence=_to_rust_ocr_confidence(value.confidence),
        **({"level": _coerce_enum(_rust.OcrElementLevel, value.level)} if value.level is not None else {}),
        rotation=value.rotation,
        page_number=value.page_number,
        parent_id=value.parent_id,
        backend_metadata=value.backend_metadata,
    )


@overload
def _to_rust_document_structure(value: None) -> None: ...


@overload
def _to_rust_document_structure(value: DocumentStructure | dict[str, Any] | str) -> _rust.DocumentStructure: ...
def _to_rust_document_structure(value: DocumentStructure | dict[str, Any] | str | None) -> _rust.DocumentStructure | None:
    """Convert Python DocumentStructure to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = DocumentStructure(**value)
    if value is None:
        return None
    value = cast(DocumentStructure, value)
    return _rust.DocumentStructure(
        nodes=value.nodes,
        source_format=value.source_format,
        relationships=value.relationships,
        node_types=value.node_types,
    )


@overload
def _to_rust_llm_usage(value: None) -> None: ...


@overload
def _to_rust_llm_usage(value: LlmUsage | dict[str, Any] | str) -> _rust.LlmUsage: ...
def _to_rust_llm_usage(value: LlmUsage | dict[str, Any] | str | None) -> _rust.LlmUsage | None:
    """Convert Python LlmUsage to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = LlmUsage(**value)
    if value is None:
        return None
    value = cast(LlmUsage, value)
    return _rust.LlmUsage(
        model=value.model,
        source=value.source,
        input_tokens=value.input_tokens,
        output_tokens=value.output_tokens,
        total_tokens=value.total_tokens,
        estimated_cost=value.estimated_cost,
        finish_reason=value.finish_reason,
    )


@overload
def _to_rust_extraction_result(value: None) -> None: ...


@overload
def _to_rust_extraction_result(value: ExtractionResult | dict[str, Any] | str) -> _rust.ExtractionResult: ...
def _to_rust_extraction_result(value: ExtractionResult | dict[str, Any] | str | None) -> _rust.ExtractionResult | None:
    """Convert Python ExtractionResult to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "extraction_method" in value and value["extraction_method"] is not None:
            value["extraction_method"] = _coerce_enum(_rust.ExtractionMethod, value["extraction_method"])
        if "metadata" in value and value["metadata"] is not None:
            value["metadata"] = _to_rust_metadata(value["metadata"])
        if "document" in value and value["document"] is not None:
            value["document"] = _to_rust_document_structure(value["document"])
        value = ExtractionResult(**value)
    if value is None:
        return None
    value = cast(ExtractionResult, value)
    return _rust.ExtractionResult(
        content=value.content,
        mime_type=value.mime_type,
        metadata=_to_rust_metadata(value.metadata),
        extraction_method=_coerce_enum(_rust.ExtractionMethod, value.extraction_method),
        tables=value.tables,
        detected_languages=value.detected_languages,
        chunks=value.chunks,
        images=value.images,
        pages=value.pages,
        elements=value.elements,
        djot_content=value.djot_content,
        ocr_elements=value.ocr_elements,
        document=_to_rust_document_structure(value.document),
        extracted_keywords=value.extracted_keywords,
        quality_score=value.quality_score,
        processing_warnings=value.processing_warnings,
        annotations=value.annotations,
        children=value.children,
        uris=value.uris,
        revisions=value.revisions,
        structured_output=value.structured_output,
        code_intelligence=value.code_intelligence,
        llm_usage=value.llm_usage,
        entities=value.entities,
        summary=value.summary,
        extraction_confidence=value.extraction_confidence,
        translation=value.translation,
        page_classifications=value.page_classifications,
        redaction_report=value.redaction_report,
        formulas=value.formulas,
        form_fields=value.form_fields,
        formatted_content=value.formatted_content,
    )


@overload
def _to_rust_diff_options(value: None) -> None: ...


@overload
def _to_rust_diff_options(value: DiffOptions | dict[str, Any] | str) -> _rust.DiffOptions: ...
def _to_rust_diff_options(value: DiffOptions | dict[str, Any] | str | None) -> _rust.DiffOptions | None:
    """Convert Python DiffOptions to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = DiffOptions(**value)
    if value is None:
        return None
    value = cast(DiffOptions, value)
    return _rust.DiffOptions(
        include_metadata=value.include_metadata,
        include_embedded=value.include_embedded,
        max_content_chars=value.max_content_chars,
    )


@overload
def _to_rust_reranker_config(value: None) -> None: ...


@overload
def _to_rust_reranker_config(value: RerankerConfig | dict[str, Any] | str) -> _rust.RerankerConfig: ...
def _to_rust_reranker_config(value: RerankerConfig | dict[str, Any] | str | None) -> _rust.RerankerConfig | None:
    """Convert Python RerankerConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        if "acceleration" in value and value["acceleration"] is not None:
            value["acceleration"] = _to_rust_acceleration_config(value["acceleration"])
        if "model" in value and value["model"] is not None and not isinstance(value["model"], _rust.RerankerModelType):
            value["model"] = _rust.RerankerModelType(value["model"])
        value = RerankerConfig(**value)
    if value is None:
        return None
    value = cast(RerankerConfig, value)
    return _rust.RerankerConfig(
        model=value.model if isinstance(value.model, _rust.RerankerModelType) else _rust.RerankerModelType(value.model),
        top_k=value.top_k,
        batch_size=value.batch_size,
        show_download_progress=value.show_download_progress,
        cache_dir=value.cache_dir,
        acceleration=_to_rust_acceleration_config(value.acceleration),
        max_rerank_duration_secs=value.max_rerank_duration_secs,
    )


@overload
def _to_rust_heuristics_config(value: None) -> None: ...


@overload
def _to_rust_heuristics_config(value: HeuristicsConfig | dict[str, Any] | str) -> _rust.HeuristicsConfig: ...
def _to_rust_heuristics_config(value: HeuristicsConfig | dict[str, Any] | str | None) -> _rust.HeuristicsConfig | None:
    """Convert Python HeuristicsConfig to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = HeuristicsConfig(**value)
    if value is None:
        return None
    value = cast(HeuristicsConfig, value)
    return _rust.HeuristicsConfig(
        enable_pdf_text_heuristics=value.enable_pdf_text_heuristics,
        text_layer_threshold=value.text_layer_threshold,
        file_size_threshold_bytes=value.file_size_threshold_bytes,
        page_count_threshold=value.page_count_threshold,
        target_pages_per_chunk=value.target_pages_per_chunk,
        max_pages_per_chunk=value.max_pages_per_chunk,
        disk_processing_threshold_bytes=value.disk_processing_threshold_bytes,
        min_chars_per_page=value.min_chars_per_page,
        max_xlsx_sheet_count=value.max_xlsx_sheet_count,
        max_xlsx_workbook_cells=value.max_xlsx_workbook_cells,
        max_pptx_embedded_count=value.max_pptx_embedded_count,
    )


@overload
def _to_rust_confidence_weights(value: None) -> None: ...


@overload
def _to_rust_confidence_weights(value: ConfidenceWeights | dict[str, Any] | str) -> _rust.ConfidenceWeights: ...
def _to_rust_confidence_weights(value: ConfidenceWeights | dict[str, Any] | str | None) -> _rust.ConfidenceWeights | None:
    """Convert Python ConfidenceWeights to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = ConfidenceWeights(**value)
    if value is None:
        return None
    value = cast(ConfidenceWeights, value)
    return _rust.ConfidenceWeights(
        text_coverage=value.text_coverage,
        ocr_aggregate=value.ocr_aggregate,
        schema_compliance=value.schema_compliance,
    )


@overload
def _to_rust_multidoc_thresholds(value: None) -> None: ...


@overload
def _to_rust_multidoc_thresholds(value: MultidocThresholds | dict[str, Any] | str) -> _rust.MultidocThresholds: ...
def _to_rust_multidoc_thresholds(
    value: MultidocThresholds | dict[str, Any] | str | None,
) -> _rust.MultidocThresholds | None:
    """Convert Python MultidocThresholds to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = MultidocThresholds(**value)
    if value is None:
        return None
    value = cast(MultidocThresholds, value)
    return _rust.MultidocThresholds(
        density_shift_threshold=value.density_shift_threshold,
        bigram_overlap_min=value.bigram_overlap_min,
    )


@overload
def _to_rust_structured_thresholds(value: None) -> None: ...


@overload
def _to_rust_structured_thresholds(value: StructuredThresholds | dict[str, Any] | str) -> _rust.StructuredThresholds: ...
def _to_rust_structured_thresholds(
    value: StructuredThresholds | dict[str, Any] | str | None,
) -> _rust.StructuredThresholds | None:
    """Convert Python StructuredThresholds to Rust binding type."""
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict):
        value = StructuredThresholds(**value)
    if value is None:
        return None
    value = cast(StructuredThresholds, value)
    return _rust.StructuredThresholds(
        scan_max_coverage=value.scan_max_coverage,
        digital_min_coverage=value.digital_min_coverage,
        docx_text_min_density=value.docx_text_min_density,
        enable_vision_fallback=value.enable_vision_fallback,
    )


async def extract(
    input: ExtractInput | None = None,  # noqa: A002
    config: ExtractionConfig | None = None,
) -> _rust.ExtractionOutput:
    """Extract content from a single bytes or URI input."""
    _rust_input = _to_rust_extract_input(input) if input is not None else _rust.ExtractInput()
    _rust_config = _to_rust_extraction_config(config) if config is not None else _rust.ExtractionConfig()
    return await _rust.extract(input=_rust_input, config=_rust_config)


async def extract_batch(
    inputs: list[ExtractInput],
    config: ExtractionConfig | None = None,
) -> _rust.ExtractionOutput:
    """Extract content from multiple bytes or URI inputs."""
    _rust_inputs = [_to_rust_extract_input(__item) for __item in inputs]

    _rust_config = _to_rust_extraction_config(config) if config is not None else _rust.ExtractionConfig()
    return await _rust.extract_batch(inputs=_rust_inputs, config=_rust_config)


def detect_mime_type_from_bytes(content: bytes) -> str:
    """Detect MIME type from raw file bytes."""
    return _rust.detect_mime_type_from_bytes(content=content)


def get_extensions_for_mime(mime_type: str) -> list[str]:
    """Get file extensions for a given MIME type."""
    return _rust.get_extensions_for_mime(mime_type=mime_type)


def list_supported_formats() -> list[SupportedFormat]:
    """List all supported document formats."""
    return _rust.list_supported_formats()


def detect_qr_codes(image_bytes: bytes, _format_hint: str | None = None) -> list[QrCode]:
    """Detect QR codes in the bytes of an `ExtractedImage`."""
    return _rust.detect_qr_codes(image_bytes=image_bytes, _format_hint=_format_hint)


def clear_embedding_backends() -> None:
    """Clear all embedding backends from the global registry."""
    _rust.clear_embedding_backends()


def list_embedding_backends() -> list[str]:
    """List the names of all registered embedding backends."""
    return _rust.list_embedding_backends()


def list_ocr_backends() -> list[str]:
    """List all registered OCR backends."""
    return _rust.list_ocr_backends()


def clear_ocr_backends() -> None:
    """Clear all OCR backends from the global registry."""
    _rust.clear_ocr_backends()


def register_builtin() -> None:
    """Register every built-in post-processor enabled by the active feature set."""
    _rust.register_builtin()


def list_post_processors() -> list[str]:
    """List all registered post-processor names."""
    return _rust.list_post_processors()


def clear_post_processors() -> None:
    """Remove all registered post-processors."""
    _rust.clear_post_processors()


def list_renderers() -> list[str]:
    """List names of all registered renderers."""
    return _rust.list_renderers()


def clear_renderers() -> None:
    """Clear all renderers from the global registry."""
    _rust.clear_renderers()


def clear_reranker_backends() -> None:
    """Clear all reranker backends from the global registry."""
    _rust.clear_reranker_backends()


def list_reranker_backends() -> list[str]:
    """List the names of all registered reranker backends."""
    return _rust.list_reranker_backends()


def list_validators() -> list[str]:
    """List names of all registered validators."""
    return _rust.list_validators()


def clear_validators() -> None:
    """Remove all registered validators."""
    _rust.clear_validators()


async def classify_pages(
    config: PageClassificationConfig,
    result: ExtractionResult | None = None,
) -> None:
    """Run page classification against an extraction result."""
    _rust_result = _to_rust_extraction_result(result) if result is not None else _rust.ExtractionResult()
    await _rust.classify_pages(config=config, result=_rust_result)


async def classify_text(text: str, config: PageClassificationConfig) -> list[ClassificationLabel]:
    """Classify a single piece of text without requiring an `ExtractionResult`."""
    return await _rust.classify_text(text=text, config=config)


async def classify_document(
    pages: list[str],
    config: PageClassificationConfig,
) -> list[ClassificationLabel]:
    """Classify a single document (as multiple pages or a single text block)."""
    return await _rust.classify_document(pages=pages, config=config)


def download_model(name: str, cache_dir: str | None = None) -> str:
    """Eagerly download a NER model into the xberg cache."""
    return _rust.download_model(name=name, cache_dir=cache_dir)


def default_model_name() -> str:
    """Pinned default NER model identifier."""
    return _rust.default_model_name()


def known_models() -> list[str]:
    """All NER models xberg knows about (used by `--all-ner-models`)."""
    return _rust.known_models()


async def redact(
    result: ExtractionResult | None = None,
    config: RedactionConfig | None = None,
) -> None:
    """Run pattern redaction (and optional NER-driven redaction) over `result` and rewrite every."""
    _rust_result = _to_rust_extraction_result(result) if result is not None else _rust.ExtractionResult()
    _rust_config = _to_rust_redaction_config(config) if config is not None else _rust.RedactionConfig()
    await _rust.redact(result=_rust_result, config=_rust_config)


def find_all(text: str) -> list[PatternMatch]:
    """Find all US Social Security Number spans in `text` (format: NNN-NN-NNNN)."""
    return _rust.find_all(text=text)


def scan_text(text: str, categories: list[PiiCategory]) -> list[PatternMatch]:
    """Scan `text` for every PII category in `categories` and return all matches in source-byte ."""
    _rust_categories = [(_rust.PiiCategory(__item) if not isinstance(__item, _rust.PiiCategory) else __item) for __item in categories]

    return _rust.scan_text(text=text, categories=_rust_categories)


def summarize(text: str, language: str | None = None, max_tokens: int | None = None) -> str | None:
    """Score and return the top-N sentences from `text`, joined in original order."""
    return _rust.summarize(text=text, language=language, max_tokens=max_tokens)


def token_count(text: str) -> int:
    """Count whitespace-separated tokens (used for token-budget bookkeeping by callers)."""
    return _rust.token_count(text=text)


async def translate_result(
    config: TranslationConfig,
    result: ExtractionResult | None = None,
) -> None:
    """Translate the extraction result in place."""
    _rust_result = _to_rust_extraction_result(result) if result is not None else _rust.ExtractionResult()
    await _rust.translate_result(config=config, result=_rust_result)


def find_footnote_anchors(markdown: str) -> list[FootnoteAnchor]:
    """Find all footnote anchor references in markdown text."""
    return _rust.find_footnote_anchors(markdown=markdown)


def parse_footnote_definitions(markdown: str) -> list[FootnoteDefinition]:
    """Parse footnote definitions from markdown text."""
    return _rust.parse_footnote_definitions(markdown=markdown)


def find_inference_markers(markdown: str) -> list[int]:
    """Find inference markers in markdown text."""
    return _rust.find_inference_markers(markdown=markdown)


def find_unmarked_claims(markdown: str) -> list[str]:
    """Find unmarked claims in markdown text."""
    return _rust.find_unmarked_claims(markdown=markdown)


def parse_citations(markdown: str) -> list[Citation]:
    """Parse the structured citation block from markdown."""
    return _rust.parse_citations(markdown=markdown)


def verify_excerpt(excerpt: str, source_text: str) -> bool:
    """Verify that an excerpt appears verbatim in source text."""
    return _rust.verify_excerpt(excerpt=excerpt, source_text=source_text)


def chunk_for_rag(text: str, config: ChunkingConfig | None = None) -> _rust.ChunkingResult:
    """Chunk text for RAG retrieval, ensuring every chunk carries a `heading_path`."""
    _rust_config = _to_rust_chunking_config(config) if config is not None else _rust.ChunkingConfig()
    return _rust.chunk_for_rag(text=text, config=_rust_config)


def compare(
    a: ExtractionResult | None = None,
    b: ExtractionResult | None = None,
    opts: DiffOptions | None = None,
) -> ExtractionDiff:
    """Compare two extraction results and return a structured diff."""
    _rust_a = _to_rust_extraction_result(a) if a is not None else _rust.ExtractionResult()
    _rust_b = _to_rust_extraction_result(b) if b is not None else _rust.ExtractionResult()
    _rust_opts = _to_rust_diff_options(opts) if opts is not None else _rust.DiffOptions()
    return _rust.compare(a=_rust_a, b=_rust_b, opts=_rust_opts)


async def extract_region_with_vlm(
    image_bytes: bytes,
    image_mime: str,
    region_kind: RegionKind,
    llm_config: LlmConfig | None = None,
    custom_prompt: str | None = None,
) -> str:
    """Extract content from a pre-cropped image region using a VLM."""
    _rust_llm_config = _to_rust_llm_config(llm_config) if llm_config is not None else _rust.LlmConfig()
    return await _rust.extract_region_with_vlm(image_bytes=image_bytes, image_mime=image_mime, region_kind=region_kind, llm_config=_rust_llm_config, custom_prompt=custom_prompt)


async def rerank_async(
    query: str,
    documents: list[str],
    config: RerankerConfig | None = None,
) -> list[RerankedDocument]:
    """Rerank documents asynchronously."""
    _rust_config = _to_rust_reranker_config(config) if config is not None else _rust.RerankerConfig()
    return await _rust.rerank_async(query=query, documents=documents, config=_rust_config)


def extract_keywords(text: str, config: KeywordConfig | None = None) -> list[Keyword]:
    """Extract keywords from text using the specified algorithm."""
    _rust_config = _to_rust_keyword_config(config) if config is not None else _rust.KeywordConfig()
    return _rust.extract_keywords(text=text, config=_rust_config)


def analyze_document(
    metadata: DocumentMetadata,
    config: HeuristicsConfig | None = None,
    document_bytes: bytes | None = None,
) -> ChunkingDecision:
    """Analyze a document and determine the optimal chunking strategy."""
    _rust_config = _to_rust_heuristics_config(config) if config is not None else _rust.HeuristicsConfig()
    return _rust.analyze_document(metadata=metadata, config=_rust_config, document_bytes=document_bytes)


def analyze_with_user_chunks(
    user_ranges: list[PageRange],
    total_pages: int,
    size_bytes: int,
    config: HeuristicsConfig | None = None,
) -> ChunkingDecision:
    """Analyze a document with user-specified chunk ranges."""
    _rust_config = _to_rust_heuristics_config(config) if config is not None else _rust.HeuristicsConfig()
    return _rust.analyze_with_user_chunks(user_ranges=user_ranges, total_pages=total_pages, size_bytes=size_bytes, config=_rust_config)


def score_confidence(
    signals: ConfidenceSignals,
    weights: ConfidenceWeights | None = None,
) -> _rust.ExtractionConfidence:
    """Score a [`ConfidenceSignals`] triple into an [`ExtractionConfidence`] using the supplied ."""
    _rust_weights = _to_rust_confidence_weights(weights) if weights is not None else _rust.ConfidenceWeights()
    return _rust.score_confidence(signals=signals, weights=_rust_weights)


def check_format_limits(
    mime_type: str,
    sheet_count: int | None = None,
    workbook_cells: int | None = None,
    embedded_count: int | None = None,
    config: HeuristicsConfig | None = None,
) -> str | None:
    """Decision returned for pre-extraction rejection based on XLSX/PPTX-specific resource bound."""
    _rust_config = _to_rust_heuristics_config(config) if config is not None else _rust.HeuristicsConfig()
    return _rust.check_format_limits(mime_type=mime_type, sheet_count=sheet_count, workbook_cells=workbook_cells, embedded_count=embedded_count, config=_rust_config)


def boundaries_from_extraction_result(
    result: ExtractionResult | None = None,
    thresholds: MultidocThresholds | None = None,
) -> list[DocumentBoundary]:
    """Derive document boundaries from an already-produced [`ExtractionResult`](crate::types::Ex."""
    _rust_result = _to_rust_extraction_result(result) if result is not None else _rust.ExtractionResult()
    _rust_thresholds = _to_rust_multidoc_thresholds(thresholds) if thresholds is not None else _rust.MultidocThresholds()
    return _rust.boundaries_from_extraction_result(result=_rust_result, thresholds=_rust_thresholds)


def detect_boundaries(
    input: MultidocInput,  # noqa: A002
    thresholds: MultidocThresholds | None = None,
) -> list[DocumentBoundary]:
    """Detect document boundaries in a multi-document PDF."""
    _rust_thresholds = _to_rust_multidoc_thresholds(thresholds) if thresholds is not None else _rust.MultidocThresholds()
    return _rust.detect_boundaries(input=input, thresholds=_rust_thresholds)


def choose_call_mode(
    input: StructuredInput,  # noqa: A002
    t: StructuredThresholds | None = None,
) -> StructuredCallMode:
    """Decide which call mode best fits this document."""
    _rust_t = _to_rust_structured_thresholds(t) if t is not None else _rust.StructuredThresholds()
    return _rust.choose_call_mode(input=input, t=_rust_t)


def calculate_chunk_plan(
    page_count: int,
    size_bytes: int,
    needs_ocr: bool,
    config: HeuristicsConfig | None = None,
) -> _rust.ChunkPlan:
    """Calculate a chunking plan for a document."""
    _rust_config = _to_rust_heuristics_config(config) if config is not None else _rust.HeuristicsConfig()
    return _rust.calculate_chunk_plan(page_count=page_count, size_bytes=size_bytes, needs_ocr=needs_ocr, config=_rust_config)


def calculate_plan_from_overrides(
    user_chunks: list[PageRange],
    total_pages: int,
    size_bytes: int,
    config: HeuristicsConfig | None = None,
) -> _rust.ChunkPlan:
    """Calculate a chunk plan from user-specified page ranges."""
    _rust_config = _to_rust_heuristics_config(config) if config is not None else _rust.HeuristicsConfig()
    return _rust.calculate_plan_from_overrides(user_chunks=user_chunks, total_pages=total_pages, size_bytes=size_bytes, config=_rust_config)


def fingerprint(raw: bytes) -> str:
    """Stable sha256 fingerprint of `raw`, formatted as `sha256:<hex>`."""
    return _rust.fingerprint(raw=raw)


def resolve(
    preset: Preset,
    custom_schema: dict[str, Any] | None = None,
    context: dict[str, str] | None = None,
) -> _rust.ResolvedPreset:
    """Resolve `(preset, custom_schema_override, context)` into a [`ResolvedPreset`]."""
    return _rust.resolve(preset=preset, custom_schema=custom_schema, context=context)


def extract_structured_json(
    bytes: bytes,  # noqa: A002
    mime: str,
    preset_spec_json: str,
    options_json: str,
) -> str:
    """Extract structured JSON from a document using JSON-encoded preset spec and options."""
    return _rust.extract_structured_json(bytes=bytes, mime=mime, preset_spec_json=preset_spec_json, options_json=options_json)


def split_and_extract_json(
    bytes: bytes,  # noqa: A002
    mime: str,
    preset_spec_json: str,
    options_json: str,
) -> str:
    """Split a multi-document PDF and extract structured JSON from each segment, returning a JSO."""
    return _rust.split_and_extract_json(bytes=bytes, mime=mime, preset_spec_json=preset_spec_json, options_json=options_json)


def render_pdf_page_to_png(
    pdf_bytes: bytes,
    page_index: int,
    dpi: int | None = None,
    password: str | None = None,
) -> bytes:
    """Render a single PDF page to PNG bytes."""
    return _rust.render_pdf_page_to_png(pdf_bytes=pdf_bytes, page_index=page_index, dpi=dpi, password=password)


def pdf_page_count(pdf_bytes: bytes, password: str | None = None) -> int:
    """Count the pages in a PDF without rendering any of them."""
    return _rust.pdf_page_count(pdf_bytes=pdf_bytes, password=password)


async def caption_image(
    image_bytes: bytes,
    llm_config: LlmConfig | None = None,
    custom_prompt: str | None = None,
) -> str:
    """Caption a single image from bytes."""
    _rust_llm_config = _to_rust_llm_config(llm_config) if llm_config is not None else _rust.LlmConfig()
    return await _rust.caption_image(image_bytes=image_bytes, llm_config=_rust_llm_config, custom_prompt=custom_prompt)


async def caption_image_file(
    path: str,
    llm_config: LlmConfig | None = None,
    custom_prompt: str | None = None,
) -> str:
    """Caption a single image from a file path."""
    _rust_llm_config = _to_rust_llm_config(llm_config) if llm_config is not None else _rust.LlmConfig()
    return await _rust.caption_image_file(path=path, llm_config=_rust_llm_config, custom_prompt=custom_prompt)


def detect_mime_type(path: str, check_exists: bool) -> str:
    """Detect the MIME type of a file at the given path."""
    return _rust.detect_mime_type(path=path, check_exists=check_exists)


async def embed_texts_async(
    _texts: list[str],
    _config: EmbeddingConfig | None = None,
) -> list[list[float]]:
    """Embed texts async."""
    _rust__config = _to_rust_embedding_config(_config) if _config is not None else _rust.EmbeddingConfig()
    return await _rust.embed_texts_async(_texts=_texts, _config=_rust__config)


def get_embedding_preset(name: str) -> EmbeddingPreset | None:
    """Get an embedding preset by name."""
    return _rust.get_embedding_preset(name=name)


def list_embedding_presets() -> list[str]:
    """List the names of all available embedding presets."""
    return _rust.list_embedding_presets()


def rerank(
    query: str,
    documents: list[str],
    config: RerankerConfig | None = None,
) -> list[RerankedDocument]:
    """Rerank a list of documents by relevance to a query."""
    _rust_config = _to_rust_reranker_config(config) if config is not None else _rust.RerankerConfig()
    return _rust.rerank(query=query, documents=documents, config=_rust_config)


def get_reranker_preset(name: str) -> RerankerPreset | None:
    """Get a reranker preset by name."""
    return _rust.get_reranker_preset(name=name)


def list_reranker_presets() -> list[str]:
    """List the names of all available reranker presets."""
    return _rust.list_reranker_presets()


def register_ocr_backend(backend: object) -> None:
    """Register a register_ocr_backend backend."""
    return _rust.register_ocr_backend(backend=backend)
def register_post_processor(backend: object) -> None:
    """Register a register_post_processor backend."""
    return _rust.register_post_processor(backend=backend)
def register_validator(backend: object) -> None:
    """Register a register_validator backend."""
    return _rust.register_validator(backend=backend)
def register_embedding_backend(backend: object) -> None:
    """Register a register_embedding_backend backend."""
    return _rust.register_embedding_backend(backend=backend)
def register_renderer(backend: object) -> None:
    """Register a register_renderer backend."""
    return _rust.register_renderer(backend=backend)
def register_reranker_backend(backend: object) -> None:
    """Register a register_reranker_backend backend."""
    return _rust.register_reranker_backend(backend=backend)
def unregister_ocr_backend(name: str) -> None:
    """Unregister the named unregister_ocr_backend backend."""
    return _rust.unregister_ocr_backend(name=name)
def unregister_post_processor(name: str) -> None:
    """Unregister the named unregister_post_processor backend."""
    return _rust.unregister_post_processor(name=name)
def unregister_validator(name: str) -> None:
    """Unregister the named unregister_validator backend."""
    return _rust.unregister_validator(name=name)
def unregister_embedding_backend(name: str) -> None:
    """Unregister the named unregister_embedding_backend backend."""
    return _rust.unregister_embedding_backend(name=name)
def unregister_renderer(name: str) -> None:
    """Unregister the named unregister_renderer backend."""
    return _rust.unregister_renderer(name=name)
def unregister_reranker_backend(name: str) -> None:
    """Unregister the named unregister_reranker_backend backend."""
    return _rust.unregister_reranker_backend(name=name)
