/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:decbacb38ca392b0d8e278b7044150d6b3cb3a645f79702094e10190b73e260b
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface EmbeddingBackendBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  dimensions(): string;
  embed?(texts: string): string;
}

export class EmbeddingBackendAdapter {
  constructor(private bridge: EmbeddingBackendBridge) {}

  async dimensions(): Promise<string> {
    try {
      const result = await this.bridge.dimensions();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async embed(texts: string): Promise<string> {
    try {
      const result = await this.bridge.embed(texts);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
