# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:446748155774867df28fecd60b1f51d93e20d7476cf9f2aad1cd588a1cf0950e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: document_extractor_management

test_that("document_extractors_clear: Clear all document extractors and verify list is empty", {
  result <- jsonlite::fromJSON(extract(config = ExtractionConfig$default()), simplifyVector = FALSE)
  expect_true(TRUE)
})

test_that("extractors_list: List all registered document extractors", {
  result <- jsonlite::fromJSON(extract(config = ExtractionConfig$default()), simplifyVector = FALSE)
  expect_true(TRUE)
})
