// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:16cef683b5e0fc9e6955649fdc36679c86b7b917096a199706dc197d20ab43b3
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The meta-schema itself failed to compile.
/// </summary>
public class BadMetaSchemaException : LoadErrorException
{
    public BadMetaSchemaException(string message) : base(message) { }

    public BadMetaSchemaException(string message, Exception innerException) : base(message, innerException) { }
}
