// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:16cef683b5e0fc9e6955649fdc36679c86b7b917096a199706dc197d20ab43b3
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors that can occur during heuristics analysis.
/// </summary>
public class HeuristicsErrorException : XbergException
{
    public HeuristicsErrorException(string message) : base(message) { }

    public HeuristicsErrorException(string message, Exception innerException) : base(message, innerException) { }
}
