// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:12d5017c2d9e684c93b33fb432e26be857228e6897c01de2278482252751fe25
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : XbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
