// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:446748155774867df28fecd60b1f51d93e20d7476cf9f2aad1cd588a1cf0950e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Combined paths to all models needed for OCR (backward compatibility).
/// </summary>
public sealed record ModelPaths
{
    /// <summary>
    /// Path to the detection model directory.
    /// </summary>
    [JsonPropertyName("det_model")]
    public required string DetModel { get; init; }

    /// <summary>
    /// Path to the classification model directory.
    /// </summary>
    [JsonPropertyName("cls_model")]
    public required string ClsModel { get; init; }

    /// <summary>
    /// Path to the recognition model directory.
    /// </summary>
    [JsonPropertyName("rec_model")]
    public required string RecModel { get; init; }

    /// <summary>
    /// Path to the character dictionary file.
    /// </summary>
    [JsonPropertyName("dict_file")]
    public required string DictFile { get; init; }


    /// <summary>
    /// Parse a <see cref="ModelPaths"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static ModelPaths FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ModelPaths>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse ModelPaths from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse ModelPaths from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
