// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:70f002808d2ae79f0f5135f47c0c282e1162631902e4b57c6829abfd62ec4fb5
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : XbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
