// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:28933e85bc9dc440d3d48a0fa997a78b13df863b6249812908ba7914441b9232
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A catch-all for uncommon errors that do not fit another variant.
/// </summary>
public class OtherException : XbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
