// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8bb2cf947e486dda2e680665792a6bb805dd879866ff4dcddb7bbdaea4e8a9cf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Configuration for the page-classification post-processor.
/// </summary>
public sealed record PageClassificationConfig
{
    /// <summary>
    /// Minijinja prompt template. Receives `{{ labels }}` (joined list), `{{ page_text }}`
    /// and `{{ multi_label }}` variables. `None` lets the backend pick a sensible default.
    /// </summary>
    [JsonPropertyName("prompt_template")]
    public string? PromptTemplate { get; init; } = null;

    /// <summary>
    /// The set of labels the classifier may emit. Must contain at least one entry.
    /// </summary>
    [JsonPropertyName("labels")]
    public List<string> Labels { get; init; } = [];

    /// <summary>
    /// Allow multiple labels per page. Single-label mode returns at most one label.
    /// </summary>
    [JsonPropertyName("multi_label")]
    public bool MultiLabel { get; init; } = false;

    /// <summary>
    /// LLM configuration used for classification.
    /// </summary>
    [JsonPropertyName("llm")]
    public required LlmConfig Llm { get; init; }


    /// <summary>
    /// Parse a <see cref="PageClassificationConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static PageClassificationConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<PageClassificationConfig>(json, JsonOptions)
            ?? throw new XbergException($"Failed to parse PageClassificationConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse PageClassificationConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
