// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8a44f3b95b7d3e50883becd244543c7abdcc4ed1895cba40b4e1e609c845e363
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file is not valid JSON.
/// </summary>
public class ParseException : LoadErrorException
{
    public ParseException(string message) : base(message) { }

    public ParseException(string message, Exception innerException) : base(message, innerException) { }
}
