// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:597bd1ea631d4ac6d358d121dc5791450b5d9aaaabe53fda1e43bef2af72e4ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Pixel-space bounding box of a QR code inside its source image.
/// </summary>
public sealed record QrBoundingBox
{
    /// <summary>
    /// Horizontal pixel offset of the bounding box top-left corner.
    /// </summary>
    [JsonPropertyName("x")]
    public uint X { get; init; } = 0;

    /// <summary>
    /// Vertical pixel offset of the bounding box top-left corner.
    /// </summary>
    [JsonPropertyName("y")]
    public uint Y { get; init; } = 0;

    /// <summary>
    /// Width of the bounding box in pixels.
    /// </summary>
    [JsonPropertyName("width")]
    public uint Width { get; init; } = 0;

    /// <summary>
    /// Height of the bounding box in pixels.
    /// </summary>
    [JsonPropertyName("height")]
    public uint Height { get; init; } = 0;


    /// <summary>
    /// Parse a <see cref="QrBoundingBox"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static QrBoundingBox FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<QrBoundingBox>(json, JsonOptions)
            ?? throw new XbergException($"Failed to parse QrBoundingBox from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse QrBoundingBox from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
