// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8bb2cf947e486dda2e680665792a6bb805dd879866ff4dcddb7bbdaea4e8a9cf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Inline text annotation — byte-range based formatting and links.
///
/// Annotations reference byte offsets into the node's text content,
/// enabling precise identification of formatted regions.
/// </summary>
public sealed record TextAnnotation
{
    /// <summary>
    /// Start byte offset in the node's text content (inclusive).
    /// </summary>
    [JsonPropertyName("start")]
    public uint Start { get; init; } = 0;

    /// <summary>
    /// End byte offset in the node's text content (exclusive).
    /// </summary>
    [JsonPropertyName("end")]
    public uint End { get; init; } = 0;

    /// <summary>
    /// Annotation type.
    /// </summary>
    [JsonPropertyName("kind")]
    public required AnnotationKind Kind { get; init; }


    /// <summary>
    /// Parse a <see cref="TextAnnotation"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static TextAnnotation FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<TextAnnotation>(json, JsonOptions)
            ?? throw new XbergException($"Failed to parse TextAnnotation from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse TextAnnotation from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
