// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e3b6b82fc7d2b08d3d09205dcdefe78b078e18b28a7e1dc16aeff66cb414069f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import {
  extractFile,
  extractBytesSync,
  extractFileSync,
  renderPdfPageToPng,
  type JsExtractionConfig,
} from "kreuzberg";

describe("error", () => {
  it("error_empty_bytes: Graceful handling of empty bytes (should not error)", () => {
    extractBytesSync("text/empty.txt", "text/plain");
  });

  it("error_empty_mime: Error when extracting with empty MIME type", async () => {
    await expect(async () => {
      await extractBytesSync("text/plain.txt", "");
    }).rejects.toThrow();
  });

  it("error_extract_bytes_conflicting_ocr: extract_bytes force+disable OCR", async () => {
    await expect(async () => {
      await extractBytesSync("SGVsbG8=", "text/plain", {
        disableOcr: true,
        forceOcr: true,
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_file_not_found: Error when file does not exist (sync)", async () => {
    await expect(async () => {
      await extractFileSync("nonexistent/file.pdf");
    }).rejects.toThrow();
  });

  it("error_file_not_found_async: Error when file does not exist (async)", async () => {
    await expect(async () => {
      await extractFile("nonexistent/file.pdf");
    }).rejects.toThrow();
  });

  it("error_invalid_chunk_overlap: Error when chunk overlap exceeds max_characters", async () => {
    await expect(async () => {
      await extractFileSync("pdf/fake_memo.pdf", undefined, {
        chunking: { maxCharacters: 10, overlapCharacters: 100 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_invalid_confidence: Error when OCR confidence threshold is out of range", async () => {
    await expect(async () => {
      await extractFileSync("pdf/fake_memo.pdf", undefined, {
        ocr: { confidenceThreshold: 2.0 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_invalid_dpi: Error when OCR DPI is invalid (negative)", async () => {
    await expect(async () => {
      await extractFileSync("pdf/fake_memo.pdf", undefined, {
        ocr: { dpi: -1 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_invalid_mime_format: Error when extracting with invalid MIME type format", async () => {
    await expect(async () => {
      await extractBytesSync("text/plain.txt", "not-a-mime");
    }).rejects.toThrow();
  });

  it("error_invalid_ocr_language: Error when OCR language pack is not available", async () => {
    await expect(async () => {
      await extractFileSync("images/balance_sheet_1.png", undefined, {
        ocr: { forceOcr: true, language: "zzz_nonexistent" },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_pdf_corrupt: Error when PDF is truncated/corrupt", async () => {
    await expect(async () => {
      await extractFileSync("pdf/corrupt_truncated.pdf");
    }).rejects.toThrow();
  });

  it("error_pdf_needs_password: Error when password-protected PDF is accessed without password", async () => {
    await expect(async () => {
      await extractFileSync("pdf/password_protected.pdf");
    }).rejects.toThrow();
  });

  it("error_pdf_page_out_of_range: Graceful handling of out-of-range page extraction", () => {
    extractFileSync("pdf/fake_memo.pdf", undefined, { pages: "999-1000" } as JsExtractionConfig);
  });

  it("error_pdf_wrong_password: Error when PDF password is incorrect", async () => {
    await expect(async () => {
      await extractFileSync("pdf/password_protected.pdf", undefined, {
        pdf: { password: "wrongpassword" },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_render_corrupt_pdf: Error when rendering page from corrupt PDF", async () => {
    await expect(async () => {
      await renderPdfPageToPng("pdf/corrupt_truncated.pdf", 0);
    }).rejects.toThrow();
  });

  it("error_render_invalid_page: Error when rendering page number exceeds document page count", async () => {
    await expect(async () => {
      await renderPdfPageToPng("pdf/fake_memo.pdf", 0);
    }).rejects.toThrow();
  });

  it("error_security_archive_files: Error when archive file count exceeds security limit", async () => {
    await expect(async () => {
      await extractFileSync("archives/documents.zip", undefined, {
        securityLimits: { maxFilesInArchive: 0 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_security_archive_size: Error when archive size exceeds security limit", async () => {
    await expect(async () => {
      await extractFileSync("archives/documents.zip", undefined, {
        securityLimits: { maxArchiveSize: 1 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_security_content_too_large: Error when content exceeds security limit for max size", async () => {
    await expect(async () => {
      await extractFileSync("pdf/fake_memo.pdf", undefined, {
        securityLimits: { maxContentSize: 10 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_security_entity_too_long: Error when an XML attribute / entity expansion exceeds max_entity_length (EntityValidator fires). Real DOCX attributes routinely exceed a 2-byte cap, so this trips on any content.", async () => {
    await expect(async () => {
      await extractFileSync("docx/lorem_ipsum.docx", undefined, {
        securityLimits: { maxEntityLength: 2 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_security_nesting_depth: Error when XML nesting depth exceeds security limit", async () => {
    await expect(async () => {
      await extractFileSync("html/complex_table.html", undefined, {
        securityLimits: { maxNestingDepth: 1 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_security_nesting_too_deep: Error when XML/DOCX nesting depth exceeds max_xml_depth (DepthValidator fires)", async () => {
    await expect(async () => {
      await extractFileSync("docx/lorem_ipsum.docx", undefined, {
        securityLimits: { maxXmlDepth: 1 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_security_too_many_cells: Error when cumulative table cell count exceeds max_table_cells (TableValidator fires). The Stanley Cups spreadsheet has more than 1 cell, so any tabular extraction trips this dial-down.", async () => {
    await expect(async () => {
      await extractFileSync("xlsx/stanley_cups.xlsx", undefined, {
        securityLimits: { maxTableCells: 1 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_security_too_many_iterations: Error when extractor parser-loop iteration count exceeds max_iterations (IterationValidator fires)", async () => {
    await expect(async () => {
      await extractFileSync("docx/lorem_ipsum.docx", undefined, {
        securityLimits: { maxIterations: 1 },
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_timeout_extraction: Error when extraction times out", async () => {
    await expect(async () => {
      await extractFileSync("pdf/large.pdf", undefined, {
        extractionTimeoutSecs: 1,
      } as JsExtractionConfig);
    }).rejects.toThrow();
  });

  it("error_unsupported_mime: Error when extracting with unsupported MIME type", async () => {
    await expect(async () => {
      await extractBytesSync("text/plain.txt", "application/x-nonexistent");
    }).rejects.toThrow();
  });
});
