// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:be6431810f980f11acfce2b0afcbc4366d6b923ff80bd76d49baf4243c043554
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith

/** E2e tests for category: serialization. */
class SerializationTest {
    @Test
    fun testSerializeJsonBasic() {
        // Serialize extraction result to JSON
        val result = Kreuzberg.serializeToJson("test_documents/text/plain.txt", "{}")
        assertTrue(result.content.orEmpty().length >= 1, "expected length >= 1")
    }

    @Test
    fun testSerializeJsonPdf() {
        // Serialize PDF extraction to JSON
        val result = Kreuzberg.serializeToJson("test_documents/pdf/sample.pdf", "{}")
        assertTrue(result.content.orEmpty().contains("content"), "expected to contain: " + "content")
    }

    @Test
    fun testSerializeToonBasic() {
        // Serialize extraction result to TOON format
        val result = Kreuzberg.serializeToToon("test_documents/text/plain.txt", "{}")
        assertTrue(result.content.orEmpty().length >= 1, "expected length >= 1")
    }

    @Test
    fun testSerializeToonPdf() {
        // Serialize PDF extraction to TOON
        val result = Kreuzberg.serializeToToon("test_documents/pdf/sample.pdf", "{}")
        assertTrue(result.content.orEmpty().length >= 10, "expected length >= 10")
    }

}
