# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd60e47971612bd724e59d936f928e3b4c42f96abe779095d1c5f3f955774a01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: extraction."""
import pytest  # noqa: F401
from kreuzberg import extract_file


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_extract_doc_basic() -> None:
    """Extract text from a DOC file containing unit test lists."""
    path = None
    result = await extract_file(path=path)
    assert len(result.content) >= 10  # noqa: S101

@pytest.mark.asyncio
async def test_extract_email_basic() -> None:
    """Extract content from an email file in EML format."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.asyncio
async def test_extract_pdf_basic() -> None:
    """Extract text from a basic PDF document containing memo content."""
    path = None
    result = await extract_file(path=path)
    assert len(result.content) >= 50  # noqa: S101

@pytest.mark.asyncio
async def test_extract_pdf_code() -> None:
    """Extract text from PDF containing code snippets and formulas."""
    path = None
    result = await extract_file(path=path)
    assert len(result.content) >= 20  # noqa: S101

@pytest.mark.asyncio
async def test_extract_pptx_basic() -> None:
    """Extract text from a PowerPoint presentation file."""
    path = None
    _ = await extract_file(path=path)
