# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:edbf252222b45d4477efbc0b7268744f38839a74c1b7f9f40f260231d4f25e80
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: serialization."""
from kreuzberg import serialize_to_json, serialize_to_toon, ExtractionConfig


def test_serialize_json_basic() -> None:
    """Serialize extraction result to JSON."""
    path = "test_documents/text/plain.txt"
    config = ExtractionConfig()
    result = serialize_to_json(path=path, config=config)
    assert len(result.content) >= 1  # noqa: S101

def test_serialize_json_pdf() -> None:
    """Serialize PDF extraction to JSON."""
    path = "test_documents/pdf/sample.pdf"
    config = ExtractionConfig()
    result = serialize_to_json(path=path, config=config)
    assert result.content is not None  # noqa: S101
    assert "content" in result.content  # noqa: S101

def test_serialize_toon_basic() -> None:
    """Serialize extraction result to TOON format."""
    path = "test_documents/text/plain.txt"
    config = ExtractionConfig()
    result = serialize_to_toon(path=path, config=config)
    assert len(result.content) >= 1  # noqa: S101

def test_serialize_toon_pdf() -> None:
    """Serialize PDF extraction to TOON."""
    path = "test_documents/pdf/sample.pdf"
    config = ExtractionConfig()
    result = serialize_to_toon(path=path, config=config)
    assert len(result.content) >= 10  # noqa: S101

