# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcc5bd0dcc9b51630b5792339add8fb280ff50c78baa7cc749fed80073bf545b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: serialization."""

from kreuzberg import serialize_to_json, serialize_to_toon, ExtractionConfig


def test_serialize_json_basic() -> None:
    """Serialize extraction result to JSON."""
    path = "test_documents/text/plain.txt"
    config = ExtractionConfig()
    result = serialize_to_json(path=path, config=config)
    assert len(result.content) >= 1  # noqa: S101


def test_serialize_json_pdf() -> None:
    """Serialize PDF extraction to JSON."""
    path = "test_documents/pdf/sample.pdf"
    config = ExtractionConfig()
    result = serialize_to_json(path=path, config=config)
    assert "content" in result.content  # noqa: S101


def test_serialize_toon_basic() -> None:
    """Serialize extraction result to TOON format."""
    path = "test_documents/text/plain.txt"
    config = ExtractionConfig()
    result = serialize_to_toon(path=path, config=config)
    assert len(result.content) >= 1  # noqa: S101


def test_serialize_toon_pdf() -> None:
    """Serialize PDF extraction to TOON."""
    path = "test_documents/pdf/sample.pdf"
    config = ExtractionConfig()
    result = serialize_to_toon(path=path, config=config)
    assert len(result.content) >= 10  # noqa: S101
