# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8aae00c57dd6ca4f9694ea7266f32c0d32b74269d524b0c94a392a439b2d31de
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: uri."""
import pytest  # noqa: F401
from kreuzberg import extract_file


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_classify_uri_anchor() -> None:
    """Classify fragment URI."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.asyncio
async def test_classify_uri_email() -> None:
    """Classify mailto URI."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.asyncio
async def test_classify_uri_https() -> None:
    """Classify HTTPS URL."""
    path = None
    _ = await extract_file(path=path)
