// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:526dd95d646b2fc6723cf49b611d6d971257dc6ab32569c7652dd0678fd95b12
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;

/** E2e tests for category: detection. */
class DetectionTest {

    @Test
    void testDetectMimeBytesHtml() throws Exception {
        // Detect HTML MIME from bytes
        var result = Kreuzberg.detectMimeTypeFromBytes("html/html.html".getBytes());

    }


    @Test
    void testDetectMimeBytesPdf() throws Exception {
        // Detect PDF MIME type from bytes
        var result = Kreuzberg.detectMimeTypeFromBytes("pdf/fake_memo.pdf".getBytes());

    }


    @Test
    void testDetectMimeBytesPng() throws Exception {
        // Detect PNG MIME type from bytes
        var result = Kreuzberg.detectMimeTypeFromBytes("images/test_hello_world.png".getBytes());

    }


    @Test
    void testGetExtensionsUnknownMime() throws Exception {
        // get_extensions unknown MIME
        assertThrows(Exception.class, () -> Kreuzberg.getExtensionsForMime("application/x-totally-unknown"));
    }

}
