// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6d5d32e4a0a422b6d29fef249d15fc588b9f78d05cb18ba583586f62007152e5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;

/** E2e tests for category: registry. */
class RegistryTest {

    @Test
    void testListDocumentExtractors() throws Exception {
        // List document extractors
        var result = Kreuzberg.listDocumentExtractors();

    }


    @Test
    void testListEmbeddingBackends() throws Exception {
        // List embedding backends
        var result = Kreuzberg.listEmbeddingBackends();

    }


    @Test
    void testListOcrBackends() throws Exception {
        // List OCR backends
        var result = Kreuzberg.listOcrBackends();

    }


    @Test
    void testListPostProcessors() throws Exception {
        // List post-processors
        var result = Kreuzberg.listPostProcessors();

    }


    @Test
    void testListRenderers() throws Exception {
        // List renderers
        var result = Kreuzberg.listRenderers();

    }


    @Test
    void testListValidators() throws Exception {
        // List validators
        var result = Kreuzberg.listValidators();

    }

}
