// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:decbacb38ca392b0d8e278b7044150d6b3cb3a645f79702094e10190b73e260b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for the VLM captioning post-processor.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CaptioningConfig.Builder.class)
@SuppressWarnings("PMD")
public record CaptioningConfig(
    @JsonProperty("llm") LlmConfig llm,
    @Nullable @JsonProperty("prompt") String prompt,
    @Nullable @JsonProperty("min_image_area") Integer minImageArea
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private LlmConfig llm = null;
private String prompt = null;
        @JsonProperty("min_image_area")
private Integer minImageArea = null;

        /** Sets the llm field. */
        @JsonProperty("llm")
        public Builder withLlm(final LlmConfig value) {
            this.llm = value;
            return this;
        }

        /** Sets the prompt field. */
        @JsonProperty("prompt")
        public Builder withPrompt(final @Nullable String value) {
            this.prompt = value;
            return this;
        }

        /** Sets the minImageArea field. */
        @JsonProperty("min_image_area")
        public Builder withMinImageArea(final @Nullable Integer value) {
            this.minImageArea = value;
            return this;
        }

        /** Builds the CaptioningConfig instance. */
        public CaptioningConfig build() {
            return new CaptioningConfig(
                llm,
                prompt,
                minImageArea
            );
        }
    }
    // CPD-ON
}
