// DO NOT EDIT - auto-generated by alef
// alef:hash:a5535c303d73df69627444d4293624026b8e689f949e546a2bdb9ce826d6f1be
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
