// DO NOT EDIT - auto-generated by alef
// alef:hash:5c9f944c39de567bb09002e728814619255d8333911621225478aa7364f39935
package dev.kreuzberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
