// DO NOT EDIT - auto-generated by alef
// alef:hash:fa6e7bda6133407a4c8f03702dcfba9546b2be66fac954269393aa46e7fd43b3
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
