# Generated by alef. Do not edit by hand.
# alef:hash:2a1926de7910b3789b64da14061dd23c1defcae86f0082fd54b028972453e2fc
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.** { *; }
