// Generated by alef. Do not edit by hand.
// alef:hash:8a44f3b95b7d3e50883becd244543c7abdcc4ed1895cba40b4e1e609c845e363

package io.xberg

object EmbeddingBackendBridge {
    private val registered = mutableMapOf<String, IEmbeddingBackend>()

    fun register(impl: IEmbeddingBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterEmbeddingBackend(EmbeddingBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterEmbeddingBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearEmbeddingBackends()
    }

    fun getAll(): Map<String, IEmbeddingBackend> = registered.toMap()
}
