// Generated by alef. Do not edit by hand.
// alef:hash:8bb2cf947e486dda2e680665792a6bb805dd879866ff4dcddb7bbdaea4e8a9cf
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Trait for OCR backend plugins.
 *
 * Implement this trait to add custom OCR capabilities. OCR backends can be:
 *
 * - Native Rust implementations (like Tesseract)
 * - FFI bridges to external libraries (like PaddleOCR)
 * - Cloud-based OCR services (Google Vision, AWS Textract, etc.)
 *
 * # Thread Safety
 *
 * OCR backends must be thread-safe (`Send + Sync`) to support concurrent processing.
 */
interface IOcrBackend {
    fun name(): String
    fun version(): String
    fun initialize() {}
    fun shutdown() {}
    fun description(): String = ""
    fun author(): String = ""
    /**
     * Process an image and extract text via OCR.
     *
     * **Returns:**
     *
     * An `ExtractedDocument` containing the extracted text and metadata.
     *
     * **Errors:**
     *
     * - `XbergError.Ocr` - OCR processing failed
     * - `XbergError.Validation` - Invalid image format or configuration
     * - `XbergError.Io` - I/O errors (these always bubble up)
     *
     * # Reading `backend_options`
     *
     * Backends that support runtime tuning can read `config.backend_options` and
     * deserialize only the keys they care about. Unknown keys are silently ignored,
     * so multiple backends can coexist in a pipeline without key conflicts.
     */
    suspend fun processImage(imageBytes: ByteArray, config: OcrConfig): ExtractedDocument
    /**
     * Process a file and extract text via OCR.
     *
     * Default implementation reads the file and calls `process_image`.
     * Override for custom file handling or optimizations.
     *
     * **Errors:**
     *
     * Same as `process_image`, plus file I/O errors.
     */
    suspend fun processImageFile(path: String, config: OcrConfig): ExtractedDocument
    /**
     * Check if this backend supports a given language code.
     *
     * **Returns:**
     *
     * `true` if the language is supported, `false` otherwise.
     */
    fun supportsLanguage(lang: String): Boolean
    /**
     * Get the backend type identifier.
     *
     * **Returns:**
     *
     * The backend type enum value.
     */
    fun backendType(): OcrBackendType
    /**
     * Optional: Get a list of all supported languages.
     *
     * Defaults to empty list. Override to provide comprehensive language support info.
     */
    fun supportedLanguages(): List<String>
    /**
     * Optional: Check if the backend supports table detection.
     *
     * Defaults to `false`. Override if your backend can detect and extract tables.
     */
    fun supportsTableDetection(): Boolean
    /**
     * Check if the backend supports direct document-level processing (e.g. for PDFs).
     *
     * Defaults to `false`. Override if the backend has optimized document processing.
     */
    fun supportsDocumentProcessing(): Boolean
    /**
     * Declare that this backend emits structured markdown directly (tables, headings, lists)
     * and downstream layout reconstruction should be skipped.
     *
     * Defaults to `false` — classical OCR backends (Tesseract, PaddleOCR classical) return
     * plain text per detected region. End-to-end VLM backends (PaddleOCR-VL, GOT-OCR 2.0)
     * emit markdown in one forward pass and should override this to `true`.
     */
    fun emitsStructuredMarkdown(): Boolean
    /**
     * Process a document file directly via OCR.
     *
     * Only called if `supports_document_processing` returns `true`.
     */
    suspend fun processDocument(path: String, config: OcrConfig): ExtractedDocument
}
