// Generated by alef. Do not edit by hand.
// alef:hash:0c4ed597c7beb11c21c08eb657d38a2f336825dd3932ffba8461108cca62f969

package io.xberg

object OcrBackendBridge {
    private val registered = mutableMapOf<String, IOcrBackend>()

    fun register(impl: IOcrBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterOcrBackend(OcrBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterOcrBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearOcrBackends()
    }

    fun getAll(): Map<String, IOcrBackend> = registered.toMap()
}
