// Generated by alef. Do not edit by hand.
// alef:hash:28933e85bc9dc440d3d48a0fa997a78b13df863b6249812908ba7914441b9232

package io.xberg

object RerankerBackendBridge {
    private val registered = mutableMapOf<String, IRerankerBackend>()

    fun register(impl: IRerankerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterRerankerBackend(RerankerBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterRerankerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearRerankerBackends()
    }

    fun getAll(): Map<String, IRerankerBackend> = registered.toMap()
}
