// Generated by alef. Do not edit by hand.
// alef:hash:446748155774867df28fecd60b1f51d93e20d7476cf9f2aad1cd588a1cf0950e
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.core.type.TypeReference
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.PropertyNamingStrategies
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.KotlinFeature
import com.fasterxml.jackson.module.kotlin.KotlinModule
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
object Xberg {
    /// Jackson module that marshals ByteArray as a JSON array of unsigned bytes,
    /// matching how Rust serde encodes Vec<u8> on the wire.
    /// Jackson's default writes ByteArray as a Base64 string, which Rust serde rejects
    /// with "invalid type: string, expected a sequence".
    private val byteArrayModule = com.fasterxml.jackson.databind.module.SimpleModule().apply {
        addSerializer(
            ByteArray::class.java,
            object : com.fasterxml.jackson.databind.ser.std.StdSerializer<ByteArray>(ByteArray::class.java) {
                override fun serialize(
                    value: ByteArray,
                    gen: com.fasterxml.jackson.core.JsonGenerator,
                    provider: com.fasterxml.jackson.databind.SerializerProvider,
                ) {
                    gen.writeStartArray()
                    for (b in value) gen.writeNumber(b.toInt() and 0xff)
                    gen.writeEndArray()
                }
            },
        )
        addDeserializer(
            ByteArray::class.java,
            object : com.fasterxml.jackson.databind.deser.std.StdDeserializer<ByteArray>(ByteArray::class.java) {
                override fun deserialize(
                    parser: com.fasterxml.jackson.core.JsonParser,
                    ctx: com.fasterxml.jackson.databind.DeserializationContext,
                ): ByteArray {
                    val node = parser.codec.readTree<com.fasterxml.jackson.databind.JsonNode>(parser)
                    return when {
                        node.isArray -> ByteArray(node.size()) { i -> node.get(i).asInt().toByte() }
                        node.isTextual -> java.util.Base64.getDecoder().decode(node.asText())
                        else -> ByteArray(0)
                    }
                }
            },
        )
    }

    private val mapper = jacksonObjectMapper()
        .registerModule(com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
        .registerModule(byteArrayModule)
        .registerModule(
            com.fasterxml.jackson.module.kotlin.KotlinModule.Builder()
                .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullIsSameAsDefault, true)
                .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyCollection, true)
                .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyMap, true)
                .build(),
        )
        .setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
        .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY)
        .configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    /** Extract content from a single bytes or URI input. */
    fun extract(input: ExtractInput, config: ExtractionConfig): ExtractionOutput {
        val resultJson = XbergBridge.nativeExtract(mapper.writeValueAsString(input), mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, ExtractionOutput::class.java)
    }
    /** Extract content from a single bytes or URI input. */
    suspend fun extractAsync(input: ExtractInput, config: ExtractionConfig): ExtractionOutput =
        withContext(Dispatchers.IO) { extract(input, config) }
    /** Extract content from multiple bytes or URI inputs. */
    fun extractBatch(inputs: List<ExtractInput>, config: ExtractionConfig): ExtractionOutput {
        val resultJson = XbergBridge.nativeExtractBatch(mapper.writeValueAsString(inputs), mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, ExtractionOutput::class.java)
    }
    /** Extract content from multiple bytes or URI inputs. */
    suspend fun extractBatchAsync(inputs: List<ExtractInput>, config: ExtractionConfig): ExtractionOutput =
        withContext(Dispatchers.IO) { extractBatch(inputs, config) }
    /**
     * Detect MIME type from raw file bytes.
     *
     * Uses magic byte signatures to detect file type from content.
     * Falls back to `infer` crate for comprehensive detection.
     *
     * For ZIP-based files, inspects contents to distinguish Office Open XML
     * formats (DOCX, XLSX, PPTX) from plain ZIP archives.
     *
     * **Returns:**
     *
     * The detected MIME type string.
     *
     * **Errors:**
     *
     * Returns `XbergError.UnsupportedFormat` if MIME type cannot be determined.
     */
    fun detectMimeTypeFromBytes(content: ByteArray): String = XbergBridge.nativeDetectMimeTypeFromBytes(java.util.Base64.getEncoder().encodeToString(content))
    /**
     * Get file extensions for a given MIME type.
     *
     * Returns all known file extensions that map to the specified MIME type.
     *
     * **Returns:**
     *
     * A vector of file extensions (without leading dot) for the MIME type.
     */
    fun getExtensionsForMime(mimeType: String): List<String> {
        val resultJson = XbergBridge.nativeGetExtensionsForMime(mimeType)
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * Get file extensions for a given MIME type.
     *
     * Returns all known file extensions that map to the specified MIME type.
     *
     * **Returns:**
     *
     * A vector of file extensions (without leading dot) for the MIME type.
     */
    suspend fun getExtensionsForMimeAsync(mimeType: String): List<String> =
        withContext(Dispatchers.IO) { getExtensionsForMime(mimeType) }
    /**
     * List all supported document formats.
     *
     * Returns every file extension Xberg recognizes together with its
     * corresponding MIME type, derived from the central format registry.
     * Formats that have no registered file extension (such as source code,
     * which is detected dynamically) are not included.
     *
     * The list is sorted alphabetically by file extension.
     *
     * **Returns:**
     *
     * A vector of `SupportedFormat` entries sorted by extension.
     */
    fun listSupportedFormats(): List<SupportedFormat> {
        val resultJson = XbergBridge.nativeListSupportedFormats()
        return mapper.readValue(resultJson, object : TypeReference<List<SupportedFormat>>() {})
    }
    /**
     * List all supported document formats.
     *
     * Returns every file extension Xberg recognizes together with its
     * corresponding MIME type, derived from the central format registry.
     * Formats that have no registered file extension (such as source code,
     * which is detected dynamically) are not included.
     *
     * The list is sorted alphabetically by file extension.
     *
     * **Returns:**
     *
     * A vector of `SupportedFormat` entries sorted by extension.
     */
    suspend fun listSupportedFormatsAsync(): List<SupportedFormat> =
        withContext(Dispatchers.IO) { listSupportedFormats() }
    /**
     * Detect QR codes in the bytes of an `ExtractedImage`.
     *
     * `format_hint` is currently unused — the `image` crate auto-detects the
     * container format from magic bytes — but the parameter is retained so future
     * backends (e.g. a WebP-via-`webp-decoder` variant) can use it without an API
     * break.
     *
     * Returns an empty listtor on any of:
     *
     * - Empty input.
     * - Image-decode failure.
     * - No QR grids detected.
     * - All detected grids fail to decode.
     *
     * Successfully decoded QR codes carry their payload, a confidence of `1.0`
     * (rqrr does not expose per-grid confidence; a successful decode is treated
     * as high-confidence by convention), and the pixel-space bounding box derived
     * from the four corner points of the grid.
     */
    fun detectQrCodes(imageBytes: ByteArray, formatHint: String? = null): List<QrCode> {
        val resultJson = XbergBridge.nativeDetectQrCodes(java.util.Base64.getEncoder().encodeToString(imageBytes), formatHint ?: "")
        return mapper.readValue(resultJson, object : TypeReference<List<QrCode>>() {})
    }
    /**
     * Detect QR codes in the bytes of an `ExtractedImage`.
     *
     * `format_hint` is currently unused — the `image` crate auto-detects the
     * container format from magic bytes — but the parameter is retained so future
     * backends (e.g. a WebP-via-`webp-decoder` variant) can use it without an API
     * break.
     *
     * Returns an empty listtor on any of:
     *
     * - Empty input.
     * - Image-decode failure.
     * - No QR grids detected.
     * - All detected grids fail to decode.
     *
     * Successfully decoded QR codes carry their payload, a confidence of `1.0`
     * (rqrr does not expose per-grid confidence; a successful decode is treated
     * as high-confidence by convention), and the pixel-space bounding box derived
     * from the four corner points of the grid.
     */
    suspend fun detectQrCodesAsync(imageBytes: ByteArray, formatHint: String? = null): List<QrCode> =
        withContext(Dispatchers.IO) { detectQrCodes(imageBytes, formatHint) }
    /**
     * Clear all embedding backends from the global registry.
     *
     * Calls `shutdown()` on every registered backend, then empties the registry.
     *
     * **Errors:**
     *
     * - Any error returned by a backend's `shutdown()` method. The first error
     *   encountered stops processing of remaining backends.
     */
    fun clearEmbeddingBackends(): Unit = XbergBridge.nativeClearEmbeddingBackends()
    /**
     * List the names of all registered embedding backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     */
    fun listEmbeddingBackends(): List<String> {
        val resultJson = XbergBridge.nativeListEmbeddingBackends()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List the names of all registered embedding backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     */
    suspend fun listEmbeddingBackendsAsync(): List<String> =
        withContext(Dispatchers.IO) { listEmbeddingBackends() }
    /**
     * List all registered OCR backends.
     *
     * Returns the names of all OCR backends currently registered in the global registry.
     *
     * **Returns:**
     *
     * A vector of OCR backend names.
     */
    fun listOcrBackends(): List<String> {
        val resultJson = XbergBridge.nativeListOcrBackends()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List all registered OCR backends.
     *
     * Returns the names of all OCR backends currently registered in the global registry.
     *
     * **Returns:**
     *
     * A vector of OCR backend names.
     */
    suspend fun listOcrBackendsAsync(): List<String> =
        withContext(Dispatchers.IO) { listOcrBackends() }
    /**
     * Clear all OCR backends from the global registry.
     *
     * Removes all OCR backends and calls their `shutdown()` methods.
     *
     * **Returns:**
     *
     * - `Ok(())` if all backends were cleared successfully
     * - `Err(...)` if any shutdown method failed
     */
    fun clearOcrBackends(): Unit = XbergBridge.nativeClearOcrBackends()
    /**
     * Register every built-in post-processor enabled by the active feature set.
     *
     * This is the single entry point that callers (including
     * `register_default_post_processors`) use to populate the global
     * post-processor registry with the in-tree built-ins. Each submodule's own
     * `register` function is gated by its feature flag so this aggregate stays
     * safe to call on any target.
     */
    fun registerBuiltin(): Unit = XbergBridge.nativeRegisterBuiltin()
    /**
     * List all registered post-processor names.
     *
     * Returns a vector of all post-processor names currently registered in the
     * global registry.
     *
     * **Returns:**
     *
     * - `Ok(List<String>)` - Vector of post-processor names
     * - `Err(...)` if the registry lock is poisoned
     */
    fun listPostProcessors(): List<String> {
        val resultJson = XbergBridge.nativeListPostProcessors()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List all registered post-processor names.
     *
     * Returns a vector of all post-processor names currently registered in the
     * global registry.
     *
     * **Returns:**
     *
     * - `Ok(List<String>)` - Vector of post-processor names
     * - `Err(...)` if the registry lock is poisoned
     */
    suspend fun listPostProcessorsAsync(): List<String> =
        withContext(Dispatchers.IO) { listPostProcessors() }
    /** Remove all registered post-processors. */
    fun clearPostProcessors(): Unit = XbergBridge.nativeClearPostProcessors()
    /**
     * List names of all registered renderers.
     *
     * **Errors:**
     *
     * Returns an error if the registry lock is poisoned.
     */
    fun listRenderers(): List<String> {
        val resultJson = XbergBridge.nativeListRenderers()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List names of all registered renderers.
     *
     * **Errors:**
     *
     * Returns an error if the registry lock is poisoned.
     */
    suspend fun listRenderersAsync(): List<String> =
        withContext(Dispatchers.IO) { listRenderers() }
    /**
     * Clear all renderers from the global registry.
     *
     * Removes every renderer, including the built-in defaults (markdown, html,
     * djot, plain). After calling this no renderers are registered; re-register
     * as needed.
     *
     * **Errors:**
     *
     * Returns an error if the registry lock is poisoned.
     */
    fun clearRenderers(): Unit = XbergBridge.nativeClearRenderers()
    /**
     * Clear all reranker backends from the global registry.
     *
     * Calls `shutdown()` on every registered backend, then empties the registry.
     *
     * **Errors:**
     *
     * - Any error returned by a backend's `shutdown()` method. The first error
     *   encountered stops processing of remaining backends.
     *
     * Since v5.0.
     */
    fun clearRerankerBackends(): Unit = XbergBridge.nativeClearRerankerBackends()
    /**
     * List the names of all registered reranker backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     *
     * Since v5.0.
     */
    fun listRerankerBackends(): List<String> {
        val resultJson = XbergBridge.nativeListRerankerBackends()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List the names of all registered reranker backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     *
     * Since v5.0.
     */
    suspend fun listRerankerBackendsAsync(): List<String> =
        withContext(Dispatchers.IO) { listRerankerBackends() }
    /** List names of all registered validators. */
    fun listValidators(): List<String> {
        val resultJson = XbergBridge.nativeListValidators()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /** List names of all registered validators. */
    suspend fun listValidatorsAsync(): List<String> =
        withContext(Dispatchers.IO) { listValidators() }
    /** Remove all registered validators. */
    fun clearValidators(): Unit = XbergBridge.nativeClearValidators()
    /**
     * Run page classification against an extraction result.
     *
     * Mutates `result.page_classifications` with one entry per non-empty page and
     * appends every LLM call's usage to `result.llm_usage`.
     *
     * **Errors:**
     *
     * Returns the first error encountered when rendering the prompt or calling the
     * LLM. Partially produced classifications are discarded so callers do not see
     * a half-populated vector.
     */
    fun classifyPages(result: ExtractionResult, config: PageClassificationConfig): Unit = XbergBridge.nativeClassifyPages(mapper.writeValueAsString(result), mapper.writeValueAsString(config))
    /**
     * Classify a single piece of text without requiring an `ExtractionResult`.
     *
     * Use this when the caller already has plain text (e.g. a RAG ingest pipeline
     * receiving documents off a queue) and wants a label list back without
     * manufacturing extractor-side metadata.
     *
     * **Errors:**
     *
     * Same as `classify_pages`: a validation error when `config.labels` is empty,
     * or any error returned by prompt rendering or the underlying LLM call.
     */
    fun classifyText(text: String, config: PageClassificationConfig): List<ClassificationLabel> {
        val resultJson = XbergBridge.nativeClassifyText(text, mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, object : TypeReference<List<ClassificationLabel>>() {})
    }
    /**
     * Classify a single piece of text without requiring an `ExtractionResult`.
     *
     * Use this when the caller already has plain text (e.g. a RAG ingest pipeline
     * receiving documents off a queue) and wants a label list back without
     * manufacturing extractor-side metadata.
     *
     * **Errors:**
     *
     * Same as `classify_pages`: a validation error when `config.labels` is empty,
     * or any error returned by prompt rendering or the underlying LLM call.
     */
    suspend fun classifyTextAsync(text: String, config: PageClassificationConfig): List<ClassificationLabel> =
        withContext(Dispatchers.IO) { classifyText(text, config) }
    /**
     * Classify a single document (as multiple pages or a single text block).
     *
     * Aggregates classifications across all pages in the provided text, returning
     * a combined label set that represents the document as a whole.
     *
     *   using the configured LLM, and results are aggregated.
     *
     * - `config` - Classification configuration including labels and LLM settings.
     *
     * **Returns:**
     *
     * A vector of `ClassificationLabel` entries representing the document's overall classification.
     *
     * **Errors:**
     *
     * Returns an error if `config.labels` is empty or if LLM calls fail.
     */
    fun classifyDocument(pages: List<String>, config: PageClassificationConfig): List<ClassificationLabel> {
        val resultJson = XbergBridge.nativeClassifyDocument(mapper.writeValueAsString(pages), mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, object : TypeReference<List<ClassificationLabel>>() {})
    }
    /**
     * Classify a single document (as multiple pages or a single text block).
     *
     * Aggregates classifications across all pages in the provided text, returning
     * a combined label set that represents the document as a whole.
     *
     *   using the configured LLM, and results are aggregated.
     *
     * - `config` - Classification configuration including labels and LLM settings.
     *
     * **Returns:**
     *
     * A vector of `ClassificationLabel` entries representing the document's overall classification.
     *
     * **Errors:**
     *
     * Returns an error if `config.labels` is empty or if LLM calls fail.
     */
    suspend fun classifyDocumentAsync(pages: List<String>, config: PageClassificationConfig): List<ClassificationLabel> =
        withContext(Dispatchers.IO) { classifyDocument(pages, config) }
    /**
     * Eagerly download a NER model into the xberg cache.
     *
     * `name` is a supported xberg GLiNER alias or catalog id. The CLI flag
     * `xberg cache warm --ner` delegates here.
     */
    fun downloadModel(name: String, cacheDir: String? = null): Long = XbergBridge.nativeDownloadModel(name, cacheDir ?: "")
    /** Pinned default NER model identifier. */
    fun defaultModelName(): String = XbergBridge.nativeDefaultModelName()
    /** All NER models xberg knows about (used by `--all-ner-models`). */
    fun knownModels(): List<String> {
        val resultJson = XbergBridge.nativeKnownModels()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /** All NER models xberg knows about (used by `--all-ner-models`). */
    suspend fun knownModelsAsync(): List<String> =
        withContext(Dispatchers.IO) { knownModels() }
    /**
     * Run pattern redaction (and optional NER-driven redaction) over `result` and
     * rewrite every textual field. Populates `result.redaction_report`.
     */
    fun redact(result: ExtractionResult, config: RedactionConfig): Unit = XbergBridge.nativeRedact(mapper.writeValueAsString(result), mapper.writeValueAsString(config))
    /** Find all US Social Security Number spans in `text` (format: NNN-NN-NNNN). */
    fun findAll(text: String): List<PatternMatch> {
        val resultJson = XbergBridge.nativeFindAll(text)
        return mapper.readValue(resultJson, object : TypeReference<List<PatternMatch>>() {})
    }
    /** Find all US Social Security Number spans in `text` (format: NNN-NN-NNNN). */
    suspend fun findAllAsync(text: String): List<PatternMatch> =
        withContext(Dispatchers.IO) { findAll(text) }
    /**
     * Scan `text` for every PII category in `categories` and return all matches
     * in source-byte order.
     *
     * When `categories` is empty every supported regex-detectable category fires.
     * Person / Organization / Location are *not* covered by the pattern engine —
     * they must be supplied by a NER backend through the redaction engine.
     */
    fun scanText(text: String, categories: List<PiiCategory>): List<PatternMatch> {
        val resultJson = XbergBridge.nativeScanText(text, mapper.writeValueAsString(categories))
        return mapper.readValue(resultJson, object : TypeReference<List<PatternMatch>>() {})
    }
    /**
     * Scan `text` for every PII category in `categories` and return all matches
     * in source-byte order.
     *
     * When `categories` is empty every supported regex-detectable category fires.
     * Person / Organization / Location are *not* covered by the pattern engine —
     * they must be supplied by a NER backend through the redaction engine.
     */
    suspend fun scanTextAsync(text: String, categories: List<PiiCategory>): List<PatternMatch> =
        withContext(Dispatchers.IO) { scanText(text, categories) }
    /**
     * Score and return the top-N sentences from `text`, joined in original order.
     *
     * `language` is an ISO 639 (or locale) code used to pick a stopword list;
     * pass `null` (or an unknown code) to fall back to English.
     * `max_tokens` bounds the summary length by whitespace-separated tokens;
     * `null` falls back to `DEFAULT_MAX_TOKENS`.
     */
    fun summarize(text: String, language: String? = null, maxTokens: Int? = null): String? = XbergBridge.nativeSummarize(text, language ?: "", maxTokens ?: 0)
    /**
     * Count whitespace-separated tokens (used for token-budget bookkeeping by
     * callers).
     */
    fun tokenCount(text: String): Int = XbergBridge.nativeTokenCount(text)
    /**
     * Translate the extraction result in place.
     *
     * Populates `result.translation` with the translated `content`, optionally the
     * translated `formatted_content` (when `preserve_markup = true`), and rewrites
     * every chunk's `content` field. Every LLM call's usage is appended to
     * `result.llm_usage`.
     */
    fun translateResult(result: ExtractionResult, config: TranslationConfig): Unit = XbergBridge.nativeTranslateResult(mapper.writeValueAsString(result), mapper.writeValueAsString(config))
    /**
     * Find all footnote anchor references in markdown text.
     *
     * Returns a vector of footnote anchors (`[^label]` use-sites), including byte offsets.
     * Footnote definitions (`[^label]: ...`) are NOT included in the results.
     *
     * **Returns:**
     *
     * A vector of `FootnoteAnchor` entries, each with the label and byte offset.
     */
    fun findFootnoteAnchors(markdown: String): List<FootnoteAnchor> {
        val resultJson = XbergBridge.nativeFindFootnoteAnchors(markdown)
        return mapper.readValue(resultJson, object : TypeReference<List<FootnoteAnchor>>() {})
    }
    /**
     * Find all footnote anchor references in markdown text.
     *
     * Returns a vector of footnote anchors (`[^label]` use-sites), including byte offsets.
     * Footnote definitions (`[^label]: ...`) are NOT included in the results.
     *
     * **Returns:**
     *
     * A vector of `FootnoteAnchor` entries, each with the label and byte offset.
     */
    suspend fun findFootnoteAnchorsAsync(markdown: String): List<FootnoteAnchor> =
        withContext(Dispatchers.IO) { findFootnoteAnchors(markdown) }
    /**
     * Parse footnote definitions from markdown text.
     *
     * Returns a vector of footnote definitions found in the markdown.
     * Handles multi-line definitions with continuation/indented lines (CommonMark format).
     *
     * **Returns:**
     *
     * A vector of `FootnoteDefinition` entries, each with label, content, and byte offset.
     */
    fun parseFootnoteDefinitions(markdown: String): List<FootnoteDefinition> {
        val resultJson = XbergBridge.nativeParseFootnoteDefinitions(markdown)
        return mapper.readValue(resultJson, object : TypeReference<List<FootnoteDefinition>>() {})
    }
    /**
     * Parse footnote definitions from markdown text.
     *
     * Returns a vector of footnote definitions found in the markdown.
     * Handles multi-line definitions with continuation/indented lines (CommonMark format).
     *
     * **Returns:**
     *
     * A vector of `FootnoteDefinition` entries, each with label, content, and byte offset.
     */
    suspend fun parseFootnoteDefinitionsAsync(markdown: String): List<FootnoteDefinition> =
        withContext(Dispatchers.IO) { parseFootnoteDefinitions(markdown) }
    /**
     * Find inference markers in markdown text.
     *
     * Returns byte offsets of every `[*inference*]` marker found in the text.
     *
     * **Returns:**
     *
     * A vector of byte offsets where inference markers appear.
     */
    fun findInferenceMarkers(markdown: String): List<Long> {
        val resultJson = XbergBridge.nativeFindInferenceMarkers(markdown)
        return mapper.readValue(resultJson, object : TypeReference<List<Long>>() {})
    }
    /**
     * Find inference markers in markdown text.
     *
     * Returns byte offsets of every `[*inference*]` marker found in the text.
     *
     * **Returns:**
     *
     * A vector of byte offsets where inference markers appear.
     */
    suspend fun findInferenceMarkersAsync(markdown: String): List<Long> =
        withContext(Dispatchers.IO) { findInferenceMarkers(markdown) }
    /**
     * Find unmarked claims in markdown text.
     *
     * Returns lines that assert a claim but carry neither a footnote citation anchor (`[^...]`)
     * nor an inference marker (`[*inference*]`).
     *
     * The heuristic is simple: a line that contains alphabetic words, ends with sentence punctuation,
     * and is not a heading, blank line, or markup-only line is considered a claim.
     * Exclude lines that appear in the citation block (after `---` + `<!-- citations ... -->`).
     *
     * **Returns:**
     *
     * A vector of trimmed line text strings for unmarked claims.
     */
    fun findUnmarkedClaims(markdown: String): List<String> {
        val resultJson = XbergBridge.nativeFindUnmarkedClaims(markdown)
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * Find unmarked claims in markdown text.
     *
     * Returns lines that assert a claim but carry neither a footnote citation anchor (`[^...]`)
     * nor an inference marker (`[*inference*]`).
     *
     * The heuristic is simple: a line that contains alphabetic words, ends with sentence punctuation,
     * and is not a heading, blank line, or markup-only line is considered a claim.
     * Exclude lines that appear in the citation block (after `---` + `<!-- citations ... -->`).
     *
     * **Returns:**
     *
     * A vector of trimmed line text strings for unmarked claims.
     */
    suspend fun findUnmarkedClaimsAsync(markdown: String): List<String> =
        withContext(Dispatchers.IO) { findUnmarkedClaims(markdown) }
    /**
     * Parse the structured citation block from markdown.
     *
     * Extracts citations from the block after a `---` thematic break followed by
     * `<!-- citations ... -->` comment. Parses each entry as:
     * `[^srcN]: <source>, <optional-locator>, excerpt: "<text>"`
     *
     * Returns parsed citations with source, optional locator, and optional excerpt.
     *
     * **Returns:**
     *
     * A vector of `Citation` entries parsed from the citation block.
     */
    fun parseCitations(markdown: String): List<Citation> {
        val resultJson = XbergBridge.nativeParseCitations(markdown)
        return mapper.readValue(resultJson, object : TypeReference<List<Citation>>() {})
    }
    /**
     * Parse the structured citation block from markdown.
     *
     * Extracts citations from the block after a `---` thematic break followed by
     * `<!-- citations ... -->` comment. Parses each entry as:
     * `[^srcN]: <source>, <optional-locator>, excerpt: "<text>"`
     *
     * Returns parsed citations with source, optional locator, and optional excerpt.
     *
     * **Returns:**
     *
     * A vector of `Citation` entries parsed from the citation block.
     */
    suspend fun parseCitationsAsync(markdown: String): List<Citation> =
        withContext(Dispatchers.IO) { parseCitations(markdown) }
    /**
     * Verify that an excerpt appears verbatim in source text.
     *
     * Performs exact matching by default. Also tries whitespace-normalized matching
     * (collapsing runs of whitespace on both sides) since PDF-extracted text often
     * has irregular spacing.
     *
     * **Returns:**
     *
     * `true` if the excerpt appears (exactly or with normalized whitespace), `false` otherwise.
     */
    fun verifyExcerpt(excerpt: String, sourceText: String): Boolean = XbergBridge.nativeVerifyExcerpt(excerpt, sourceText)
    /**
     * Chunk text for RAG retrieval, ensuring every chunk carries a `heading_path`.
     *
     * Delegates to `chunk_text` using the caller's config (defaulting to
     * `ChunkerType.Markdown` when the config uses the default `Text` type, so that
     * heading hierarchy is resolved).  After chunking, derives
     * `ChunkMetadata.heading_path` from each chunk's `heading_context`.
     *
     *   underlying splitter; use `ChunkerType.Markdown` for documents with ATX
     *   headings.
     *
     * **Returns:**
     *
     * A `ChunkingResult` where every chunk's `heading_path` is populated from its
     * `heading_context` (empty when the chunk is not under any heading).
     *
     * **Errors:**
     *
     * Propagates any error from the underlying chunker (e.g. invalid overlap).
     */
    fun chunkForRag(text: String, config: ChunkingConfig): ChunkingResult {
        val resultJson = XbergBridge.nativeChunkForRag(text, mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, ChunkingResult::class.java)
    }
    /**
     * Chunk text for RAG retrieval, ensuring every chunk carries a `heading_path`.
     *
     * Delegates to `chunk_text` using the caller's config (defaulting to
     * `ChunkerType.Markdown` when the config uses the default `Text` type, so that
     * heading hierarchy is resolved).  After chunking, derives
     * `ChunkMetadata.heading_path` from each chunk's `heading_context`.
     *
     *   underlying splitter; use `ChunkerType.Markdown` for documents with ATX
     *   headings.
     *
     * **Returns:**
     *
     * A `ChunkingResult` where every chunk's `heading_path` is populated from its
     * `heading_context` (empty when the chunk is not under any heading).
     *
     * **Errors:**
     *
     * Propagates any error from the underlying chunker (e.g. invalid overlap).
     */
    suspend fun chunkForRagAsync(text: String, config: ChunkingConfig): ChunkingResult =
        withContext(Dispatchers.IO) { chunkForRag(text, config) }
    /**
     * Compare two extraction results and return a structured diff.
     *
     * The comparison is purely structural — no I/O, no side effects. All fields
     * of `ExtractionDiff` are populated according to the provided `DiffOptions`.
     */
    fun compare(a: ExtractionResult, b: ExtractionResult, opts: DiffOptions): ExtractionDiff {
        val resultJson = XbergBridge.nativeCompare(mapper.writeValueAsString(a), mapper.writeValueAsString(b), mapper.writeValueAsString(opts))
        return mapper.readValue(resultJson, ExtractionDiff::class.java)
    }
    /**
     * Compare two extraction results and return a structured diff.
     *
     * The comparison is purely structural — no I/O, no side effects. All fields
     * of `ExtractionDiff` are populated according to the provided `DiffOptions`.
     */
    suspend fun compareAsync(a: ExtractionResult, b: ExtractionResult, opts: DiffOptions): ExtractionDiff =
        withContext(Dispatchers.IO) { compare(a, b, opts) }
    /**
     * Extract content from a pre-cropped image region using a VLM.
     *
     * The caller is responsible for cropping the page image to the region's bounding
     * box before calling this function. The `image_bytes` parameter must contain the
     * raw bytes of the **cropped** region image (JPEG, PNG, WebP, etc.).
     *
     * **Returns:**
     *
     * Extracted Markdown text from the VLM, or an error if the VLM call fails.
     *
     * **Errors:**
     *
     * - `Ocr` if the VLM call fails or returns no content.
     * - `MissingDependency` if the liter-llm client cannot
     *   be initialised.
     */
    fun extractRegionWithVlm(imageBytes: ByteArray, imageMime: String, regionKind: RegionKind, llmConfig: LlmConfig, customPrompt: String? = null): String = XbergBridge.nativeExtractRegionWithVlm(java.util.Base64.getEncoder().encodeToString(imageBytes), imageMime, mapper.writeValueAsString(regionKind), mapper.writeValueAsString(llmConfig), customPrompt ?: "")
    /**
     * Rerank documents asynchronously.
     *
     * Async counterpart to `rerank`. Offloads blocking ONNX inference to a
     * dedicated blocking thread pool via Tokio's `spawn_blocking`, keeping the
     * async executor free.
     *
     * Since v5.0.
     */
    /**
     * Rerank documents asynchronously.
     *
     * Async counterpart to `rerank`. Offloads blocking ONNX inference to a
     * dedicated blocking thread pool via Tokio's `spawn_blocking`, keeping the
     * async executor free.
     *
     * Since v5.0.
     */
    suspend fun rerankAsync(query: String, documents: List<String>, config: RerankerConfig): List<RerankedDocument> = withContext(Dispatchers.IO) { val resultJson = XbergBridge.nativeRerankAsync(query, mapper.writeValueAsString(documents), mapper.writeValueAsString(config)); mapper.readValue(resultJson, object : TypeReference<List<RerankedDocument>>() {}) }
    /**
     * Extract keywords from text using the specified algorithm.
     *
     * This is the unified entry point for keyword extraction. The algorithm
     * used is determined by `config.algorithm`.
     *
     * **Returns:**
     *
     * A vector of keywords sorted by relevance (highest score first).
     *
     * **Errors:**
     *
     * Returns an error if:
     *
     * - The specified algorithm feature is not enabled
     * - Keyword extraction fails
     */
    fun extractKeywords(text: String, config: KeywordConfig): List<Keyword> {
        val resultJson = XbergBridge.nativeExtractKeywords(text, mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, object : TypeReference<List<Keyword>>() {})
    }
    /**
     * Extract keywords from text using the specified algorithm.
     *
     * This is the unified entry point for keyword extraction. The algorithm
     * used is determined by `config.algorithm`.
     *
     * **Returns:**
     *
     * A vector of keywords sorted by relevance (highest score first).
     *
     * **Errors:**
     *
     * Returns an error if:
     *
     * - The specified algorithm feature is not enabled
     * - Keyword extraction fails
     */
    suspend fun extractKeywordsAsync(text: String, config: KeywordConfig): List<Keyword> =
        withContext(Dispatchers.IO) { extractKeywords(text, config) }
    /**
     * Analyze a document and determine the optimal chunking strategy.
     *
     * Decision logic (in priority order):
     *
     * 1. If user provides `disable_chunking` → no chunking
     * 2. If user provides page_ranges → use user overrides
     * 3. If chunking is not enabled → no chunking
     * 4. If format doesn't support chunking → no chunking
     * 5. If file is small (below both thresholds) and not force_chunking → no chunking
     * 6. If PDF has a substantial text layer AND !force_ocr → no chunking
     *    *(only when `heuristics-pdf` feature is enabled; otherwise skipped)*
     *
     * 7. Otherwise → chunk the document
     *
     * **Errors:**
     *
     * Returns an error only when the `heuristics-pdf` feature is active and
     * the PDF text-layer analysis itself returns a hard error.  In all other
     * cases the function returns a `ChunkingDecision`.
     */
    fun analyzeDocument(metadata: DocumentMetadata, config: HeuristicsConfig, documentBytes: ByteArray? = null): ChunkingDecision {
        val resultJson = XbergBridge.nativeAnalyzeDocument(mapper.writeValueAsString(metadata), mapper.writeValueAsString(config), documentBytes?.let { java.util.Base64.getEncoder().encodeToString(it) } ?: "")
        return mapper.readValue(resultJson, ChunkingDecision::class.java)
    }
    /**
     * Analyze a document and determine the optimal chunking strategy.
     *
     * Decision logic (in priority order):
     *
     * 1. If user provides `disable_chunking` → no chunking
     * 2. If user provides page_ranges → use user overrides
     * 3. If chunking is not enabled → no chunking
     * 4. If format doesn't support chunking → no chunking
     * 5. If file is small (below both thresholds) and not force_chunking → no chunking
     * 6. If PDF has a substantial text layer AND !force_ocr → no chunking
     *    *(only when `heuristics-pdf` feature is enabled; otherwise skipped)*
     *
     * 7. Otherwise → chunk the document
     *
     * **Errors:**
     *
     * Returns an error only when the `heuristics-pdf` feature is active and
     * the PDF text-layer analysis itself returns a hard error.  In all other
     * cases the function returns a `ChunkingDecision`.
     */
    suspend fun analyzeDocumentAsync(metadata: DocumentMetadata, config: HeuristicsConfig, documentBytes: ByteArray? = null): ChunkingDecision =
        withContext(Dispatchers.IO) { analyzeDocument(metadata, config, documentBytes) }
    /**
     * Analyze a document with user-specified chunk ranges.
     *
     * Creates a chunk plan based on user-provided page ranges.
     */
    fun analyzeWithUserChunks(userRanges: List<PageRange>, totalPages: Int, sizeBytes: Long, config: HeuristicsConfig): ChunkingDecision {
        val resultJson = XbergBridge.nativeAnalyzeWithUserChunks(mapper.writeValueAsString(userRanges), totalPages, sizeBytes, mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, ChunkingDecision::class.java)
    }
    /**
     * Analyze a document with user-specified chunk ranges.
     *
     * Creates a chunk plan based on user-provided page ranges.
     */
    suspend fun analyzeWithUserChunksAsync(userRanges: List<PageRange>, totalPages: Int, sizeBytes: Long, config: HeuristicsConfig): ChunkingDecision =
        withContext(Dispatchers.IO) { analyzeWithUserChunks(userRanges, totalPages, sizeBytes, config) }
    /**
     * Score a `ConfidenceSignals` triple into an `ExtractionConfidence` using
     * the supplied weights.
     *
     * When `signals.ocr_aggregate` is `null`, the OCR weight folds into
     * `text_coverage` so the weighted sum still totals 1.0.
     */
    fun scoreConfidence(signals: ConfidenceSignals, weights: ConfidenceWeights): ExtractionConfidence {
        val resultJson = XbergBridge.nativeScoreConfidence(mapper.writeValueAsString(signals), mapper.writeValueAsString(weights))
        return mapper.readValue(resultJson, ExtractionConfidence::class.java)
    }
    /**
     * Score a `ConfidenceSignals` triple into an `ExtractionConfidence` using
     * the supplied weights.
     *
     * When `signals.ocr_aggregate` is `null`, the OCR weight folds into
     * `text_coverage` so the weighted sum still totals 1.0.
     */
    suspend fun scoreConfidenceAsync(signals: ConfidenceSignals, weights: ConfidenceWeights): ExtractionConfidence =
        withContext(Dispatchers.IO) { scoreConfidence(signals, weights) }
    /**
     * Decision returned for pre-extraction rejection based on XLSX/PPTX-specific
     * resource bounds. Returns `Some(reason)` to reject; `null` to proceed.
     *
     * Callers must provide counts from a pre-extraction peek (e.g. parsing
     * `xl/workbook.xml` for sheet count).
     */
    fun checkFormatLimits(mimeType: String, sheetCount: Int? = null, workbookCells: Long? = null, embeddedCount: Int? = null, config: HeuristicsConfig): String? = XbergBridge.nativeCheckFormatLimits(mimeType, sheetCount ?: 0, workbookCells ?: 0L, embeddedCount ?: 0, mapper.writeValueAsString(config))
    /**
     * Derive document boundaries from an already-produced `ExtractionResult`.
     *
     * Builds a `MultidocInput` from `result.pages` (one `PageSignals` per
     * `PageContent` entry), then delegates to `detect_boundaries`.
     *
     * # Fallback behaviour
     *
     * - If `result.pages` is `null` or empty the whole document is treated as a
     *   single document: returns `[Start(1), End(1)]`, matching the contract of
     *   `detect_boundaries` for a one-page input.
     *
     * # Text density
     *
     * `PageContent` does not carry a pre-computed density score.
     * This function approximates density as
     * `non_whitespace_chars / total_chars` (clamped to `[0.0, 1.0]`), which is a
     * reasonable proxy for how text-dense a page is relative to itself.  Pass a
     * custom `MultidocInput` to `detect_boundaries` directly when you need a
     * higher-fidelity density measurement (e.g. chars-per-pt² from a PDF extractor).
     */
    fun boundariesFromExtractionResult(result: ExtractionResult, thresholds: MultidocThresholds): List<DocumentBoundary> {
        val resultJson = XbergBridge.nativeBoundariesFromExtractionResult(mapper.writeValueAsString(result), mapper.writeValueAsString(thresholds))
        return mapper.readValue(resultJson, object : TypeReference<List<DocumentBoundary>>() {})
    }
    /**
     * Derive document boundaries from an already-produced `ExtractionResult`.
     *
     * Builds a `MultidocInput` from `result.pages` (one `PageSignals` per
     * `PageContent` entry), then delegates to `detect_boundaries`.
     *
     * # Fallback behaviour
     *
     * - If `result.pages` is `null` or empty the whole document is treated as a
     *   single document: returns `[Start(1), End(1)]`, matching the contract of
     *   `detect_boundaries` for a one-page input.
     *
     * # Text density
     *
     * `PageContent` does not carry a pre-computed density score.
     * This function approximates density as
     * `non_whitespace_chars / total_chars` (clamped to `[0.0, 1.0]`), which is a
     * reasonable proxy for how text-dense a page is relative to itself.  Pass a
     * custom `MultidocInput` to `detect_boundaries` directly when you need a
     * higher-fidelity density measurement (e.g. chars-per-pt² from a PDF extractor).
     */
    suspend fun boundariesFromExtractionResultAsync(result: ExtractionResult, thresholds: MultidocThresholds): List<DocumentBoundary> =
        withContext(Dispatchers.IO) { boundariesFromExtractionResult(result, thresholds) }
    /**
     * Detect document boundaries in a multi-document PDF.
     *
     * Returns a list of detected boundaries, always including implicit boundaries
     * at start (page 1) and end (page_count).  Boundaries are returned in ascending
     * order of `start_page`.
     *
     * **Returns:**
     *
     * Ordered list of document boundaries.
     */
    fun detectBoundaries(input: MultidocInput, thresholds: MultidocThresholds): List<DocumentBoundary> {
        val resultJson = XbergBridge.nativeDetectBoundaries(mapper.writeValueAsString(input), mapper.writeValueAsString(thresholds))
        return mapper.readValue(resultJson, object : TypeReference<List<DocumentBoundary>>() {})
    }
    /**
     * Detect document boundaries in a multi-document PDF.
     *
     * Returns a list of detected boundaries, always including implicit boundaries
     * at start (page 1) and end (page_count).  Boundaries are returned in ascending
     * order of `start_page`.
     *
     * **Returns:**
     *
     * Ordered list of document boundaries.
     */
    suspend fun detectBoundariesAsync(input: MultidocInput, thresholds: MultidocThresholds): List<DocumentBoundary> =
        withContext(Dispatchers.IO) { detectBoundaries(input, thresholds) }
    /**
     * Decide which call mode best fits this document.
     *
     * Rules applied in order:
     *
     * 1. `image/ *` → `StructuredCallMode.VisionOnly` (no text layer to start from).
     * 2. `application/pdf` → `StructuredCallMode.TextOnly` regardless of
     *    `text_coverage` or embedded image count.  Xberg's OCR + text-layer
     *    extraction produces text for scanned PDFs; the orchestrator's
     *    post-call confidence gate handles any vision escalation actually needed.
     *
     * 3. DOCX / `text/html` / `text/ *` / `application/json` / `application/xml` /
     *    `application/rtf` with `avg_chars_per_page > docx_text_min_density`
     *    → `StructuredCallMode.TextOnly`.
     *
     * 4. Anything else → `StructuredCallMode.Skip`.
     *
     * After rule selection two post-rule promotions apply (in order):
     *
     * - `user_force_vision` promotes `TextOnly` → `TextPlusVision`
     *   (`Skip` stays `Skip` — caller meant to opt out).
     *
     * - `enable_vision_fallback` promotes `TextOnly` →
     *   `TextOnlyWithVisionFallback` (does **not** upgrade `TextPlusVision` or
     *   `Skip`).
     */
    fun chooseCallMode(input: StructuredInput, t: StructuredThresholds): StructuredCallMode {
        val resultJson = XbergBridge.nativeChooseCallMode(mapper.writeValueAsString(input), mapper.writeValueAsString(t))
        return mapper.readValue(resultJson, StructuredCallMode::class.java)
    }
    /**
     * Decide which call mode best fits this document.
     *
     * Rules applied in order:
     *
     * 1. `image/ *` → `StructuredCallMode.VisionOnly` (no text layer to start from).
     * 2. `application/pdf` → `StructuredCallMode.TextOnly` regardless of
     *    `text_coverage` or embedded image count.  Xberg's OCR + text-layer
     *    extraction produces text for scanned PDFs; the orchestrator's
     *    post-call confidence gate handles any vision escalation actually needed.
     *
     * 3. DOCX / `text/html` / `text/ *` / `application/json` / `application/xml` /
     *    `application/rtf` with `avg_chars_per_page > docx_text_min_density`
     *    → `StructuredCallMode.TextOnly`.
     *
     * 4. Anything else → `StructuredCallMode.Skip`.
     *
     * After rule selection two post-rule promotions apply (in order):
     *
     * - `user_force_vision` promotes `TextOnly` → `TextPlusVision`
     *   (`Skip` stays `Skip` — caller meant to opt out).
     *
     * - `enable_vision_fallback` promotes `TextOnly` →
     *   `TextOnlyWithVisionFallback` (does **not** upgrade `TextPlusVision` or
     *   `Skip`).
     */
    suspend fun chooseCallModeAsync(input: StructuredInput, t: StructuredThresholds): StructuredCallMode =
        withContext(Dispatchers.IO) { chooseCallMode(input, t) }
    /**
     * Calculate a chunking plan for a document.
     *
     * **Returns:**
     *
     * A `ChunkPlan` with optimal chunk boundaries.
     */
    fun calculateChunkPlan(pageCount: Int, sizeBytes: Long, needsOcr: Boolean, config: HeuristicsConfig): ChunkPlan {
        val resultJson = XbergBridge.nativeCalculateChunkPlan(pageCount, sizeBytes, needsOcr, mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, ChunkPlan::class.java)
    }
    /**
     * Calculate a chunking plan for a document.
     *
     * **Returns:**
     *
     * A `ChunkPlan` with optimal chunk boundaries.
     */
    suspend fun calculateChunkPlanAsync(pageCount: Int, sizeBytes: Long, needsOcr: Boolean, config: HeuristicsConfig): ChunkPlan =
        withContext(Dispatchers.IO) { calculateChunkPlan(pageCount, sizeBytes, needsOcr, config) }
    /**
     * Calculate a chunk plan from user-specified page ranges.
     *
     * Validates and processes user overrides into a proper chunk plan.
     */
    fun calculatePlanFromOverrides(userChunks: List<PageRange>, totalPages: Int, sizeBytes: Long, config: HeuristicsConfig): ChunkPlan {
        val resultJson = XbergBridge.nativeCalculatePlanFromOverrides(mapper.writeValueAsString(userChunks), totalPages, sizeBytes, mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, ChunkPlan::class.java)
    }
    /**
     * Calculate a chunk plan from user-specified page ranges.
     *
     * Validates and processes user overrides into a proper chunk plan.
     */
    suspend fun calculatePlanFromOverridesAsync(userChunks: List<PageRange>, totalPages: Int, sizeBytes: Long, config: HeuristicsConfig): ChunkPlan =
        withContext(Dispatchers.IO) { calculatePlanFromOverrides(userChunks, totalPages, sizeBytes, config) }
    /** Stable sha256 fingerprint of `raw`, formatted as `sha256:<hex>`. */
    fun fingerprint(raw: ByteArray): String = XbergBridge.nativeFingerprint(java.util.Base64.getEncoder().encodeToString(raw))
    /**
     * Resolve `(preset, custom_schema_override, context)` into a `ResolvedPreset`.
     *
     * - `custom_schema` overrides `preset.schema` when set.
     * - `context` substitutes `{{key}}` tokens in `preset.context_template`; the
     *   rendered string is appended to `system_prompt` so the model sees it.
     */
    fun resolve(preset: Preset, customSchema: String? = null, context: Map<String, String>): ResolvedPreset {
        val resultJson = XbergBridge.nativeResolve(mapper.writeValueAsString(preset), customSchema ?: "", mapper.writeValueAsString(context))
        return mapper.readValue(resultJson, ResolvedPreset::class.java)
    }
    /**
     * Resolve `(preset, custom_schema_override, context)` into a `ResolvedPreset`.
     *
     * - `custom_schema` overrides `preset.schema` when set.
     * - `context` substitutes `{{key}}` tokens in `preset.context_template`; the
     *   rendered string is appended to `system_prompt` so the model sees it.
     */
    suspend fun resolveAsync(preset: Preset, customSchema: String? = null, context: Map<String, String>): ResolvedPreset =
        withContext(Dispatchers.IO) { resolve(preset, customSchema, context) }
    /**
     * Extract structured JSON from a document using JSON-encoded preset spec and options.
     *
     * This is the synchronous JSON-in / JSON-out entry point suitable for FFI and
     * language-binding call paths.
     *
     *   `cache`).  Pass `"{}"` to use all defaults.
     *
     * **Returns:**
     *
     * JSON-serialised `StructuredOutput` on success.
     *
     * **Errors:**
     *
     * Returns `Validation` when either JSON argument is
     * malformed.  All other failures from the underlying
     * `extract_structured_sync` call are mapped onto `XbergError`
     * via `From<StructuredError>`.
     */
    fun extractStructuredJson(bytes: ByteArray, mime: String, presetSpecJson: String, optionsJson: String): String = XbergBridge.nativeExtractStructuredJson(java.util.Base64.getEncoder().encodeToString(bytes), mime, presetSpecJson, optionsJson)
    /**
     * Split a multi-document PDF and extract structured JSON from each segment,
     * returning a JSON array of `StructuredOutput` objects.
     *
     * Non-PDF documents are passed through as a single-element array.
     *
     * Same as `extract_structured_json`.
     *
     * **Returns:**
     *
     * JSON-serialised `List<StructuredOutput>` (a JSON array) on success.
     *
     * **Errors:**
     *
     * Returns `Validation` when either JSON argument is
     * malformed.  All other failures from the underlying
     * `split_and_extract_sync` call are mapped onto `XbergError`
     * via `From<StructuredError>`.
     */
    fun splitAndExtractJson(bytes: ByteArray, mime: String, presetSpecJson: String, optionsJson: String): String = XbergBridge.nativeSplitAndExtractJson(java.util.Base64.getEncoder().encodeToString(bytes), mime, presetSpecJson, optionsJson)
    /**
     * Render a single PDF page to PNG bytes.
     *
     * Returns raw PNG-encoded bytes for the specified page at the given DPI.
     * Uses pdf_oxide with tiny-skia for pure-Rust rendering.
     *
     * For pages with extreme dimensions (very wide vector diagrams, etc.) the
     * effective DPI may be automatically reduced to avoid rasterizer failure.
     * A warning is logged when this happens.
     *
     * **Errors:**
     *
     * Returns `XbergError.Parsing` if the PDF cannot be opened, authenticated,
     * or rendered, or if `page_index` is out of range.
     */
    fun renderPdfPageToPng(pdfBytes: ByteArray, pageIndex: Long, dpi: Int? = null, password: String? = null): ByteArray = XbergBridge.nativeRenderPdfPageToPng(java.util.Base64.getEncoder().encodeToString(pdfBytes), pageIndex, dpi ?: 0, password ?: "")
    /**
     * Count the pages in a PDF without rendering any of them.
     *
     * Opens the document and returns its page count from the PDF structure. No page
     * is rasterized, so this is cheap relative to `render_pdf_page_to_png` — use it
     * when you only need the count (e.g. to drive a render loop over the pages).
     *
     * **Errors:**
     *
     * Returns `XbergError.Parsing` if the PDF cannot be opened, authenticated,
     * or its page count read.
     */
    fun pdfPageCount(pdfBytes: ByteArray, password: String? = null): Long = XbergBridge.nativePdfPageCount(java.util.Base64.getEncoder().encodeToString(pdfBytes), password ?: "")
    /**
     * Caption a single image from bytes.
     *
     *   `RegionKind.Caption` prompt when `null`.
     *
     * **Returns:**
     *
     * The generated caption text.
     *
     * **Errors:**
     *
     * Returns an error if the VLM call fails or if image format detection fails.
     */
    fun captionImage(imageBytes: ByteArray, llmConfig: LlmConfig, customPrompt: String? = null): String = XbergBridge.nativeCaptionImage(java.util.Base64.getEncoder().encodeToString(imageBytes), mapper.writeValueAsString(llmConfig), customPrompt ?: "")
    /**
     * Caption a single image from a file path.
     *
     *   `RegionKind.Caption` prompt when `null`.
     *
     * **Returns:**
     *
     * The generated caption text.
     *
     * **Errors:**
     *
     * Returns an error if the file cannot be read, if image format detection fails,
     * or if the VLM call fails.
     */
    fun captionImageFile(path: String, llmConfig: LlmConfig, customPrompt: String? = null): String = XbergBridge.nativeCaptionImageFile(path, mapper.writeValueAsString(llmConfig), customPrompt ?: "")
    /**
     * Detect the MIME type of a file at the given path.
     *
     * Uses the file extension and optionally the file content to determine the MIME type.
     * Set `check_exists` to `true` to verify the file exists before detection.
     */
    fun detectMimeType(path: String, checkExists: Boolean): String = XbergBridge.nativeDetectMimeType(path, checkExists)
    /**
     * Embed a list of texts using the configured embedding model.
     *
     * Returns a 2D vector where each inner vector is the embedding for the corresponding text.
     */
    fun embedTexts(texts: List<String>, config: EmbeddingConfig): List<List<Float>> {
        val resultJson = XbergBridge.nativeEmbedTexts(mapper.writeValueAsString(texts), mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, object : TypeReference<List<List<Float>>>() {})
    }
    /**
     * Embed a list of texts using the configured embedding model.
     *
     * Returns a 2D vector where each inner vector is the embedding for the corresponding text.
     */
    suspend fun embedTextsAsync(texts: List<String>, config: EmbeddingConfig): List<List<Float>> =
        withContext(Dispatchers.IO) { embedTexts(texts, config) }
    /**
     * Get an embedding preset by name.
     *
     * Returns `null` if no preset with the given name exists. Returns an owned
     * clone so the value is safe to pass across FFI boundaries.
     */
    fun getEmbeddingPreset(name: String): String? = XbergBridge.nativeGetEmbeddingPreset(name)
    /**
     * List the names of all available embedding presets.
     *
     * Returns owned `String`s so the values are safe to pass across FFI boundaries.
     */
    fun listEmbeddingPresets(): List<String> {
        val resultJson = XbergBridge.nativeListEmbeddingPresets()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List the names of all available embedding presets.
     *
     * Returns owned `String`s so the values are safe to pass across FFI boundaries.
     */
    suspend fun listEmbeddingPresetsAsync(): List<String> =
        withContext(Dispatchers.IO) { listEmbeddingPresets() }
    /**
     * Rerank a list of documents by relevance to a query.
     *
     * Returns documents sorted descending by score. Applies `top_k` truncation if
     * configured.
     *
     * **Errors:**
     *
     * - `XbergError.Validation` if `query` is empty or blank.
     * - `XbergError.MissingDependency` if ONNX Runtime is not installed (ONNX path).
     * - `XbergError.Reranking` if the preset is unknown or model download fails.
     *
     * Since v5.0.
     */
    fun rerank(query: String, documents: List<String>, config: RerankerConfig): List<RerankedDocument> {
        val resultJson = XbergBridge.nativeRerank(query, mapper.writeValueAsString(documents), mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, object : TypeReference<List<RerankedDocument>>() {})
    }
    /**
     * Get a reranker preset by name.
     *
     * Returns `null` if no preset with the given name exists. Returns an owned
     * clone so the value is safe to pass across FFI boundaries.
     *
     * Since v5.0.
     */
    fun getRerankerPreset(name: String): String? = XbergBridge.nativeGetRerankerPreset(name)
    /**
     * List the names of all available reranker presets.
     *
     * Returns owned `String`s so the values are safe to pass across FFI boundaries.
     *
     * Since v5.0.
     */
    fun listRerankerPresets(): List<String> {
        val resultJson = XbergBridge.nativeListRerankerPresets()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List the names of all available reranker presets.
     *
     * Returns owned `String`s so the values are safe to pass across FFI boundaries.
     *
     * Since v5.0.
     */
    suspend fun listRerankerPresetsAsync(): List<String> =
        withContext(Dispatchers.IO) { listRerankerPresets() }
}
