// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:355422f83c20a8c944a5fe72e7ed4f9d6677eccadc0e42c80632042bd834c394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Chunk response with chunks and metadata.
 */
public record ChunkResponse(
    /** List of chunks */
    List<String> chunks,
    /** Total number of chunks */
    @JsonProperty("chunk_count") long chunkCount,
    /** Configuration used for chunking */
    String config,
    /** Input text size in bytes */
    @JsonProperty("input_size_bytes") long inputSizeBytes,
    /** Chunker type used for chunking */
    @JsonProperty("chunker_type") String chunkerType
) {
}
