// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:844ff09b2359f968ea569507c882555728353219414a9958f8a797b4818f08aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Configuration for email extraction.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record EmailConfig(@JsonProperty("msg_fallback_codepage") Optional<Integer> msgFallbackCodepage) {
    public static EmailConfigBuilder builder() {
        return new EmailConfigBuilder();
    }
}
