// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4001a48eb806f6f50b125457fd75ded87092b78bc1bfe88dfaa34c0d66cb1682
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Email attachment representation.
 *
 * Contains metadata and optionally the content of an email attachment.
 */
public record EmailAttachment(
    /** Attachment name (from Content-Disposition header) */
    Optional<String> name,
    /** Filename of the attachment */
    Optional<String> filename,
    /** MIME type of the attachment */
    @JsonProperty("mime_type") Optional<String> mimeType,
    /** Size in bytes */
    Optional<Long> size,
    /** Whether this attachment is an image */
    @JsonProperty("is_image") boolean isImage,
    /** Attachment data (if extracted). */
    Optional<byte[]> data
) {
}
