// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:34b880a451ac24e65433cf10fdf3948cd7774eb19cd054594687d00d5fdec807
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Per-file extraction configuration overrides for batch processing.
 *
 * All fields are {@code Option&lt;T&gt;} — {@code None} means "use the batch-level default." This type is used with
 * {@code batch_extract_files} and {@code batch_extract_bytes} to allow heterogeneous extraction settings within a single batch.
 *
 * # Excluded Fields
 *
 * The following {@code ExtractionConfig} fields are batch-level only and cannot be overridden per file: -
 * {@code max_concurrent_extractions} — controls batch parallelism - {@code use_cache} — global caching policy - {@code acceleration} —
 * shared ONNX execution provider - {@code security_limits} — global archive security policy
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FileExtractionConfigBuilder.class)
public record FileExtractionConfig(@Nullable Boolean enableQualityProcessing, @Nullable OcrConfig ocr, @Nullable Boolean forceOcr,
        @Nullable List<Long> forceOcrPages, @Nullable Boolean disableOcr, @Nullable ChunkingConfig chunking,
        @Nullable ContentFilterConfig contentFilter, @Nullable ImageExtractionConfig images, @Nullable PdfConfig pdfOptions,
        @Nullable TokenReductionOptions tokenReduction, @Nullable LanguageDetectionConfig languageDetection, @Nullable PageConfig pages,
        @Nullable KeywordConfig keywords, @Nullable PostProcessorConfig postprocessor, @Nullable String htmlOptions,
        @Nullable ResultFormat resultFormat, @Nullable OutputFormat outputFormat, @Nullable Boolean includeDocumentStructure,
        @Nullable LayoutDetectionConfig layout, @Nullable Long timeoutSecs, @Nullable TreeSitterConfig treeSitter,
        @Nullable StructuredExtractionConfig structuredExtraction) {
    public static FileExtractionConfigBuilder builder() {
        return new FileExtractionConfigBuilder();
    }

    /**
     * Parse a {@code FileExtractionConfig} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException
     *             if the JSON cannot be deserialised.
     */
    public static FileExtractionConfig fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper().registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                    .findAndRegisterModules().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, FileExtractionConfig.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse FileExtractionConfig from JSON: " + e.getMessage(), e);
        }
    }
}
