// DO NOT EDIT - auto-generated by alef
// alef:hash:70c73eb6e36e725ef0049ab0b5c298e7eedcab5a26ca482859b21c1d5a7cfd2e
package dev.kreuzberg;

/**
 * Main error type for all Kreuzberg operations.
 *
 * All errors in Kreuzberg use this enum, which preserves error chains and provides context for debugging.
 *
 * # Variants
 *
 * - {@code Io} - File system and I/O errors (always bubble up) - {@code Parsing} - Document parsing errors (corrupt
 * files, unsupported features) - {@code Ocr} - OCR processing errors - {@code Validation} - Input validation errors
 * (invalid paths, config, parameters) - {@code Cache} - Cache operation errors (non-fatal, can be ignored) -
 * {@code ImageProcessing} - Image manipulation errors - {@code Serialization} - JSON/MessagePack serialization errors -
 * {@code MissingDependency} - Missing optional dependencies (tesseract, etc.) - {@code Plugin} - Plugin-specific errors
 * - {@code LockPoisoned} - Mutex/RwLock poisoning (should not happen in normal operation) - {@code UnsupportedFormat} -
 * Unsupported MIME type or file format - {@code Other} - Catch-all for uncommon errors
 */
public class KreuzbergErrorException extends Exception {
    /** Creates a new KreuzbergErrorException with the given message. */
    public KreuzbergErrorException(final String message) {
        super(message);
    }

    /** Creates a new KreuzbergErrorException with the given message and cause. */
    public KreuzbergErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
