// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a0a11c995fddf21a0ecb1c242d58324fbca1f01f30b2869ad86fd3352d80c9e6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single layout detection result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record LayoutDetection(@JsonProperty("class_name") LayoutClass className, float confidence, BBox bbox) {
}
