// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a28506c63fd7d8ecf125ee06ddfeb15449c7371b43461bf41974984de51cae2e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Extraction result metadata.
 *
 * Contains common fields applicable to all formats, format-specific metadata
 * via a discriminated union, and additional custom fields from postprocessors.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MetadataBuilder.class)
public record Metadata(
    @Nullable String title,
    @Nullable String subject,
    @Nullable List<String> authors,
    @Nullable List<String> keywords,
    @Nullable String language,
    @Nullable @JsonProperty("createdAt") @com.fasterxml.jackson.annotation.JsonAlias("created_at") String createdAt,
    @Nullable @JsonProperty("modifiedAt") @com.fasterxml.jackson.annotation.JsonAlias("modified_at") String modifiedAt,
    @Nullable @JsonProperty("createdBy") @com.fasterxml.jackson.annotation.JsonAlias("created_by") String createdBy,
    @Nullable @JsonProperty("modifiedBy") @com.fasterxml.jackson.annotation.JsonAlias("modified_by") String modifiedBy,
    @Nullable PageStructure pages,
    @JsonDeserialize(using = FormatMetadataDeserializer.class) @Nullable FormatMetadata format,
    @Nullable @JsonProperty("imagePreprocessing") @com.fasterxml.jackson.annotation.JsonAlias("image_preprocessing") ImagePreprocessingMetadata imagePreprocessing,
    @Nullable @JsonProperty("jsonSchema") @com.fasterxml.jackson.annotation.JsonAlias("json_schema") Object jsonSchema,
    @Nullable ErrorMetadata error,
    @Nullable @JsonProperty("extractionDurationMs") @com.fasterxml.jackson.annotation.JsonAlias("extraction_duration_ms") Long extractionDurationMs,
    @Nullable String category,
    @Nullable List<String> tags,
    @Nullable @JsonProperty("documentVersion") @com.fasterxml.jackson.annotation.JsonAlias("document_version") String documentVersion,
    @Nullable @JsonProperty("abstractText") @com.fasterxml.jackson.annotation.JsonAlias("abstract_text") String abstractText,
    @Nullable @JsonProperty("outputFormat") @com.fasterxml.jackson.annotation.JsonAlias("output_format") String outputFormat,
    @JsonProperty("ocrUsed") @com.fasterxml.jackson.annotation.JsonAlias("ocr_used") boolean ocrUsed,
    Map<String, Object> additional
) {
    public static MetadataBuilder builder() {
        return new MetadataBuilder();
    }

    /**
     * Parse a {@code Metadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static Metadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, Metadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse Metadata from JSON: " + e.getMessage(), e);
        }
    }
}
