// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:355422f83c20a8c944a5fe72e7ed4f9d6677eccadc0e42c80632042bd834c394
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OpenWebUI "External" engine response format.
 *
 * Returned by {@code PUT /process} for the OpenWebUI external document loader.
 */
public record OpenWebDocumentResponse(
    /** Extracted text content */
    @JsonProperty("page_content") String pageContent,
    /** Document metadata */
    String metadata
) {
}
