// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ecc65e6580942597854e9a6d476ab2f0ab8248aa3a21bff07b8c9153af233988
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * RAKE-specific parameters.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonPOJOBuilder(withPrefix = "with")
public class RakeParamsBuilder {

    private long minWordLength = 0;
    private long maxWordsPerPhrase = 0;

    /** Sets the minWordLength field. */
    public RakeParamsBuilder withMinWordLength(final long value) {
        this.minWordLength = value;
        return this;
    }

    /** Sets the maxWordsPerPhrase field. */
    public RakeParamsBuilder withMaxWordsPerPhrase(final long value) {
        this.maxWordsPerPhrase = value;
        return this;
    }

    /** Builds the RakeParams instance. */
    public RakeParams build() {
        return new RakeParams(
            minWordLength,
            maxWordsPerPhrase
        );
    }
}
