// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc5f3762a515127acd0bdbd655b135af0fcb1f5328a337a50c787edeabb5bb29
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Individual table cell with content and optional styling.
 *
 * Future extension point for rich table support with cell-level metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class TableCellBuilder {

    private String content = "";
    @JsonProperty("rowSpan")
    @com.fasterxml.jackson.annotation.JsonAlias("row_span")
    private long rowSpan = 0;
    @JsonProperty("colSpan")
    @com.fasterxml.jackson.annotation.JsonAlias("col_span")
    private long colSpan = 0;
    @JsonProperty("isHeader")
    @com.fasterxml.jackson.annotation.JsonAlias("is_header")
    private boolean isHeader = false;

    /** Sets the content field. */
    public TableCellBuilder withContent(final String value) {
        this.content = value;
        return this;
    }

    /** Sets the rowSpan field. */
    @JsonProperty("rowSpan")
    @com.fasterxml.jackson.annotation.JsonAlias("row_span")
    public TableCellBuilder withRowSpan(final long value) {
        this.rowSpan = value;
        return this;
    }

    /** Sets the colSpan field. */
    @JsonProperty("colSpan")
    @com.fasterxml.jackson.annotation.JsonAlias("col_span")
    public TableCellBuilder withColSpan(final long value) {
        this.colSpan = value;
        return this;
    }

    /** Sets the isHeader field. */
    @JsonProperty("isHeader")
    @com.fasterxml.jackson.annotation.JsonAlias("is_header")
    public TableCellBuilder withIsHeader(final boolean value) {
        this.isHeader = value;
        return this;
    }

    /** Builds the TableCell instance. */
    public TableCell build() {
        return new TableCell(
            content,
            rowSpan,
            colSpan,
            isHeader
        );
    }
}
