// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4001a48eb806f6f50b125457fd75ded87092b78bc1bfe88dfaa34c0d66cb1682
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Plain text and Markdown extraction result.
 *
 * Contains the extracted text along with statistics and,
 * for Markdown files, structural elements like headers and links.
 */
public record TextExtractionResult(
    /** Extracted text content */
    String content,
    /** Number of lines */
    @JsonProperty("line_count") long lineCount,
    /** Number of words */
    @JsonProperty("word_count") long wordCount,
    /** Number of characters */
    @JsonProperty("character_count") long characterCount,
    /** Markdown headers (text only, Markdown files only) */
    Optional<List<String>> headers,
    /** Markdown links as (text, URL) tuples (Markdown files only) */
    Optional<List<String>> links,
    /** Code blocks as (language, code) tuples (Markdown files only) */
    @JsonProperty("code_blocks") Optional<List<String>> codeBlocks
) {
}
