// DO NOT EDIT - auto-generated by alef
// alef:hash:8a7be6f38fb1624e8a52b015a29cdbad1e5aad2d384ed00e50fe71b237f15945
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
