// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4001a48eb806f6f50b125457fd75ded87092b78bc1bfe88dfaa34c0d66cb1682
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * YAKE-specific parameters.
 */
public record YakeParams(@JsonProperty("window_size") long windowSize) {
    public static YakeParamsBuilder builder() {
        return new YakeParamsBuilder();
    }
}
