# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1be4948160182a5fac565fc4fd1f9efae553b98fcacea46fbcd0fa657e190784
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
