# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0faa091a47b256ebba1e8379b247a65f35e0fc46e65b004a4271f18fa009dbee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          attributes: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            attributes: nil
end
