# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:13fcf389e0a8b12803971ee7eb506c6d65a3feefd32cf707c91e176c54e06591
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: [],
            node_types: []
end
