# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6214b04a756fce86270e57c863ac374cbbf87056c1a48b875f7575745d9befa9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: [],
            node_types: []
end
