# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:648b530f18ca06c9a87a6bcd4bb39ab2cac431866ab3eaac0b00c471028a5b85
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for DOCX"

  defstruct application: "",
            app_version: "",
            template: "",
            total_time: 0,
            pages: 0,
            words: 0,
            characters: 0,
            characters_with_spaces: 0,
            lines: 0,
            paragraphs: 0,
            company: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false
end
