# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:212fad49463e234fe03ed6dbee04f10c79e9e60e12a1a08d973f0cf7ec67bd48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingPreset do
  @moduledoc "Preset configurations for common RAG use cases."

  defstruct name: "",
            chunk_size: 0,
            overlap: 0,
            model_repo: "",
            pooling: "",
            model_file: "",
            dimensions: 0,
            description: ""
end
