# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb028a083813a5f0c2e052fe5ce5747090d957b5cb2ec489bfd03c4f50b3600f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            mime_type: nil
end
