# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b369ecbf91ca4908d053fb4663f8db42ba396a70f30f614f2ddb0732311e112f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
