# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4a52ab45e2045c124b411483cc8dcef4fa6db85f976e3b280f9b9ba0703540c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlMetadata do
  @moduledoc "HTML metadata extracted from HTML documents."

  defstruct title: "",
            description: "",
            keywords: [],
            author: "",
            canonical_url: "",
            base_href: "",
            language: "",
            text_direction: :left_to_right,
            open_graph: %{},
            twitter_card: %{},
            meta_tags: %{},
            headers: [],
            links: [],
            images: [],
            structured_data: []
end
