# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5accea078f7938d804bf8658b63f0682c884bde6bb8f0e9f00f1ca4c9ae40a0e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingConfig do
  @moduledoc """
  Image preprocessing configuration for OCR.

  These settings control how images are preprocessed before OCR to improve
  text recognition quality. Different preprocessing strategies work better
  for different document types.
  """

  @typedoc "Image preprocessing configuration for OCR."
  @type t :: %__MODULE__{
          target_dpi: integer(),
          auto_rotate: boolean(),
          deskew: boolean(),
          denoise: boolean(),
          contrast_enhance: boolean(),
          binarization_method: String.t() | nil,
          invert_colors: boolean()
        }

  defstruct target_dpi: 300,
            auto_rotate: true,
            deskew: true,
            denoise: false,
            contrast_enhance: false,
            binarization_method: "otsu",
            invert_colors: false
end
