# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4001a48eb806f6f50b125457fd75ded87092b78bc1bfe88dfaa34c0d66cb1682
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  defstruct det_model: "",
            cls_model: "",
            rec_model: "",
            dict_file: ""
end
