# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bece8cf56b5dc19946411218a74b70476c3ce48446e9504c678d5c309c0917b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.MultidocThresholds do
  @moduledoc """
  Thresholds for multi-document boundary detection.

  All fields are public; callers override any subset via struct-update syntax.
  """

  @typedoc "Thresholds for multi-document boundary detection."
  @type t :: %__MODULE__{
          density_shift_threshold: float(),
          bigram_overlap_min: float()
        }

  defstruct density_shift_threshold: 0.3,
            bigram_overlap_min: 0.1

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
