# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:88946bee139c274ddadf0c1b3e84697ea829a632216439c4507292e2d5f49970
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
