# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:35f1339955633e1488b61e05a7d8a8b9db6c4ffe1be3e2c374482f956459d996
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc "PowerPoint presentation metadata."

  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0
end
