# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:752b2a1c31c5d6e6fad1b48d714494c11203a1c3b125ed58b215dd80e60c363c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableProperties do
  @moduledoc "Table-level properties from `<w:tblPr>`."

  defstruct style_id: "",
            width: "",
            alignment: "",
            layout: "",
            look: "",
            borders: "",
            cell_margins: "",
            indent: "",
            caption: ""
end
