# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:811c6fb425bc3b653df9212a2990b9f2dd1a6579fae9a548eb8560a4eccb68fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmResponse do
  @moduledoc "Cache warm response."

  defstruct cache_dir: "",
            downloaded: [],
            already_cached: []
end
