# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7682ceb2987f694a705f0a779b3385227ab43982dbaa0bea6046f752d87c56c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
