// DO NOT EDIT - auto-generated by alef
// alef:hash:16cef683b5e0fc9e6955649fdc36679c86b7b917096a199706dc197d20ab43b3
package io.xberg;

/**
 * The extraction was cancelled via a `CancellationToken`.
 */
public class CancelledException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CancelledException with the given message. */
  public CancelledException(final String message) {
    super(message);
  }

  /** Creates a new CancelledException with the given message and cause. */
  public CancelledException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
