// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Provenance of a cited field value.
 */
@SuppressWarnings("PMD")
public enum CitationSource {
    /**
     * Value came from the LLM only.
     */
    Llm("llm"),
    /**
     * Value came from extracted source data only.
     */
    Extracted("extracted"),
    /**
     * Value fused from both LLM output and extracted source data.
     */
    Fused("fused"),
    /**
     * No provenance could be attributed.
     */
    None("none");


    /** The string value. */
    private final String value;

    CitationSource(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static CitationSource fromValue(final String value) {
        for (CitationSource e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown CitationSource value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
