// DO NOT EDIT - auto-generated by alef
// alef:hash:597bd1ea631d4ac6d358d121dc5791450b5d9aaaabe53fda1e43bef2af72e4ac
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new DeserializeException with the given message. */
    public DeserializeException(final String message) {
        super(message);
    }

    /** Creates a new DeserializeException with the given message and cause. */
    public DeserializeException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
