// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:446748155774867df28fecd60b1f51d93e20d7476cf9f2aad1cd588a1cf0950e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Types of inline elements in Djot.
 */
@SuppressWarnings("PMD")
public enum InlineType {
    /**
     * Plain text run.
     */
    Text("text"),
    /**
     * Bold / strong emphasis.
     */
    Strong("strong"),
    /**
     * Italic / regular emphasis.
     */
    Emphasis("emphasis"),
    /**
     * Highlighted text (marker pen).
     */
    Highlight("highlight"),
    /**
     * Subscript text.
     */
    Subscript("subscript"),
    /**
     * Superscript text.
     */
    Superscript("superscript"),
    /**
     * Inserted text (tracked change).
     */
    Insert("insert"),
    /**
     * Deleted text (tracked change).
     */
    Delete("delete"),
    /**
     * Inline code span.
     */
    Code("code"),
    /**
     * Hyperlink with URL.
     */
    Link("link"),
    /**
     * Inline image reference.
     */
    Image("image"),
    /**
     * Generic inline span with optional attributes.
     */
    Span("span"),
    /**
     * Inline mathematical expression.
     */
    Math("math"),
    /**
     * Raw inline content in a specified format.
     */
    RawInline("raw_inline"),
    /**
     * Footnote reference marker.
     */
    FootnoteRef("footnote_ref"),
    /**
     * Named symbol or emoji shortcode.
     */
    Symbol("symbol");


    /** The string value. */
    private final String value;

    InlineType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static InlineType fromValue(final String value) {
        for (InlineType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown InlineType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
