// DO NOT EDIT - auto-generated by alef
// alef:hash:12d5017c2d9e684c93b33fb432e26be857228e6897c01de2278482252751fe25
package io.xberg;

/**
 * A required optional system dependency (e.g. `tesseract`) was not found.
 */
public class MissingDependencyException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new MissingDependencyException with the given message. */
  public MissingDependencyException(final String message) {
    super(message);
  }

  /** Creates a new MissingDependencyException with the given message and cause. */
  public MissingDependencyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
