// DO NOT EDIT - auto-generated by alef
// alef:hash:209a244862e56919f9675a72596b4bcd9283654720164e27cad36e49934090ab
package io.xberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
