// DO NOT EDIT - auto-generated by alef
// alef:hash:8be48e406e8ed15d017b0bfd64fa1e32e10d862b7a4b3834d40e96d3379c0519
package io.xberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
