// DO NOT EDIT - auto-generated by alef
// alef:hash:70f002808d2ae79f0f5135f47c0c282e1162631902e4b57c6829abfd62ec4fb5
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
