// DO NOT EDIT - auto-generated by alef
// alef:hash:70f002808d2ae79f0f5135f47c0c282e1162631902e4b57c6829abfd62ec4fb5
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) {
    super(message);
  }

  /** Creates a new PdfAnalysisErrorException with the given message and cause. */
  public PdfAnalysisErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
