// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:446748155774867df28fecd60b1f51d93e20d7476cf9f2aad1cd588a1cf0950e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Thresholds for the structured-extraction call-mode heuristic.
 *
 * All defaults are **conservative starting points**.  Deployments should
 * measure their own document corpus and override via their own config;
 * these values are chosen to be safe-by-default, not to be optimal for
 * any particular workload.
 *
 * Construct custom thresholds with struct-update syntax:
 *
 * use xberg.heuristics.StructuredThresholds;
 * let t = StructuredThresholds {
 *     enable_vision_fallback: true,
 *     ..StructuredThresholds.default()
 * };
 *
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StructuredThresholds.Builder.class)
public record StructuredThresholds(
    @JsonProperty("scan_max_coverage") double scanMaxCoverage,
    @JsonProperty("digital_min_coverage") double digitalMinCoverage,
    @JsonProperty("docx_text_min_density") double docxTextMinDensity,
    @JsonProperty("enable_vision_fallback") boolean enableVisionFallback
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for StructuredThresholds deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("scan_max_coverage")
        private double scanMaxCoverage;
        @JsonProperty("digital_min_coverage")
        private double digitalMinCoverage;
        @JsonProperty("docx_text_min_density")
        private double docxTextMinDensity;
        @JsonProperty("enable_vision_fallback")
        private boolean enableVisionFallback;

        /** Sets the scanMaxCoverage field. */
        @JsonProperty("scan_max_coverage")
        public Builder withScanMaxCoverage(final double value) {
            this.scanMaxCoverage = value;
            return this;
        }

        /** Sets the digitalMinCoverage field. */
        @JsonProperty("digital_min_coverage")
        public Builder withDigitalMinCoverage(final double value) {
            this.digitalMinCoverage = value;
            return this;
        }

        /** Sets the docxTextMinDensity field. */
        @JsonProperty("docx_text_min_density")
        public Builder withDocxTextMinDensity(final double value) {
            this.docxTextMinDensity = value;
            return this;
        }

        /** Sets the enableVisionFallback field. */
        @JsonProperty("enable_vision_fallback")
        public Builder withEnableVisionFallback(final boolean value) {
            this.enableVisionFallback = value;
            return this;
        }

        /** Constructs a StructuredThresholds instance from the builder's current state. */
        public StructuredThresholds build() {
            return new StructuredThresholds(
                scanMaxCoverage,
                digitalMinCoverage,
                docxTextMinDensity,
                enableVisionFallback
            );
        }
    }
    // CPD-ON
}
