# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:209a244862e56919f9675a72596b4bcd9283654720164e27cad36e49934090ab
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'renderer_management' do
  it 'renderers_clear: Clear all renderers and verify list is empty' do
    Xberg.clear_renderers()

  end

  it 'renderers_list: List all registered renderers' do
    result = Xberg.list_renderers()

    expect(result).not_to be_nil
  end
end
