// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9d32d98f25cf93c467bec287b2b76cb901f14fb674ad9f7a481cd5dbacffc5a8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Kreuzberg

/// E2e tests for category: configuration.
final class ConfigurationTests: XCTestCase {
    func testConfigDiscover() async throws {
        // Discover configuration from current or parent directories
        let result = try await extractFile("")
        XCTAssertFalse(result.result.chunking.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.result.chunking.max_chars, 50)
    }

    func testConfigFromFile() async throws {
        // Load configuration from a TOML file
        let result = try await extractFile("")
        XCTAssertFalse(result.result.chunking.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.result.chunking.max_chars, 100)
        XCTAssertEqual(result.result.chunking.max_overlap, 20)
        XCTAssertFalse(result.result.language_detection.isEmpty, "expected non-empty value")
        XCTAssertEqual(result.result.language_detection.enabled, false)
    }

}
