// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5dbff18ceca7019fcddc210e02b307dbd0bc8f671db9636199d19b3a52a7b58c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Kreuzberg

/// E2e tests for category: xml.
final class XmlTests: XCTestCase {
    func testXmlPlantCatalog() async throws {
        // XML plant catalog to validate streaming XML extraction.
        let result = try await extractFile("xml/plant_catalog.xml")
        XCTAssertEqual(result.mime_type.trimmingCharacters(in: .whitespaces), "application/xml")
        XCTAssertGreaterThanOrEqual(result.content.count, 100)
    }

}
