// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8a44f3b95b7d3e50883becd244543c7abdcc4ed1895cba40b4e1e609c845e363
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: tokenizer_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_TokenizerBackendsClear(t *testing.T) {
	// Clear all tokenizer backends and verify list is empty
	_ = xberg.ClearTokenizerBackends()
}

func Test_TokenizerBackendsList(t *testing.T) {
	// List all registered tokenizer backends
	_, err := xberg.ListTokenizerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
